#include "pch.h"
#include "TypeInfo.h"

NativeTypeInfo g_TypeInfoSX(NativeType::SX);
NativeTypeInfo g_TypeInfoS8(NativeType::S8);
NativeTypeInfo g_TypeInfoS16(NativeType::S16);
NativeTypeInfo g_TypeInfoS32(NativeType::S32);
NativeTypeInfo g_TypeInfoS64(NativeType::S64);
NativeTypeInfo g_TypeInfoUX(NativeType::UX);
NativeTypeInfo g_TypeInfoU8(NativeType::U8);
NativeTypeInfo g_TypeInfoU16(NativeType::U16);
NativeTypeInfo g_TypeInfoU32(NativeType::U32);
NativeTypeInfo g_TypeInfoU64(NativeType::U64);
NativeTypeInfo g_TypeInfoBool(NativeType::Bool);
NativeTypeInfo g_TypeInfoF32(NativeType::F32);
NativeTypeInfo g_TypeInfoF64(NativeType::F64);
NativeTypeInfo g_TypeInfoFX(NativeType::FX);
NativeTypeInfo g_TypeInfoChar(NativeType::Char);
NativeTypeInfo g_TypeInfoString(NativeType::String);