var cptcpt = 0

#compiler(swag.CompilerMsgKindMask.SemanticFunc)
{
    //cpt := 0's64

    /*msg := cast(const *swag.CompilerMessage) @msg()
    while msg != null
    {
        cptcpt += 1
        msg = cast(const *swag.CompilerMessage) @msg()
        if msg == null
            break

        /*@print(msg.name)
        @print(" ")
        @print(msg.type.name)
        @print("\n")*/
    }*/

    //@print(cptcpt)
    //@print(" ")

    /*msg := cast(const *swag.CompilerMessage) @msg()
    @print(msg.name)
    @print(" ")
    @print(msg.type.name)
    @print("\n")*/
}
