//#[swag.printbc]
#test
{
    /*@print(cast(f64) @sqrt(5.0'f32))
    @print("\n")
    @print(cast(f64) @sqrt(5.0'f64))
    @print("\n")

    @print(cast(f64) @sin(5.0'f32))
    @print("\n")
    @print(cast(f64) @sin(5.0'f64))
    @print("\n")
    @print(cast(f64) @cos(5.0'f32))
    @print("\n")
    @print(cast(f64) @cos(5.0'f64))
    @print("\n")

    @print(cast(f64) @log(5.0'f32))
    @print("\n")
    @print(cast(f64) @log(5.0'f64))
    @print("\n")
    @print(cast(f64) @log2(5.0'f32))
    @print("\n")
    @print(cast(f64) @log2(5.0'f64))
    @print("\n")
    @print(cast(f64) @log10(5.0'f32))
    @print("\n")
    @print(cast(f64) @log10(5.0'f64))
    @print("\n")*/

    /*@print(cast(f64) @floor(5.4'f32))
    @print("\n")
    @print(cast(f64) @floor(5.4'f64))
    @print("\n")
    @print(cast(f64) @ceil(5.4'f32))
    @print("\n")
    @print(cast(f64) @ceil(5.4'f64))
    @print("\n")
    @print(cast(f64) @trunc(5.4'f32))
    @print("\n")
    @print(cast(f64) @trunc(5.4'f64))
    @print("\n")
    @print(cast(f64) @round(5.4'f32))
    @print("\n")
    @print(cast(f64) @round(5.4'f64))
    @print("\n")*/

    @print(cast(f64) @abs(-5.4'f32))
    @print("\n")
    @print(cast(f64) @abs(-5.4'f64))
    @print("\n")
}