/// Enumerates gamepad buttons
enum GamePadButton
{
    /// A button
    A
    /// B button
    B
    Back
    BigButton
    DPadDown
    DPadLeft
    DPadRight
    DPadUp
    LeftShoulder
    LeftStick
    LeftThumbstickDown
    LeftThumbstickLeft
    LeftThumbstickRight
    LeftThumbstickUp
    LeftTrigger
    RightShoulder
    RightStick
    RightThumbstickDown
    RightThumbstickLeft
    RightThumbstickRight
    RightThumbstickUp
    RightTrigger
    Start
    X
    Y
}