/*

User identifiers start with '_' or an ascii letter.
Identifiers can contain '_', an ascii letter or a digit number.

thisIsAValidIdentifier0
this_is_also_valid
this_1_is_2_also__3_valid

User identifiers cannot start with two underscores. This is reserved by the compiler.

Some identifiers start with '#'. This indicates a compiler special keyword.

#assert
#run
#main
...

Some identifiers start with '@'. This indicates a buildin (intrinsic) function.

@min()
@max()
@sqrt()
...

*/