#global skip

// This is the list of all keywords:

// Compiler keywords
// -----------------

#abi
#arch
#callerfunction
#callerlocation
#cfg
#code
#defined
#file
#function
#global
#hastag
#line
#load
#location
#os
#scopefct
#semerror
#swagbuildnum
#swagos
#swagrevision
#swagversion
#tagval

#assert
#checkif
#elif
#else
#if
#import
#inline
#macro
#mixin
#placeholder
#print
#selectif

#ast
#compiler
#drop
#init
#main
#run
#test

// Intrinsics
// ----------

@abs
@acos
@alloc
@args
@asin
@assert
@atan
@atomadd
@atomand
@atomcmpxchg
@atomor
@atomxchg
@atomxor
@bcdbg
@bitcountlz
@bitcountnz
@bitcounttz
@byteswap
@ceil
@compiler
@cos
@cosh
@cstrlen
@errormsg
@exp
@exp2
@floor
@free
@getcontext
@isbytecode
@log
@log10
@log2
@max
@memcmp
@memcpy
@memmove
@memset
@min
@panic
@pow
@print
@realloc
@round
@setcontext
@seterr
@sin
@sinh
@sqrt
@strcmp
@tan
@tanh
@trunc
@typecmp

@alignof
@countof
@dataof
@drop
@err
@index
@init
@isconstexpr
@kindof
@mkany
@mkcallback
@mkforeign
@mkinterface
@mkslice
@mkstring
@offsetof
@postcopy
@postmove
@reloc
@sizeof
@spread
@stringof
@typeof

// Language keywords
// -----------------

alias
assume
attr
autocast
bitcast
cast
catch
code
const
discard
enum
false
func
impl
interface
move
namespace
nodrop
null
private
protected
public
retval
struct
throw
true
try
typeinfo
typeset
union
using
var

break
case
continue
default
defer
else
errdefer
fallthrough
for
if
label
loop
return
switch
visit
while

// Basic types
// -----------

any
bool
char
f32
f64
s8
s16
s32
s64
int
u8
u16
u32
u64
uint
void
string