..\bin\swag_stats clean --script

..\bin\swag_stats ..\bin\examples\scripts\chess.swgs      --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\mine.swgs       --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\pong.swgs       --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\verlet.swgs     --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\mandelbrot.swgs --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\matrix.swgs     --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\gameoflife.swgs --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\clock.swgs      --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\blob.swgs       --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\swag.swgs       --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\pendulum.swgs   --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\cards.swgs      --args:"swag.test"
..\bin\swag_stats ..\bin\examples\scripts\calc.swgs       --args:"swag.test"