..\bin\swag_devmode clean --script

..\bin\swag_devmode run -w:..\bin\examples -m:wnd    --script --args:"swag.test"
..\bin\swag_devmode run -w:..\bin\examples -m:captme --script --args:"swag.test"
..\bin\swag_devmode run -w:..\bin\examples -m:draw   --script --args:"swag.test"
..\bin\swag_devmode run -w:..\bin\examples -m:wnd    --args:"swag.test"
..\bin\swag_devmode run -w:..\bin\examples -m:captme --args:"swag.test"
..\bin\swag_devmode run -w:..\bin\examples -m:draw   --args:"swag.test"

..\bin\swag_devmode ..\bin\examples\scripts\chess.swgs      --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\mine.swgs       --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\pong.swgs       --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\verlet.swgs     --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\mandelbrot.swgs --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\matrix.swgs     --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\gameoflife.swgs --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\clock.swgs      --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\blob.swgs       --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\swag.swgs       --args:"swag.test"
..\bin\swag_devmode ..\bin\examples\scripts\pendulum.swgs   --args:"swag.test"