SWAG_ERROR(Err0000, "fatal error: invalid swag command `%s`")
SWAG_ERROR(Err0001, "compare operation not allowed on type `%s`")
SWAG_ERROR(Err0002, "type `%s` cannot be used in a range expression")
SWAG_ERROR(Err0004, "cannot select function `%s` because `%s` has failed")
SWAG_ERROR(Err0005, "operation `%s` not allowed on %s `%s`")
SWAG_ERROR(Err0006, "parameter `%d` should be named because some parameters before are named")
SWAG_ERROR(Err0007, "comparison operations are invalid on tuple types")
SWAG_ERROR(Err0008, "unknown named parameter `%s`")
SWAG_ERROR(Err0009, "slice can only be compared to `null`")
SWAG_ERROR(Err0010, "an interface can only be compared to `null`")
SWAG_ERROR(Err0011, "named parameter `%s` already defined")
SWAG_ERROR(Err0012, "expected an expression, found a type")
SWAG_ERROR(Err0013, "%s `%s` cannot be referenced in that context because it`s not a value")
SWAG_ERROR(Err0014, "fatal error: not enough memory !")
SWAG_ERROR(Err0015, "bytecode stack overflow (maximum stack size is `--stack-size:%s`)")
SWAG_ERROR(Err0016, "not enough parameters for %s")
SWAG_ERROR(Err0017, "invalid type declaration, symbol `%s` is not a type (it`s %s)")
SWAG_ERROR(Err0018, "cannot make %s public because %s `%s` is not public")
SWAG_ERROR(Err0020, "missing function call `()` to %s")
SWAG_ERROR(Err0021, "array dimension cannot be evaluated at compile time")
SWAG_ERROR(Err0022, "array dimension should be of type integer, but is `%s`")
SWAG_ERROR(Err0023, "array dimension is 0")
SWAG_ERROR(Err0024, "pointer to `Swag.TypeInfo` should be `const`")
SWAG_ERROR(Err0025, "alias is public but `%s` is not")
SWAG_ERROR(Err0026, "too many parameters for %s")
SWAG_ERROR(Err0027, "alias can only be used with a type or an identifier")
SWAG_ERROR(Err0028, "`Swag.Strict` attribute can only be used on a type alias")
SWAG_ERROR(Err0029, "cannot alias a struct member")
SWAG_ERROR(Err0030, "alias cannot be used on %s")
SWAG_ERROR(Err0031, "invalid bitcast type `%s` (should be integer, rune or float)")
SWAG_ERROR(Err0032, "cannot bitcast from type `%s` (should be integer, pointer, rune or float)")
SWAG_ERROR(Err0033, "cannot bitcast to a type with a bigger size (`%s` from `%s`)")
SWAG_ERROR(Err0034, "ambiguous conversion of struct `%s` to interface `%s`")
SWAG_ERROR(Err0035, "not enough generic parameters for %s")
SWAG_ERROR(Err0036, "error: backend: cannot locate windows sdk folder")
SWAG_ERROR(Err0037, "cannot instantiate generic %s `%s` with an untyped integer, you need to specify a type")
SWAG_ERROR(Err0038, "cannot instantiate generic %s `%s` with an untyped float, you need to specify a type")
SWAG_ERROR(Err0039, "cannot instantiate generic struct `%s`, missing contextual types replacements")
SWAG_ERROR(Err0040, "partial type alias `%s` for generic struct instantiation is not supported")
SWAG_ERROR(Err0041, "cannot instantiate generic function `%s`, missing generic parameters")
SWAG_ERROR(Err0042, "cannot instantiate generic function `%s`, missing contextual types replacements")
SWAG_ERROR(Err0043, "cannot instantiate variable because type `%s` is generic")
SWAG_ERROR(Err0044, "too many generic parameters for %s `%s`")
SWAG_ERROR(Err0045, "cannot create `%s` process (::CreatePipe)")
SWAG_ERROR(Err0046, "cannot create process `%s`")
SWAG_ERROR(Err0047, "bad type of parameter `%d` for %s, generic type `%s` is assigned to `%s` (`%s` provided)")
SWAG_ERROR(Err0048, "invalid type (`*Swag.CVaList` expected, `%s` provided")
SWAG_ERROR(Err0049, "missing generic parameters when calling %s")
SWAG_ERROR(Err0050, "bad type of parameter `%d` for %s (`%s` is expected for field `%s`, `%s` provided)")
SWAG_ERROR(Err0051, "cannot add `%s` to the `PATH` environment variable")
SWAG_ERROR(Err0052, "failed to start watcher service !")
SWAG_ERROR(Err0053, "bad type of parameter `%d` for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0054, "bad generic parameter `%d` for %s (type expected, value provided)")
SWAG_ERROR(Err0055, "failed to update watcher service !")
SWAG_ERROR(Err0056, "x64 backend unsupported os `%s`")
SWAG_ERROR(Err0057, "bad generic parameter `%d` for %s (value expected, type provided)")
SWAG_ERROR(Err0058, "cannot convert type `%s` to a constant expression")
SWAG_ERROR(Err0059, "cannot convert slice of type `%s` to a constant expression")
SWAG_ERROR(Err0060, "cannot reference a compiler constant at runtime")
SWAG_ERROR(Err0061, "invalid number of arguments for special function `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0062, "too few arguments for special function `%s` (at least `%d` expected, only `%d` provided)")
SWAG_ERROR(Err0063, "missing return type for special function `%s`")
SWAG_ERROR(Err0064, "missing return type for special function `%s` (`%s` expected)")
SWAG_ERROR(Err0065, "invalid return type for special function `%s` (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0066, "invalid parameter `%d` for special function `%s` (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0067, "special function `%s` should be defined in a `impl` scope")
SWAG_ERROR(Err0068, "missing parameters for special function `%s`")
SWAG_ERROR(Err0069, "invalid first parameter type for special function `%s` (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0070, "bad type of generic parameter `%d` for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0071, "invalid number of generic parameters for special function `%s`")
SWAG_ERROR(Err0072, "invalid generic parameter for special function `%s` (`string` expected, `%s` provided)")
SWAG_ERROR(Err0073, "invalid number of generic parameters for special function `%s`")
SWAG_ERROR(Err0074, "invalid generic parameter for special function `%s` (`bool` expected, `%s` provided)")
SWAG_ERROR(Err0075, "`opVisit` should have the `Swag.Macro` attribute")
SWAG_ERROR(Err0076, "call level limit reached (maximum level is `--max-recurse:%d`)")
SWAG_ERROR(Err0077, "invalid parameter `2` for special function `%s` (cannot be of type `%s`)")
SWAG_ERROR(Err0078, "special function `%s` (starting with `op` followed by a letter in upper case) is unknown")
SWAG_ERROR(Err0079, "cannot find special function `%s` in `%s`")
SWAG_ERROR(Err0080, "unexpected end of file found in comment")
SWAG_ERROR(Err0081, "invalid character `%s`")
SWAG_ERROR(Err0082, "struct `%s` should be initialized in place with `{}` and not parenthesis (this is reserved for function calls)")
SWAG_ERROR(Err0083, "%s `%s` is deprecated")
SWAG_ERROR(Err0084, "`@runes` should have a string as a parameter (`%s` provided)")
SWAG_ERROR(Err0085, "identifier `%s` cannot be dereferenced like a struct (type is `%s`)")
SWAG_ERROR(Err0086, "variable `%s` has only been used to find function `%s`; use scope `%s` instead")
SWAG_ERROR(Err0087, "only calls to `Swag.Mixin` functions can be done at global scope (`%s` is %s)")
SWAG_ERROR(Err0088, "%s is not declared with the `Swag.Mixin` attribute, and this is mandatory for a function call at global scope")
SWAG_ERROR(Err0089, "`%s` cannot be evaluated at compile time")
SWAG_ERROR(Err0090, "cannot evaluate function parameter at compile time (type is `%s`)")
SWAG_ERROR(Err0091, "cannot reference compile time %s `%s` (marked with `Swag.Compiler`) from runtime %s")
SWAG_ERROR(Err0092, "unused return value of lambda `%s`")
SWAG_ERROR(Err0093, "identifier `%s` cannot be found in tuple")
SWAG_ERROR(Err0094, "cannot discard a function call that returns nothing")
SWAG_ERROR(Err0095, "bad type of ufcs (first) parameter for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0096, "unused variable `%s`")
SWAG_ERROR(Err0097, "%s `%s` has not been used as the first parameter to call `%s`")
SWAG_ERROR(Err0098, "function `%s` should be called with `()` and not curlies (this is reserved for struct initialization)")
SWAG_ERROR(Err0099, "unexpected aliased identifiers because function `%s` is not a macro or a mixin")
SWAG_ERROR(Err0100, "cannot reference `opInit` special function (use `@init` instead)")
SWAG_ERROR(Err0101, "cannot reference `opDrop` special function (use `@drop` instead)")
SWAG_ERROR(Err0102, "evaluation of a function parameter of type `%s` is not supported at compile time")
SWAG_ERROR(Err0103, "cannot reference `opPostCopy` special function (use `@postcopy` instead)")
SWAG_ERROR(Err0104, "cannot reference `opPostMove` special function (use `@postmove` instead)")
SWAG_ERROR(Err0105, "cannot call empty function `%s`")
SWAG_ERROR(Err0106, "bad type of `self` parameter for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0107, "cannot reference compile time function `%s` (marked with `Swag.Compiler`) from runtime %s")
SWAG_ERROR(Err0108, "cannot reference `Swag.Test` function `%s` from `%s`")
SWAG_ERROR(Err0109, "unused return value of function `%s`")
SWAG_ERROR(Err0110, "identifier `%s` cannot be found in %s `%s`")
SWAG_ERROR(Err0111, "during public export")
SWAG_ERROR(Err0112, "during generic expansion")
SWAG_ERROR(Err0113, "found %d overloads for `%s` but no one could match")
SWAG_ERROR(Err0114, "cannot take the address of a function with call parameters")
SWAG_ERROR(Err0115, "ambiguous resolution of generic %s `%s`")
SWAG_ERROR(Err0116, "ambiguous resolution of symbol `%s`")
SWAG_ERROR(Err0117, "cannot use `with` or `using` on two variables with the same type")
SWAG_ERROR(Err0118, "during inline expansion")
SWAG_ERROR(Err0119, "missing function call parameters")
SWAG_ERROR(Err0120, "field name `%s` cannot be found in tuple")
SWAG_ERROR(Err0121, "expected a single identifier %s")
SWAG_ERROR(Err0122, "unknown identifier `%s`")
SWAG_ERROR(Err0123, "generic value `%s` has already been deduced from parameters to be `%s` (and `%s` is provided here)")
SWAG_ERROR(Err0124, "invalid lambda call, `%s` is not a variable (it`s %s)")
SWAG_ERROR(Err0125, "identifier `%s` has call parameters, but is a variable of type `%s` and not a function")
SWAG_ERROR(Err0126, "`opSlice` special function should return a string or a slice (`%s` provided)")
SWAG_ERROR(Err0127, "identifier `%s` has call parameters, but is %s and not a function")
SWAG_ERROR(Err0128, "during `#selectif` validation of function call")
SWAG_ERROR(Err0129, "during `#checkif` validation of function call")
SWAG_ERROR(Err0130, "invalid generic parameters, identifier `%s` is %s and not a function or a struct")
SWAG_ERROR(Err0132, "invalid reference to file scope")
SWAG_ERROR(Err0133, "cannot resolve identifier `%s`")
SWAG_ERROR(Err0135, "backtick can only be used inside an inline/macro block")
SWAG_ERROR(Err0136, "back ticked identifier can only be used inside a `Swag.Macro` function or an `#inline` block")
SWAG_ERROR(Err0137, "`%s` cannot be used inside a struct special function")
SWAG_ERROR(Err0138, "`%s` can only be used inside a function marked with `throw`, and `%s` is not")
SWAG_ERROR(Err0139, "`%s` can only be used before a function call, and `%s` is %s")
SWAG_ERROR(Err0140, "unknown compiler instruction `%s`")
SWAG_ERROR(Err0141, "expected `[`, `{`, `(`, `\"` or an intrinsic name, found character `%c`")
SWAG_ERROR(Err0142, "operator `+` not allowed with operand type `%s`")
SWAG_ERROR(Err0143, "operator `+` not allowed on type `%s`")
SWAG_ERROR(Err0144, "pointer arithmetic not allowed on `typeinfo`")
SWAG_ERROR(Err0145, "invalid number syntax, a digit separator `_` cannot be followed by another digit separator")
SWAG_ERROR(Err0146, "operator `-` not allowed with operand type `%s`")
SWAG_ERROR(Err0147, "operator `-` not allowed on type `%s`")
SWAG_ERROR(Err0148, "operator `*` not allowed on type `%s`")
SWAG_ERROR(Err0149, "operator `/` not allowed on type `%s`")
SWAG_ERROR(Err0150, "division by zero")
SWAG_ERROR(Err0151, "invalid number syntax, missing at least one digit")
SWAG_ERROR(Err0152, "invalid number syntax, a digit separator `_` cannot end a literal number")
SWAG_ERROR(Err0153, "error reading source file `%s`")
SWAG_ERROR(Err0154, "invalid number syntax, a digit separator `_` cannot start a literal number")
SWAG_ERROR(Err0155, "invalid number syntax, a digit separator `_` cannot start a fractional part")
SWAG_ERROR(Err0156, "invalid number syntax, a digit separator `_` cannot start an exponent part")
SWAG_ERROR(Err0157, "operator `%` not allowed on type `%s`")
SWAG_ERROR(Err0158, "not enough hexadecimal digit, %s")
SWAG_ERROR(Err0159, "`Swag.Tls` and `Swag.Compiler` attributes are exclusive")
SWAG_ERROR(Err0160, "cannot assign a function pointer to a constant")
SWAG_ERROR(Err0161, "cannot transform type `%s` to a constant array because `opCount` returns `0`")
SWAG_ERROR(Err0162, "cannot transform type `%s` to a constant array because `opSlice` returns an empty slice")
SWAG_ERROR(Err0163, "operator `|` not allowed on type `%s`")
SWAG_ERROR(Err0164, "operator `&` not allowed on type `%s`")
SWAG_ERROR(Err0165, nullptr)
SWAG_ERROR(Err0166, "fatal error: script file `%s` does not exist")
SWAG_ERROR(Err0167, "operator `^` not allowed on type `%s`")
SWAG_ERROR(Err0168, "invalid operation `%s` on a tuple type")
SWAG_ERROR(Err0169, "more than one module with name `%s` is present in the workspace (path is `%s`)")
SWAG_ERROR(Err0170, "operator `<<` not allowed on type `%s`")
SWAG_ERROR(Err0171, "expected the type of the array after dimensions, found `%s`")
SWAG_ERROR(Err0172, "operator `>>` not allowed on type `%s`")
SWAG_ERROR(Err0173, "shift operand should be `u32` and not `%s`")
SWAG_ERROR(Err0174, "invalid hexadecimal digit `%c`, %s")
SWAG_ERROR(Err0175, "cannot cast implicitly from `%s` to `%s`")
SWAG_ERROR(Err0176, "cannot cast, type `%s` does not implement interface `%s`")
SWAG_ERROR(Err0177, "cannot cast from `%s` to `%s`")
SWAG_ERROR(Err0178, "value `%I64d` is negative and not in the range of `u8`")
SWAG_ERROR(Err0179, "value `%I64u` is not in the range of `u8`")
SWAG_ERROR(Err0180, "value `%I64d` is negative and not in the range of `u16`")
SWAG_ERROR(Err0181, "value `%I64u` is not in the range of `u16`")
SWAG_ERROR(Err0182, "value `%I64d` is negative and not in the range of `u32`")
SWAG_ERROR(Err0183, "value `%I64u` is not in the range of `u32`")
SWAG_ERROR(Err0184, "`\\x` escape code needs 2 of them")
SWAG_ERROR(Err0185, "value `%I64d` is negative and not in the range of `u64`")
SWAG_ERROR(Err0186, "value `%I64d` is not in the range of `s8`")
SWAG_ERROR(Err0187, "value `%I64d` is not in the range of `s16`")
SWAG_ERROR(Err0188, "value `%I64d` is not in the range of `s32`")
SWAG_ERROR(Err0189, "value `%I64d` is not in the range of `s64`")
SWAG_ERROR(Err0190, "attribute declaration (`attr`), unlike function, cannot be marked with `throw`")
SWAG_ERROR(Err0191, "value `%I64d` is truncated in `f32`")
SWAG_ERROR(Err0192, "value `%I64u` is truncated in `f32`")
SWAG_ERROR(Err0193, "value `%lf` is truncated in `f32`")
SWAG_ERROR(Err0194, "value `%I64d` is truncated in `f64`")
SWAG_ERROR(Err0195, "value `%I64u` is truncated in `f64`")
SWAG_ERROR(Err0196, "not enough initializers for `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0197, "too many initializers for `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0198, "if this is an array literal and not a type declaration, use `@[` instead of `[`")
SWAG_ERROR(Err0199, "forbidden `opDrop` special function for `%s` because struct is marked with `Swag.ConstExpr`")
SWAG_ERROR(Err0200, "cannot cast from `%s` to `%s` because `%s` has multiple fields of type `%s` with `using`")
SWAG_ERROR(Err0201, "if this is a tuple literal and not a type declaration, use `@{` instead of `{`")
SWAG_ERROR(Err0202, "expected a type inside a tuple type definition, found `%s`")
SWAG_ERROR(Err0203, "cannot cast, not enough initializers (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0204, "cannot cast, too many initializers (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0205, "not enough parameters in tuple initialization (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0206, "cannot reference variable `%s` because it`s in another stack frame")
SWAG_ERROR(Err0207, "[safety] truncated bits when casting expression from `%s` to `%s`")
SWAG_ERROR(Err0208, "[safety] cast from a negative value of type `%s` to unsigned type `%s`")
SWAG_ERROR(Err0209, "[safety] integer overflow during `+` operation on type `%s`")
SWAG_ERROR(Err0210, "[safety] integer overflow during `-` operation on type `%s`")
SWAG_ERROR(Err0211, "[safety] integer overflow during `*` operation on type `%s`")
SWAG_ERROR(Err0212, "[safety] integer overflow during `+=` operation on type `%s`")
SWAG_ERROR(Err0213, "[safety] integer overflow during `-=` operation on type `%s`")
SWAG_ERROR(Err0214, "[safety] integer overflow during `*=` operation on type `%s`")
SWAG_ERROR(Err0215, "[safety] `<<` shift operand value on type `%s` is greater than `%d`")
SWAG_ERROR(Err0216, "[safety] `>>` shift operand value on type `%s` is greater than `%d`")
SWAG_ERROR(Err0217, "[safety] integer overflow during `<<` operation on type `%s`")
SWAG_ERROR(Err0218, "[safety] integer overflow during `>>` operation on type `%s`")
SWAG_ERROR(Err0219, "[safety] `@abs` integer overflow on type `%s`")
SWAG_ERROR(Err0220, "[safety] integer overflow when taking the negative value of type `%s`")
SWAG_ERROR(Err0221, "[safety] division by zero")
SWAG_ERROR(Err0222, "[safety] index out of range")
SWAG_ERROR(Err0223, "cannot open #load file `%s`")
SWAG_ERROR(Err0224, "`\\u` escape code needs 4 of them")
SWAG_ERROR(Err0225, "`%s[index] = %s` is impossible because special function `opIndexAffect` cannot be found in `%s`")
SWAG_ERROR(Err0226, "cannot access by index because special function `opIndex` cannot be found in type `%s`")
SWAG_ERROR(Err0227, "cannot access `%s` by index because special function `opIndex` cannot be found in type `%s`")
SWAG_ERROR(Err0228, nullptr)
SWAG_ERROR(Err0229, "[safety] bad slicing, lower bound is greater than upper bound")
SWAG_ERROR(Err0230, "[safety] bad slicing, upper bound is out of range")
SWAG_ERROR(Err0231, "copy semantic is forbidden for type `%s` because of `Swag.NoCopy` attribute")
SWAG_ERROR(Err0232, "`#dependencies` can only be used in the module configuration file (`module.swg`)")
SWAG_ERROR(Err0233, "`#selectif` expression should be of type `bool` (`%s` provided)")
SWAG_ERROR(Err0234, "`#ast` expression should be of type `string` (`%s` provided)")
SWAG_ERROR(Err0235, "`#import` can only be used inside a `#dependencies` block")
SWAG_ERROR(Err0236, "expected a type `string` as an `#assert` message (`%s` provided)")
SWAG_ERROR(Err0237, "`#assert` message string cannot be evaluated at compile time")
SWAG_ERROR(Err0238, "compiler assertion failed")
SWAG_ERROR(Err0239, "`#macro` can only be used inside a `Swag.Macro` function")
SWAG_ERROR(Err0240, "expression should be of type `code`, but is `%s`")
SWAG_ERROR(Err0241, "`#semerror` has not triggered an error")
SWAG_ERROR(Err0242, "filename cannot be evaluated at compile time")
SWAG_ERROR(Err0243, "`#load` parameter should be of type string (`%s` provided)")
SWAG_ERROR(Err0244, "cannot find file `%s`")
SWAG_ERROR(Err0245, "`@gettag` name expected, found a type")
SWAG_ERROR(Err0246, "an identifier marked with `#scopefct` cannot be used in a scope")
SWAG_ERROR(Err0247, "an identifier marked with `#scopefct` can only be used inside a function")
SWAG_ERROR(Err0248, "`@hastag` name cannot be evaluated at compile time")
SWAG_ERROR(Err0249, "`@hastag` parameter should be a string (`%s` provided)")
SWAG_ERROR(Err0250, "`@gettag` name value cannot be evaluated at compile time")
SWAG_ERROR(Err0251, "`@gettag` parameter should be a string, but is `%s`")
SWAG_ERROR(Err0252, "type `%s` and type `%s` defined in the command line for `%s` are incompatible")
SWAG_ERROR(Err0253, "`\\U` escape code needs 8 of them")
SWAG_ERROR(Err0254, "`#callerlocation` can only be used in a function parameter declaration")
SWAG_ERROR(Err0255, "`#callerfunction` can only be used in a function parameter declaration")
SWAG_ERROR(Err0256, "`#function` can only be used inside a function")
SWAG_ERROR(Err0257, "failed to load module `%s` while resolving foreign function `%s`: %s")
SWAG_ERROR(Err0258, "cannot resolve foreign function call to `%s`")
SWAG_ERROR(Err0259, "unrecognized character escape sequence `%c`")
SWAG_ERROR(Err0260, "invalid token `[`")
SWAG_ERROR(Err0261, "cannot convert boolean literal to `%s`")
SWAG_ERROR(Err0262, "invalid character literal `%s`; this is a string, not a character")
SWAG_ERROR(Err0263, "cannot convert character literal to `u8`, value `%u` is too big")
SWAG_ERROR(Err0264, "invalid operator modifier `%s`")
SWAG_ERROR(Err0265, "operator modifier `%s` already used once")
SWAG_ERROR(Err0266, "operator modifier `%s` is invalid for operator `%s`")
SWAG_ERROR(Err0267, "invalid compare operator `=`, did you mean `==` ?")
SWAG_ERROR(Err0268, "`#dependencies` can only be declared at the file level")
SWAG_ERROR(Err0269, "missing `#main` function (executable entry point)")
SWAG_ERROR(Err0270, "initializer list is empty")
SWAG_ERROR(Err0271, "variable name or `?` expected in tuple unpacking, found `%s`")
SWAG_ERROR(Err0272, "identifier `%s` starts with `__`, and this is reserved by the language")
SWAG_ERROR(Err0273, "unexpected generic parameters for variable `%s`")
SWAG_ERROR(Err0274, "unexpected call parameters for variable `%s`")
SWAG_ERROR(Err0275, "`@alias` special variable name should be followed by a number")
SWAG_ERROR(Err0276, "invalid special variable name `%s`, `@alias` should be followed by a number (`%s` provided)")
SWAG_ERROR(Err0277, "an `@alias` number should be in the range [0, 31] (`%u` provided)")
SWAG_ERROR(Err0278, "invalid variable name `%s` (cannot start with `@`)")
SWAG_ERROR(Err0279, "cannot decompose a tuple in %s")
SWAG_ERROR(Err0280, "cannot evaluate constant expression of type `%s` at compile time")
SWAG_ERROR(Err0281, "cannot evaluate constant expression of type `%s` at compile time, because struct is not marked with `Swag.ConstExpr`")
SWAG_ERROR(Err0282, "attempt to unpack `%d` variable(s), but the expression on the right contains `%d` element(s)")
SWAG_ERROR(Err0283, "`@gettag` default value expected, found a type")
SWAG_ERROR(Err0284, "`#import` location already defined as `%s`")
SWAG_ERROR(Err0285, "expected an identifier, found a literal")
SWAG_ERROR(Err0286, "`#import` version already defined as `%s`")
SWAG_ERROR(Err0287, "cannot convert character literal to `u16`, value `%u` is too big")
SWAG_ERROR(Err0288, "`#import` version invalid format")
SWAG_ERROR(Err0289, "version should be of the form `version.revision.buildnum`, with each number >= 0 or the `?` character")
SWAG_ERROR(Err0290, "expected a struct, but symbol `%s` is %s")
SWAG_ERROR(Err0291, "cannot unpack type `%s` (expected a struct)")
SWAG_ERROR(Err0292, "cannot unpack `%s` because it does not contain any field")
SWAG_ERROR(Err0293, "attempt to unpack `%u` variable(s), but the tuple on the right contains `%u` field(s)")
SWAG_ERROR(Err0294, "type to tuple conversion is not (yet?) supported for type `%s`")
SWAG_ERROR(Err0295, "struct cannot be initialized twice")
SWAG_ERROR(Err0296, "invalid variable name `%s` because `@alias` can only be used inside a macro or a mixin function")
SWAG_ERROR(Err0297, "attribute `Swag.Discardable` can only be used on a lambda variable (provided type is `%s`)")
SWAG_ERROR(Err0298, "constant should be initialized")
SWAG_ERROR(Err0299, "non mutable variable should be initialized")
SWAG_ERROR(Err0300, "reference should be initialized")
SWAG_ERROR(Err0301, "affect not allowed from an array")
SWAG_ERROR(Err0302, "cannot convert from `string` to `%s`")
SWAG_ERROR(Err0303, "missing initialization expression to deduce size of array")
SWAG_ERROR(Err0304, "invalid initialization expression for array (expected an array literal or `?`)")
SWAG_ERROR(Err0305, "constant should be explicitly initialized")
SWAG_ERROR(Err0306, "`slice` type should be declared as immutable with `const`, because right expression is const")
SWAG_ERROR(Err0307, "initialization expression is `void`")
SWAG_ERROR(Err0308, "cannot deduce type from `null`")
SWAG_ERROR(Err0309, "unable to deduce type of %s `%s`")
SWAG_ERROR(Err0310, "an enum variable should be initialized with a valid value or with `?`")
SWAG_ERROR(Err0311, "cannot create constant because type `%s` is generic")
SWAG_ERROR(Err0312, "cannot create variable because type `%s` is generic")
SWAG_ERROR(Err0313, "global variable cannot be declared as `public`")
SWAG_ERROR(Err0314, "invalid file format, should be ascii, utf-8 or utf-8-bom")
SWAG_ERROR(Err0315, "expected a variable name, found `%s`")
SWAG_ERROR(Err0316, "%s `%s` should be public because it is referenced in a public context")
SWAG_ERROR(Err0317, "cannot convert floating point number `%Lf`")
SWAG_ERROR(Err0318, "fatal error: missing script file; use `--file:<filename>.swgs` to specify a script to run")
SWAG_ERROR(Err0319, "fatal error: invalid script file extension; should be `.swgs` instead of `%s`")
SWAG_ERROR(Err0320, "cannot slice `%s` because special function `opSlice` cannot be found in type `%s`")
SWAG_ERROR(Err0321, "cannot evaluate tuple value at compile time because one of its members is not `Swag.ConstExpr`")
SWAG_ERROR(Err0322, "fatal error: invalid value for `--tag:%s` (%s)")
SWAG_ERROR(Err0323, "found `else` without a corresponding `if`")
SWAG_ERROR(Err0324, "found `#else` without a corresponding `#if`")
SWAG_ERROR(Err0325, "found `#elif` without a corresponding `#if`")
SWAG_ERROR(Err0326, "found `)` without a corresponding opening `(`")
SWAG_ERROR(Err0327, "found `}` without a corresponding opening `{`")
SWAG_ERROR(Err0328, "found `]` without a corresponding opening `[`")
SWAG_ERROR(Err0329, "missing `%s` %s")
SWAG_ERROR(Err0330, "expected `%s` instead of `%s` %s")
SWAG_ERROR(Err0331, "line break or `;` is expected before `%s` to close the %s")
SWAG_ERROR(Err0332, "cannot use operator `orelse` on type `%s`")
SWAG_ERROR(Err0333, "expected an alias name, found `%s`")
SWAG_ERROR(Err0334, "`self` can only be used inside a struct or `impl` block")
SWAG_ERROR(Err0335, "`#import` has a specific revision (`%d`) but undefined major version (`?`)")
SWAG_ERROR(Err0336, "`#import` has a specific build number (`%d`) but undefined revision (`?`)")
SWAG_ERROR(Err0337, "cannot use a range in a switch with an expression")
SWAG_ERROR(Err0338, "too many array dimensions (maximum is `254`)")
SWAG_ERROR(Err0339, "missing pointer declaration `*` after `const`")
SWAG_ERROR(Err0340, "too many pointer dimensions (maximim is `%u`)")
SWAG_ERROR(Err0341, "literal number `%I64u` is not in the range of `u8`")
SWAG_ERROR(Err0342, "pointer to reference is not (yet?) supported")
SWAG_ERROR(Err0343, "expected a type declaration, found `%s`")
SWAG_ERROR(Err0344, "fatal error: cannot delete file `%s`")
SWAG_ERROR(Err0345, "fatal error: cannot delete directory `%s`")
SWAG_ERROR(Err0346, "symbol `%s` already defined in parent scope")
SWAG_ERROR(Err0347, "fatal error: cannot create script file `%s`")
SWAG_ERROR(Err0348, "`#self` can only be used inside a function")
SWAG_ERROR(Err0349, "a %s definition should appear at file or namespace scope")
SWAG_ERROR(Err0350, "`%s` attribute cannot be used in a file marked with `#global export`, because the whole file is implicitly public")
SWAG_ERROR(Err0351, "found `elif` without a corresponding `if`")
SWAG_ERROR(Err0352, nullptr)
SWAG_ERROR(Err0353, "unexpected token `%s` after `protected` attribute")
SWAG_ERROR(Err0354, "unexpected token `%s` after `public` attribute")
SWAG_ERROR(Err0355, "expected an attribute name, found `%s`")
SWAG_ERROR(Err0356, "empty attribute usage")
SWAG_ERROR(Err0357, "literal number `%I64u` is not in the range of `u16`")
SWAG_ERROR(Err0358, "literal number `%I64u` is not in the range of `u32`")
SWAG_ERROR(Err0359, "literal number `%I64d` is not in the range of `s8`")
SWAG_ERROR(Err0360, "literal number `%I64d` is not in the range of `s16`")
SWAG_ERROR(Err0361, "literal number `%I64d` is not in the range of `s32`")
SWAG_ERROR(Err0362, "literal number `%I64u` is not in the range of `rune`")
SWAG_ERROR(Err0363, "value `%I64d` is truncated in `f32`")
SWAG_ERROR(Err0364, "`#mixin` replacement block can only be used inside a breakable statement (`loop`, `visit`, `for` ...)")
SWAG_ERROR(Err0365, "`#mixin` invalid replacement `%s`")
SWAG_ERROR(Err0366, "`#mixin` empty replacement block")
SWAG_ERROR(Err0367, "`#semerror` is invalid outside a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0368, "`#semerror` cannot be in a `#if` block")
SWAG_ERROR(Err0369, "`#global` should be defined first, at the top of the file")
SWAG_ERROR(Err0370, "`#global export` already defined")
SWAG_ERROR(Err0371, "`#global foreignlib` should be followed by a string")
SWAG_ERROR(Err0372, "value `%I64d` is truncated in `f64`")
SWAG_ERROR(Err0373, "invalid pass name `%s`")
SWAG_ERROR(Err0374, "`#global testerror` is invalid outside a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0375, "`#global testwarning` is invalid outside a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0376, "`#global` unexpected instruction `%s`")
SWAG_ERROR(Err0377, "`#import` can only be used in the module configuration file (`module.swg`)")
SWAG_ERROR(Err0378, "`#import` can only be declared at the top level scope")
SWAG_ERROR(Err0379, "`#import` should be followed by a string")
SWAG_ERROR(Err0380, "`#import` location defined twice")
SWAG_ERROR(Err0381, "invalid location `%s`")
SWAG_ERROR(Err0382, "`#import` version defined twice")
SWAG_ERROR(Err0383, "invalid version `%s`")
SWAG_ERROR(Err0384, "`#placeholder` can only be declared in a top level scope")
SWAG_ERROR(Err0385, "`#placeholder` should be followed by an identifier")
SWAG_ERROR(Err0386, "global `using` should be declared at the top of the file")
SWAG_ERROR(Err0387, "invalid literal number conversion of `%I64u`")
SWAG_ERROR(Err0388, "namespace definition should appear either at file scope or immediately within another namespace definition")
SWAG_ERROR(Err0389, "missing namespace name before `{`")
SWAG_ERROR(Err0390, "missing namespace name before `;`")
SWAG_ERROR(Err0391, "namespace name should be an identifier (`%s` provided)")
SWAG_ERROR(Err0392, "`swag` namespace is reserved by the compiler")
SWAG_ERROR(Err0393, "namespace cannot have the same name as the module (`%s`)")
SWAG_ERROR(Err0394, "literal number `%I64u` is not in the range of `u8`")
SWAG_ERROR(Err0395, "invalid label identifier `%s`")
SWAG_ERROR(Err0396, "expected an enum name, found `%s`")
SWAG_ERROR(Err0397, "fatal error: module `%s` already exists in the `/modules` folder")
SWAG_ERROR(Err0398, "literal number `%I64u` is not in the range of `u16`")
SWAG_ERROR(Err0399, "`{` is expected instead of `%s`")
SWAG_ERROR(Err0400, "expected an enum value identifier, found `%s`")
SWAG_ERROR(Err0401, "invalid token, identifier expected")
SWAG_ERROR(Err0402, "invalid token, `,` expected")
SWAG_ERROR(Err0403, "invalid named parameter `%s`")
SWAG_ERROR(Err0404, "literal number `%I64u` is not in the range of `u32`")
SWAG_ERROR(Err0405, "const before a function parameter name can only be followed by `self`")
SWAG_ERROR(Err0406, "`self` can only be used inside an `impl` block")
SWAG_ERROR(Err0407, "a method can only be declared inside a struct `impl` block")
SWAG_ERROR(Err0408, "invalid parameter name `%s`")
SWAG_ERROR(Err0409, "missing function parameter type or assignment (`:` or `=`)")
SWAG_ERROR(Err0410, "invalid variable name `%s`")
SWAG_ERROR(Err0411, "missing generic parameters")
SWAG_ERROR(Err0412, "missing generic name or type")
SWAG_ERROR(Err0413, "function names starting with `@` are reserved for intrinsics")
SWAG_ERROR(Err0414, "missing function name instead of `%s`")
SWAG_ERROR(Err0415, "literal number `%I64u` is not in the range of `s8`")
SWAG_ERROR(Err0416, "expected `{` to start the %s body, found `;`")
SWAG_ERROR(Err0417, "`@power` called with invalid values `%.3f` and `%.3f`")
SWAG_ERROR(Err0418, "cannot cast from immutable type `%s` to mutable `%s`")
SWAG_ERROR(Err0419, "semantic cycle detected during resolution of %s `%s`")
SWAG_ERROR(Err0422, "literal number `%I64u` is not in the range of `s16`")
SWAG_ERROR(Err0423, "`@log2` called with invalid value `%.3f`")
SWAG_ERROR(Err0424, "`@log10` called with invalid value `%.3f`")
SWAG_ERROR(Err0425, "`@sqrt` called with invalid value `%.3f`")
SWAG_ERROR(Err0426, "`@asin` called with invalid value `%.3f`")
SWAG_ERROR(Err0427, "`@acos` called with invalid value `%.3f`")
SWAG_ERROR(Err0428, "`@log` called with invalid value `%.3f`")
SWAG_ERROR(Err0429, "literal number `%I64u` is not in the range of `s32`")
SWAG_ERROR(Err0430, "literal number `%I64u` is not in the range of `s64`")
SWAG_ERROR(Err0431, "runtime variable `%s` is initialized to zero and cannot be changed at compile time; initialize it with `?` if this is intended")
SWAG_ERROR(Err0432, "literal number `%I64u` is not in the range of `rune`")
SWAG_ERROR(Err0433, "invalid literal number conversion of `%I64u`")
SWAG_ERROR(Err0434, "bytecode execution, ")
SWAG_ERROR(Err0435, "exception during compile time execution !")
SWAG_ERROR(Err0436, "it could be a bug in the compile time part of your program")
SWAG_ERROR(Err0437, "literal suffix type must be native (`%s` provided)")
SWAG_ERROR(Err0438, "`for` is invalid for an enum implementation block")
SWAG_ERROR(Err0439, "invalid literal suffix type (`%s`)")
SWAG_ERROR(Err0440, "invalid generic parameters, should be naked")
SWAG_ERROR(Err0441, "implementation block kind (%s) does not match the type of `%s` (%s)")
SWAG_ERROR(Err0442, "`@cvastart` intrinsic can only be used in a function with a last argument of type `cvarargs`")
SWAG_ERROR(Err0443, "`@cvaarg` unsupported type `%s`")
SWAG_ERROR(Err0444, "expected a struct name, found `%s`")
SWAG_ERROR(Err0445, "`@cvaarg` unsupported type `%s` (type has been promoted to '%s' at the call site)")
SWAG_ERROR(Err0446, "parameter of type `cvarargs` cannot be passed from function to function")
SWAG_ERROR(Err0447, "empty tuple definition")
SWAG_ERROR(Err0448, "identifier expected")
SWAG_ERROR(Err0449, "invalid token `%s` in tuple type, `,` or `}` are expected here")
SWAG_ERROR(Err0450, nullptr)
SWAG_ERROR(Err0451, "`using` on a member is invalid in an interface definition")
SWAG_ERROR(Err0452, nullptr)
SWAG_ERROR(Err0453, "`var` is not necessary to declare a field inside a struct")
SWAG_ERROR(Err0454, "invalid affect operator `==`, did you mean `=` ?")
SWAG_ERROR(Err0455, "expected `:` or `=` in variable declaration, found `%s`")
SWAG_ERROR(Err0456, nullptr)
SWAG_ERROR(Err0457, "variable should have a type or should be initialized")
SWAG_ERROR(Err0458, nullptr)
SWAG_ERROR(Err0459, "too many digits in literal number")
SWAG_ERROR(Err0460, "expected a binary digit, found `%s`")
SWAG_ERROR(Err0461, nullptr)
SWAG_ERROR(Err0462, "cannot take address of function parameter of type '%s'")
SWAG_ERROR(Err0463, "invalid hexadecimal digit `%s`")
SWAG_ERROR(Err0464, "literal number is too big (cannot fit in 64 bits)")
SWAG_ERROR(Err0465, "cannot take address of %s")
SWAG_ERROR(Err0466, "floating point number exponent should have at least one digit")
SWAG_ERROR(Err0467, "invalid literal number prefix `%s`")
SWAG_ERROR(Err0468, "index out of range (index is `%I64u`, maximum index is `%I64u`)")
SWAG_ERROR(Err0469, "cannot take address of constant")
SWAG_ERROR(Err0470, "invalid address expression")
SWAG_ERROR(Err0471, "cannot take address of a macro")
SWAG_ERROR(Err0472, "cannot take address of a mixin")
SWAG_ERROR(Err0473, "cannot take address of an inline function")
SWAG_ERROR(Err0474, "slicing operator cannot be applied on an array with multiple dimensions (type is `%s`)")
SWAG_ERROR(Err0475, "slicing operator cannot be applied on type `%s`")
SWAG_ERROR(Err0476, "bad slicing arguments, lower bound `%I64u` is greater than upper bound `%I64u`")
SWAG_ERROR(Err0477, "bad slicing arguments, upper bound `%I64u` is out of range")
SWAG_ERROR(Err0478, "type `%s` is immutable (`const`) and cannot be changed")
SWAG_ERROR(Err0479, nullptr)
SWAG_ERROR(Err0480, nullptr)
SWAG_ERROR(Err0481, "cannot dereference type `%s`")
SWAG_ERROR(Err0482, "cannot dereference a tuple type like a pointer or an array")
SWAG_ERROR(Err0483, nullptr)
SWAG_ERROR(Err0484, nullptr)
SWAG_ERROR(Err0485, "array access type should be integer, but is `%s`")
SWAG_ERROR(Err0486, "cannot dereference a `void` pointer")
SWAG_ERROR(Err0487, nullptr)
SWAG_ERROR(Err0488, "%s `%s` cannot be dereferenced like a pointer")
SWAG_ERROR(Err0489, "`@init` first parameter should be a pointer, but is `%s`")
SWAG_ERROR(Err0490, "`@init` count parameter should be an integer, but is `%s`")
SWAG_ERROR(Err0491, "too many initialization parameters for type `%s`")
SWAG_ERROR(Err0492, nullptr)
SWAG_ERROR(Err0493, "cannot call `@postcopy` on type `%s` because it is marked with the `Swag.NoCopy` attribute")
SWAG_ERROR(Err0494, nullptr)
SWAG_ERROR(Err0495, "`%s` first parameter should be a pointer, but is `%s`")
SWAG_ERROR(Err0496, "`%s` second parameter should be a pointer, but is `%s`")
SWAG_ERROR(Err0497, "`%s` second parameter should be a pointer to type `%s`, but points to `%s`")
SWAG_ERROR(Err0498, "`%s` count parameter should be an integer, but is `%s`")
SWAG_ERROR(Err0499, "unknown module dependency `%s`")
SWAG_ERROR(Err0500, "missing `%d` test errors (%d raised)")
SWAG_ERROR(Err0501, "missing `%d` test warnings (%d raised)")
SWAG_ERROR(Err0502, "cannot open file `%s`")
SWAG_ERROR(Err0503, nullptr)
SWAG_ERROR(Err0504, "operation `%s` not allowed, left type is `%s` and right type is `%s`")
SWAG_ERROR(Err0505, "%s overflow, maximum size is 0x%I64x bytes")
SWAG_ERROR(Err0506, nullptr)
SWAG_ERROR(Err0507, "fatal error: invalid module `%s`, configuration file `%s` is missing")
SWAG_ERROR(Err0508, "cannot find `%s` in module folder `%s`")
SWAG_ERROR(Err0509, "cannot access file `%s`")
SWAG_ERROR(Err0510, "cannot fetch file `%s` for module dependency `%s`")
SWAG_ERROR(Err0511, "dependency module folder `%s` does not exist")
SWAG_ERROR(Err0512, "a %s cannot be marked with `Swag.NoReturn` attribute")
SWAG_ERROR(Err0513, "cannot resolve module dependency `%s` (`location` is empty)")
SWAG_ERROR(Err0514, "invalid `location` format; should have the form `location=\"mode@accesspath\"`")
SWAG_ERROR(Err0515, "invalid `location` mode; should be `swag` or `disk`, not `%s`")
SWAG_ERROR(Err0516, "cannot resolve dependency to module `%s` because of two different major versions (`%d` and `%d`)")
SWAG_ERROR(Err0517, nullptr)
SWAG_ERROR(Err0518, "cannot resolve dependency to module `%s`, version `%s` cannot be found at location `%s`")
SWAG_ERROR(Err0519, "command line error: invalid --stack-size value (%s), valid range is [%s, %s]")
SWAG_ERROR(Err0520, nullptr)
SWAG_ERROR(Err0521, nullptr)
SWAG_ERROR(Err0522, "command line error: invalid os `%s` for x64 backend")
SWAG_ERROR(Err0523, "command line error: invalid arch `%s` for x64 backend")
SWAG_ERROR(Err0524, "cannot open file `%s` for writing")
SWAG_ERROR(Err0525, "cannot write to file `%s`")
SWAG_ERROR(Err0526, "[safety] `@memcpy` destination pointer is null")
SWAG_ERROR(Err0527, "[safety] `@memcpy` source pointer is null")
SWAG_ERROR(Err0528, "[safety] `@memmove` destination pointer is null")
SWAG_ERROR(Err0529, "[safety] `@memmove` source pointer is null")
SWAG_ERROR(Err0530, "[safety] `@memset` destination pointer is null")
SWAG_ERROR(Err0531, "[safety] `@memcmp` first pointer is null")
SWAG_ERROR(Err0532, "[safety] `@memcmp` second pointer is null")
SWAG_ERROR(Err0533, "[safety] `@strlen` pointer is null")
SWAG_ERROR(Err0534, "uncatched error when calling `%s`; missing `try`, `assume` or `catch`")
SWAG_ERROR(Err0535, "`%s` can only be used before a function call that can raise errors (function marked with `throw`)")
SWAG_ERROR(Err0536, "stack overflow (maximum stack size is `--stack-size:%s`)")
SWAG_ERROR(Err0537, "cannot convert typeinfo `%s` to runtime typeinfo")
SWAG_ERROR(Err0538, "fatal error: invalid value `%s` for command line `--tag:%s`; this is not a valid literal")
SWAG_ERROR(Err0539, "fatal error: command line --tag `%s` unsupported type `%s`")
SWAG_ERROR(Err0540, "fatal error: missing workspace folder `--workspace`")
SWAG_ERROR(Err0541, "fatal error: workspace folder `%s` does not exist")
SWAG_ERROR(Err0542, "fatal error: invalid workspace `%s`, subfolder `modules/` or `tests/` does not exist")
SWAG_ERROR(Err0543, "fatal error: cannot create public directory `%s`")
SWAG_ERROR(Err0544, "[safety] pointer to `Swag.CVaList` is null")
SWAG_ERROR(Err0545, "fatal error: cannot create target directory `%s`")
SWAG_ERROR(Err0546, "fatal error: cache directory `%s` does not exist")
SWAG_ERROR(Err0547, "fatal error: cannot create cache directory `%s`")
SWAG_ERROR(Err0548, nullptr)
SWAG_ERROR(Err0549, "module `%s`, cannot resolve %s `%s`")
SWAG_ERROR(Err0550, "[safety] `@strcmp` first pointer is null")
SWAG_ERROR(Err0551, "[safety] `@strcmp` second pointer is null")
SWAG_ERROR(Err0552, "fatal error: some problems have been found in compiler bootstrap !!!")
SWAG_ERROR(Err0553, nullptr)
SWAG_ERROR(Err0554, "fatal error: some problems have been found in compiler runtime !!!")
SWAG_ERROR(Err0555, "unsupported tuple type in generic parameters")
SWAG_ERROR(Err0556, "module `%s` cannot be found in that workspace")
SWAG_ERROR(Err0557, "dependency module `%s` cannot be found in that workspace")
SWAG_ERROR(Err0558, "llvm backend cannot create target `%s`")
SWAG_ERROR(Err0559, "`move` cannot be applied to a constant expression (type is `%s`)")
SWAG_ERROR(Err0560, "`retval` type is invalid for a function return type")
SWAG_ERROR(Err0561, "`]` should not be followed by a line break when declaring an array type")
SWAG_ERROR(Err0562, nullptr)
SWAG_ERROR(Err0563, nullptr)
SWAG_ERROR(Err0564, "affect operation not allowed, left expression is immutable (`const`)")
SWAG_ERROR(Err0565, "affect operation not allowed, left expression is not an l-value")
SWAG_ERROR(Err0566, "affect operation not allowed")
SWAG_ERROR(Err0567, "affect operation not allowed, left expression is not a variable")
SWAG_ERROR(Err0568, nullptr)
SWAG_ERROR(Err0569, "cannot affect an expression of type `void`")
SWAG_ERROR(Err0570, "`%s` operation not allowed on type `any`")
SWAG_ERROR(Err0571, "affect not allowed on %s `%s`")
SWAG_ERROR(Err0572, "affect not allowed, `%s` is %s")
SWAG_ERROR(Err0573, "invalid operation on a tuple type")
SWAG_ERROR(Err0574, "affect to tuple is not possible because right expression is not compatible")
SWAG_ERROR(Err0575, nullptr)
SWAG_ERROR(Err0576, nullptr)
SWAG_ERROR(Err0577, nullptr)
SWAG_ERROR(Err0578, nullptr)
SWAG_ERROR(Err0579, "pointer arithmetic not allowed with operand type `%s`")
SWAG_ERROR(Err0580, nullptr)
SWAG_ERROR(Err0581, nullptr)
SWAG_ERROR(Err0582, "expected an attribute, but `%s` is %s")
SWAG_ERROR(Err0583, "attribute `%s` can only be applied to %s")
SWAG_ERROR(Err0585, nullptr)
SWAG_ERROR(Err0586, "attribute `%s` cannot be used in that context")
SWAG_ERROR(Err0587, nullptr)
SWAG_ERROR(Err0588, "attribute `%s` cannot be applied to %s")
SWAG_ERROR(Err0589, nullptr)
SWAG_ERROR(Err0590, nullptr)
SWAG_ERROR(Err0591, "attribute `%s` assigned twice to `%s` (`Swag.AttrMulti` is not present in the declaration of `%s`)")
SWAG_ERROR(Err0592, nullptr)
SWAG_ERROR(Err0593, "`Swag.Safety` invalid value `%s`")
SWAG_ERROR(Err0594, "`Swag.Optim` invalid value `%s`")
SWAG_ERROR(Err0595, "`Swag.Pack` value should be 0 or a power of two (`%d` provided)")
SWAG_ERROR(Err0596, "`Swag.Align` value should be a power of two (`%d` provided)")
SWAG_ERROR(Err0597, "invalid attribute usage")
SWAG_ERROR(Err0598, "invalid attribute `%s`")
SWAG_ERROR(Err0599, "`Swag.ExportType` invalid value `%s`")
SWAG_ERROR(Err0600, "attribute `%s` does not have the `Swag.AttributeUsage.File` usage, so it cannot be used with `#global`")
SWAG_ERROR(Err0601, "`Swag.Using` is empty")
SWAG_ERROR(Err0602, "attribute parameter cannot be evaluated at compile time")
SWAG_ERROR(Err0603, "cannot delete file `%s`")
SWAG_ERROR(Err0604, "cannot create directory `%s`")
SWAG_ERROR(Err0605, nullptr)
SWAG_ERROR(Err0606, "%s should return a value")
SWAG_ERROR(Err0607, "switch without an expression cannot be marked as `Swag.Complete`")
SWAG_ERROR(Err0608, "invalid switch type `any`, you need to cast to a concrete type")
SWAG_ERROR(Err0609, "invalid switch type `%s`")
SWAG_ERROR(Err0610, "switch body is empty")
SWAG_ERROR(Err0611, "switch value `%s` already defined")
SWAG_ERROR(Err0612, "switch enum value `%s` already defined")
SWAG_ERROR(Err0613, "switch value `%d` already defined")
SWAG_ERROR(Err0614, "switch value `%f` already defined")
SWAG_ERROR(Err0615, "expression cannot be evaluated at compile time, and switch is `Swag.Complete`")
SWAG_ERROR(Err0616, "`default` is invalid in a switch marked with `Swag.Complete`")
SWAG_ERROR(Err0617, "`Swag.Complete` attribute cannot be used on a switch with type `%s`")
SWAG_ERROR(Err0618, nullptr)
SWAG_ERROR(Err0619, nullptr)
SWAG_ERROR(Err0620, "switch is incomplete (missing `%s.%s`)")
SWAG_ERROR(Err0621, nullptr)
SWAG_ERROR(Err0622, "expected a constant name, found `%s`")
SWAG_ERROR(Err0623, "missing variable type or assignment (`:` or `=`)")
SWAG_ERROR(Err0624, "cannot visit a tuple type")
SWAG_ERROR(Err0625, "special visit name is only valid for struct (type is `%s`)")
SWAG_ERROR(Err0626, "too many `visit` alias names (maximum is `2`, but `%u` are provided)")
SWAG_ERROR(Err0627, "cannot visit a variadic type by pointer")
SWAG_ERROR(Err0628, "a pointer type (`%s`) cannot be visited with `visit`")
SWAG_ERROR(Err0629, "expression of type `%s` cannot be visited with `visit`")
SWAG_ERROR(Err0630, "`@index` can only be used inside a breakable loop (`visit`, `loop` ...)")
SWAG_ERROR(Err0631, "unknown label `%s`")
SWAG_ERROR(Err0632, "`break` can only be used inside a breakable block")
SWAG_ERROR(Err0633, "`fallthrough` can only be used inside a `switch` block")
SWAG_ERROR(Err0634, "`fallthrough` can only be used inside a `case` block")
SWAG_ERROR(Err0635, "`fallthrough` cannot be used in the last `case` of the switch")
SWAG_ERROR(Err0636, "cannot visit an enum by pointer")
SWAG_ERROR(Err0637, "`continue` can only be used inside a breakable loop (`for`, `visit`, `loop`, `while` ...)")
SWAG_ERROR(Err0638, nullptr)
SWAG_ERROR(Err0639, "label name `%s` already defined in the hierarchy")
SWAG_ERROR(Err0640, nullptr)
SWAG_ERROR(Err0641, nullptr)
SWAG_ERROR(Err0642, nullptr)
SWAG_ERROR(Err0643, nullptr)
SWAG_ERROR(Err0644, nullptr)
SWAG_ERROR(Err0645, "variable initialized twice, first with type arguments, and then with an assignment")
SWAG_ERROR(Err0646, "expected an interface, but `%s` is %s")
SWAG_ERROR(Err0647, nullptr)
SWAG_ERROR(Err0648, "expected a struct, but `%s` is %s")
SWAG_ERROR(Err0649, nullptr)
SWAG_ERROR(Err0650, nullptr)
SWAG_ERROR(Err0651, nullptr)
SWAG_ERROR(Err0652, "function `%s` has an incorrect signature for interface `%s`")
SWAG_ERROR(Err0653, "should be")
SWAG_ERROR(Err0654, "missing first parameter `self` for interface function `%s`")
SWAG_ERROR(Err0655, "bad type for first parameter of interface function implementation (`self` expected, `%s` provided)")
SWAG_ERROR(Err0656, nullptr)
SWAG_ERROR(Err0657, "some functions of interface `%s` are not implemented")
SWAG_ERROR(Err0658, nullptr)
SWAG_ERROR(Err0659, "implementation block for `%s` is private but the corresponding identifier is not")
SWAG_ERROR(Err0660, "implementation block for `%s` is not private but the corresponding identifier is")
SWAG_ERROR(Err0661, "implementation block is not defined in the same scope as `%s` (`impl` parent scope is `%s`, `%s` parent scope is `%s`)")
SWAG_ERROR(Err0662, "expected a struct or an enum, but `%s` is %s")
SWAG_ERROR(Err0663, nullptr)
SWAG_ERROR(Err0664, "unsupported alias as an implementation block name")
SWAG_ERROR(Err0665, nullptr)
SWAG_ERROR(Err0666, "struct cannot be marked with `Swag.Opaque` because it is not public")
SWAG_ERROR(Err0667, "struct cannot be marked with `Swag.Opaque` because the whole file is exported (`#global export`)")
SWAG_ERROR(Err0668, "`using` is invalid on a constant")
SWAG_ERROR(Err0669, "`using` on a field is only valid for a struct type (`%s` provided)")
SWAG_ERROR(Err0670, "initialization expression cannot be evaluated at compile time")
SWAG_ERROR(Err0671, "type `%s` is generic, but struct `%s` does not declare generic parameters")
SWAG_ERROR(Err0672, "cannot resolve struct `%s` because type `%s` is generic")
SWAG_ERROR(Err0673, "cannot find struct member `%s` to compute variable relocation (`Swag.Offset` attribute)")
SWAG_ERROR(Err0674, "struct member name `%s` starts with `item`, and this is reserved by the language")
SWAG_ERROR(Err0675, "embedded struct `%s` cannot be public")
SWAG_ERROR(Err0676, "an interface can only contain members of type `lambda` (`%s` provided)")
SWAG_ERROR(Err0677, "missing parameters for interface member `%s` (`self` expected as first parameter)")
SWAG_ERROR(Err0678, nullptr)
SWAG_ERROR(Err0679, "bad type for first parameter of interface member (`self` expected, `%s` provided)")
SWAG_ERROR(Err0680, "cannot initialize an interface member")
SWAG_ERROR(Err0681, "cannot resolve interface because type `%s` is generic")
SWAG_ERROR(Err0682, "cannot relocate an interface member")
SWAG_ERROR(Err0683, "interface `%s` is empty")
SWAG_ERROR(Err0684, "embedded interface `%s` cannot be public")
SWAG_ERROR(Err0685, nullptr)
SWAG_ERROR(Err0686, nullptr)
SWAG_ERROR(Err0687, nullptr)
SWAG_ERROR(Err0688, nullptr)
SWAG_ERROR(Err0689, "`using` on a variable cannot be used in `%s` scope")
SWAG_ERROR(Err0690, nullptr)
SWAG_ERROR(Err0691, "`using` cannot be used on an enum variable")
SWAG_ERROR(Err0692, "`using` cannot be used on a variable of type `%s`")
SWAG_ERROR(Err0693, nullptr)
SWAG_ERROR(Err0694, "invalid `using` type")
SWAG_ERROR(Err0695, "`using` cannot be used on type `%s` (expected a namespace, a struct, an enum or a variable)")
SWAG_ERROR(Err0696, nullptr)
SWAG_ERROR(Err0697, "invalid type `%s` for enum flags (should be unsigned integer)")
SWAG_ERROR(Err0698, "invalid type `%s` for enum index (should be integer)")
SWAG_ERROR(Err0699, "dimension of enum array type `%s` should be specified")
SWAG_ERROR(Err0700, "enum array type `%s` should be `const`")
SWAG_ERROR(Err0701, "enum slice type `%s` should be `const`")
SWAG_ERROR(Err0702, "expected an enum type, found `%s`")
SWAG_ERROR(Err0703, "`with` cannot be used on type `%s` (expected a namespace, an enum or a variable)")
SWAG_ERROR(Err0704, nullptr)
SWAG_ERROR(Err0705, nullptr)
SWAG_ERROR(Err0706, "enum value `%s` of type `%s` should be initialized")
SWAG_ERROR(Err0707, nullptr)
SWAG_ERROR(Err0708, "enum value `%s` is out of range of `u8`")
SWAG_ERROR(Err0709, "cannot deduce flag value of `%s` because previous value is not power of two")
SWAG_ERROR(Err0710, "enum value `%s` is out of range of `u16`")
SWAG_ERROR(Err0711, nullptr)
SWAG_ERROR(Err0712, "enum value `%s` is out of range of `u32`")
SWAG_ERROR(Err0713, nullptr)
SWAG_ERROR(Err0714, "enum value `%s` is out of range of `u64`")
SWAG_ERROR(Err0715, nullptr)
SWAG_ERROR(Err0716, "enum value `%s` is out of range of `s8`")
SWAG_ERROR(Err0717, "enum value `%s` is out of range of `s16`")
SWAG_ERROR(Err0718, "enum value `%s` is out of range of `s32`")
SWAG_ERROR(Err0719, "enum value `%s` is out of range of `s64`")
SWAG_ERROR(Err0720, "command line error: invalid argument `%s`")
SWAG_ERROR(Err0721, nullptr)
SWAG_ERROR(Err0722, "command line error: argument `%s` should be followed by `%s`")
SWAG_ERROR(Err0723, nullptr)
SWAG_ERROR(Err0724, "command line error: argument `%s` should be followed by `true` or `false` (`%s`)")
SWAG_ERROR(Err0725, "command line error: argument `%s` should be followed by a string")
SWAG_ERROR(Err0726, "attribute declaration (`attr`), unlike function, should not have a return value starting with `->`")
SWAG_ERROR(Err0727, "command line error: argument `%s` should be followed by an integer value")
SWAG_ERROR(Err0728, "command line error: argument `%s` should be followed by an integer value (`%s`)")
SWAG_ERROR(Err0729, "type `code` is only valid in a `Swag.Macro` or `Swag.Mixin` function")
SWAG_ERROR(Err0730, "type `alias` is only valid in a `Swag.Macro` or `Swag.Mixin` function")
SWAG_ERROR(Err0731, "invalid type `%s` for attribute parameter")
SWAG_ERROR(Err0732, nullptr)
SWAG_ERROR(Err0733, "inline function has variadic arguments, this is not yet supported")
SWAG_ERROR(Err0734, "variadic argument should be the last one")
SWAG_ERROR(Err0735, "type `cvarargs` can only be used for a function parameter")
SWAG_ERROR(Err0736, "type `code` can only be used for a function parameter")
SWAG_ERROR(Err0737, "compiler instruction `%s` is invalid as a default parameter value")
SWAG_ERROR(Err0738, "parameter `%d` should have a default value because some parameters before have a default value")
SWAG_ERROR(Err0739, "`#main` function already defined once")
SWAG_ERROR(Err0740, nullptr)
SWAG_ERROR(Err0741, "`@alias` names are not all contiguous in function `%s` (missing `@alias%u`)")
SWAG_ERROR(Err0742, "function with the `Swag.Foreign` attribute cannot have a body")
SWAG_ERROR(Err0743, "compiler special function cannot have the `Swag.Inline` attribute")
SWAG_ERROR(Err0744, "`#test` functions can only be used in a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0745, "function with the `Swag.Test` attribute cannot have a return value")
SWAG_ERROR(Err0746, "function with the `Swag.Test` attribute cannot have parameters")
SWAG_ERROR(Err0747, "%s cannot be public")
SWAG_ERROR(Err0748, "not all control paths of %s return a value")
SWAG_ERROR(Err0749, "%s has a return type `%s`, but the body is missing a `return`")
SWAG_ERROR(Err0750, "`#message` function should have a parameter of type `Swag.CompilerMsgMask`")
SWAG_ERROR(Err0751, "function `%s` has the `Swag.NoGeneric` attribute but seems to be generic")
SWAG_ERROR(Err0752, "function `%s` cannot have generic parameters because it is flagged with the `Swag.NoGeneric` attribute")
SWAG_ERROR(Err0753, "function `%s` cannot have the `Swag.Complete` attribute, this is reserved for `opAffect`")
SWAG_ERROR(Err0754, "function `%s` cannot have the `Swag.Implicit` attribute, this is reserved for `opAffect` and `opCast`")
SWAG_ERROR(Err0755, "%s cannot have the `Swag.NoReturn` attribute without `Swag.Macro` or `Swag.Mixin`")
SWAG_ERROR(Err0756, "%s cannot have the `Swag.Implicit` attribute because it`s generic")
SWAG_ERROR(Err0757, "%s is marked with `Swag.Macro` and `Swag.Inline` attributes at the same time")
SWAG_ERROR(Err0758, "%s is marked with `Swag.Macro` and `Swag.Mixin` attributes at the same time")
SWAG_ERROR(Err0759, "%s is marked with `Swag.Mixin` and `Swag.Inline` attributes at the same time")
SWAG_ERROR(Err0760, "%s is marked with `Swag.Mixin` and `Swag.Macro` attributes at the same time")
SWAG_ERROR(Err0761, "a %s cannot be marked with `Swag.Macro` attribute")
SWAG_ERROR(Err0762, "a %s cannot be marked with `Swag.Mixin` attribute")
SWAG_ERROR(Err0763, "a %s cannot be marked with `Swag.Inline` attribute")
SWAG_ERROR(Err0764, "function cannot return a value of type `%s`")
SWAG_ERROR(Err0765, "struct `%s` has the `Swag.NoCopy` attribute, so `opPostCopy` is irrelevant")
SWAG_ERROR(Err0766, "function cannot have a return type because it is flagged with the `Swag.NoReturn` attribute")
SWAG_ERROR(Err0767, "function cannot have the `Swag.Discardable` attribute because it returns `void`")
SWAG_ERROR(Err0768, "unreachable code")
SWAG_ERROR(Err0769, "`retval` type can only be used in a function body")
SWAG_ERROR(Err0770, nullptr)
SWAG_ERROR(Err0771, "`retval` type cannot be used in a function that returns nothing")
SWAG_ERROR(Err0772, "expected return expression of type `%s` after `return`")
SWAG_ERROR(Err0773, nullptr)
SWAG_ERROR(Err0774, "returning a value of type `%s`, but %s returns nothing")
SWAG_ERROR(Err0775, "cannot expand `%s` because this is recursive")
SWAG_ERROR(Err0776, "invalid name alias")
SWAG_ERROR(Err0777, "invalid name alias (should be an identifier)")
SWAG_ERROR(Err0778, "invalid name alias (should be a single identifier)")
SWAG_ERROR(Err0779, nullptr)
SWAG_ERROR(Err0780, "alias name `%s` is unused and should be removed")
SWAG_ERROR(Err0781, "cannot expand `%s` in global scope because it contains sub declarations, this is not (yet?) supported")
SWAG_ERROR(Err0782, "`@mkforeign` should have a lambda type as a first parameter")
SWAG_ERROR(Err0783, "`@mkforeign` should have a `const *void` as a second parameter")
SWAG_ERROR(Err0784, "`@mkcallback` should have a lambda value as a first parameter")
SWAG_ERROR(Err0785, "callback type not supported, too many parameters (maximum is `%d`)")
SWAG_ERROR(Err0786, "callback return type `%s` not supported")
SWAG_ERROR(Err0787, "`%s` should have a pointer as a first parameter")
SWAG_ERROR(Err0788, "`%s` cannot have `null` as first parameter")
SWAG_ERROR(Err0789, "`@mkany` should have a pointer as a first parameter")
SWAG_ERROR(Err0790, "`@mkany` cannot have `null` as first parameter")
SWAG_ERROR(Err0791, "`pointer to value and type are not related (first parameter is a pointer to type `%s` but second parameter is type `%s`)")
SWAG_ERROR(Err0792, "`@mkany` should have a `typeinfo` or a type value as a second parameter (`%s` provided)")
SWAG_ERROR(Err0793, "`@mkinterface` should have a one dimension pointer or a struct as a first parameter")
SWAG_ERROR(Err0794, "`@mkinterface` should have a typeinfo as a second parameter")
SWAG_ERROR(Err0795, "`@mkinterface` should have an interface as a third parameter")
SWAG_ERROR(Err0796, "`@dataof` cannot be used on a tuple type")
SWAG_ERROR(Err0797, "`@dataof` cannot be applied to expression of type `%s`")
SWAG_ERROR(Err0798, "expression cannot be evaluated at compile time")
SWAG_ERROR(Err0799, "unsupported `@stringof` expression")
SWAG_ERROR(Err0800, "`@countof` cannot be used on a tuple type")
SWAG_ERROR(Err0801, "`@countof` cannot be used on type `%s`")
SWAG_ERROR(Err0802, "constant value should be unsigned, but is `%d`")
SWAG_ERROR(Err0803, "unsupported `@nameof` expression")
SWAG_ERROR(Err0804, nullptr)
SWAG_ERROR(Err0805, "constant value should be unsigned, but is `%I64d`")
SWAG_ERROR(Err0806, "`@spread` can only be called as a function parameter")
SWAG_ERROR(Err0807, "expression of type `%s` cannot be spreaded")
SWAG_ERROR(Err0808, nullptr)
SWAG_ERROR(Err0809, nullptr)
SWAG_ERROR(Err0810, "cannot evaluate type in that context because it`s generic")
SWAG_ERROR(Err0811, nullptr)
SWAG_ERROR(Err0812, "size cannot be computed because expression is generic")
SWAG_ERROR(Err0813, nullptr)
SWAG_ERROR(Err0814, "alignement cannot be computed because expression is generic")
SWAG_ERROR(Err0815, nullptr)
SWAG_ERROR(Err0816, nullptr)
SWAG_ERROR(Err0817, "fatal error: workspace folder `%s` already exists")
SWAG_ERROR(Err0818, "fatal error: cannot create directory `%s`")
SWAG_ERROR(Err0819, "cannot alias a pointer or an array reference")
SWAG_ERROR(Err0820, "enum `%s` already defined")
SWAG_ERROR(Err0821, "cannot unpack variable `%s` from struct `%s` because there`s no corresponding member")
SWAG_ERROR(Err0822, "`using` on a variable with a type pointer can only be used on a pointer to a struct (type is `%s`)")
SWAG_ERROR(Err0823, "`case` statement is empty, you should add a `break`")
SWAG_ERROR(Err0824, "fatal error: cannot create file `%s`")
SWAG_ERROR(Err0825, "expected `,` or `]`, found `%s`")
SWAG_ERROR(Err0826, "invalid access to an array with multiple dimensions, syntax is [x, y], not [x][y]")
SWAG_ERROR(Err0827, "negate an unsigned type (`%s`) is not allowed")
SWAG_ERROR(Err0828, "minus operation not allowed on type `%s`")
SWAG_ERROR(Err0829, "cannot negate number `%d` because `%u` is not in the range of `s8`")
SWAG_ERROR(Err0830, "cannot negate number `%d` because `%u` is not in the range of `s16`")
SWAG_ERROR(Err0831, "cannot negate number `%d` because `%u` is not in the range of `s32`")
SWAG_ERROR(Err0832, "cannot negate number `%I64d` because `%I64u` is not in the range of `s64`")
SWAG_ERROR(Err0833, "bit inversion operation not allowed on type `%s`")
SWAG_ERROR(Err0834, "%s size overflow")
SWAG_ERROR(Err0835, "expected an identifier, found symbol `%s`")
SWAG_ERROR(Err0836, nullptr)
SWAG_ERROR(Err0837, nullptr)
SWAG_ERROR(Err0838, "type `Self` cannot be used outside an `impl`, `struct` or `interface` block")
SWAG_ERROR(Err0839, "struct initialization of `%s` should be done with `{}` and not parenthesis (this is reserved for function calls)")
SWAG_ERROR(Err0840, "array size should be defined before the type name")
SWAG_ERROR(Err0841, "invalid token `%s` after `discard`")
SWAG_ERROR(Err0842, "`%s` can only be used inside a function")
SWAG_ERROR(Err0843, "invalid `try` inside `%s` expression")
SWAG_ERROR(Err0844, "invalid `catch` inside `%s` expression")
SWAG_ERROR(Err0845, "invalid `assume` inside `%s` expression")
SWAG_ERROR(Err0846, "invalid `throw` inside `%s` expression")
SWAG_ERROR(Err0847, "`discard try/assume` cannot be followed by a block")
SWAG_ERROR(Err0848, "`catch` can only be used inside a function")
SWAG_ERROR(Err0849, nullptr)
SWAG_ERROR(Err0850, nullptr)
SWAG_ERROR(Err0851, nullptr)
SWAG_ERROR(Err0852, nullptr)
SWAG_ERROR(Err0853, "`%s` should be immediatly followed by an identifier")
SWAG_ERROR(Err0854, "`throw` can only be used inside a function")
SWAG_ERROR(Err0855, nullptr)
SWAG_ERROR(Err0856, nullptr)
SWAG_ERROR(Err0857, nullptr)
SWAG_ERROR(Err0858, "`%s` should not be followed by a line break %s")
SWAG_ERROR(Err0859, "[safety] dereferencing a null pointer")
SWAG_ERROR(Err0860, "a %s cannot be marked with `Swag.NotGeneric` attribute")
SWAG_ERROR(Err0861, "intrinsic parameter expression cannot be empty")
SWAG_ERROR(Err0862, "expression is empty")
SWAG_ERROR(Err0863, "missing `if` boolean expression before `{`")
SWAG_ERROR(Err0864, "missing `while` boolean expression before `{`")
SWAG_ERROR(Err0865, "`case` or `default` expected")
SWAG_ERROR(Err0866, "`default` already defined")
SWAG_ERROR(Err0867, "missing `case` expression before `:`")
SWAG_ERROR(Err0868, "missing `case` expression before `break`")
SWAG_ERROR(Err0869, "`case` statement is empty, you should add a `break` or a `fallthrough`")
SWAG_ERROR(Err0870, "opVisit special name expected")
SWAG_ERROR(Err0871, "missing the `visit` expression to evaluate before `{`")
SWAG_ERROR(Err0872, "missing another `visit` variable name after `,` and before `:`")
SWAG_ERROR(Err0873, nullptr)
SWAG_ERROR(Err0874, "missing the `loop` expression to evaluate before `{`")
SWAG_ERROR(Err0875, nullptr)
SWAG_ERROR(Err0876, "invalid label name, you should add `;` or put a valid label identifier")
SWAG_ERROR(Err0877, "invalid label name, identifier expected")
SWAG_ERROR(Err0878, "missing `#if` expression")
SWAG_ERROR(Err0879, "missing `#global if` expression")
SWAG_ERROR(Err0880, "no corresponding `}` has been found")
SWAG_ERROR(Err0881, "identifier is preceeded with `.`, but no parent scope can be found")
SWAG_ERROR(Err0882, nullptr)
SWAG_ERROR(Err0883, "missing function parameters before `{`")
SWAG_ERROR(Err0884, nullptr)
SWAG_ERROR(Err0885, "symbol `%s` already defined as %s in an accessible scope")
SWAG_ERROR(Err0886, "symbol `%s` already defined in an accessible scope")
SWAG_ERROR(Err0887, nullptr)
SWAG_ERROR(Err0888, nullptr)
SWAG_ERROR(Err0889, nullptr)
SWAG_ERROR(Err0890, "symbol `%s` already defined as a name alias in an accessible scope")
SWAG_ERROR(Err0891, "invalid `%s`, use `%s` instead to do a logical test")
SWAG_ERROR(Err0892, "placeholder identifier `%s` has not been solved")
SWAG_ERROR(Err0893, "identifier `%s` has not been solved")
SWAG_ERROR(Err0894, "variable `%s` is used before being declared")
SWAG_ERROR(Err0895, "expected a top level instruction")
SWAG_ERROR(Err0896, "expected an embedded instruction or a curly block")
SWAG_ERROR(Err0897, "expected a left expression")
SWAG_ERROR(Err0898, "expected a variable declaration")
SWAG_ERROR(Err0899, "expected an expression")
SWAG_ERROR(Err0905, "unexpected end of line found in string literal")
SWAG_ERROR(Err0906, "initialization value cannot be evaluated at compile time because `opAffect` is not `Swag.ConstExpr`")
SWAG_ERROR(Err0907, "cannot cast from type `%s` to pointer type; only type `uint` is accepted")
SWAG_ERROR(Err0908, "`%s = %s` is impossible because no corresponding `opAffect` function cannot be found in `%s`")
SWAG_ERROR(Err0909, "type `%s` cannot be used in an union because it contains `opPostCopy` (or one of its members does)")
SWAG_ERROR(Err0910, "type `%s` cannot be used in an union because it contains `opPostMove` (or one of its members does)")
SWAG_ERROR(Err0911, "type `%s` cannot be used in an union because it contains `opDrop` (or one of its members does)")
SWAG_ERROR(Err0912, "expected `:` after variable name `%s`, found a literal")

SWAG_ERROR(Hnt0000, "this divisor expression is zero")
SWAG_ERROR(Hnt0001, "this `@sqrt` is called with a negative value")
SWAG_ERROR(Hnt0002, "this value can only be converted to type `%s` with a dynamic call to `opAffect`")
SWAG_ERROR(Hnt0003, "this is a static reference to a struct member of `%s`")
SWAG_ERROR(Hnt0004, "this should be `const %s`")
SWAG_ERROR(Hnt0005, "this could be casted to `uint`")
SWAG_ERROR(Hnt0006, "this cannot be visited")
SWAG_ERROR(Hnt0007, "this implies another `visit` variable name")
SWAG_ERROR(Hnt0008, nullptr)
SWAG_ERROR(Hnt0009, "this should be a `visit` variable name or the expression to evaluate")
SWAG_ERROR(Hnt0010, "this should be a `visit` variable name")
SWAG_ERROR(Hnt0011, "this type is `%s`")
SWAG_ERROR(Hnt0012, "this return (%s) should have type `%s`")
SWAG_ERROR(Hnt0013, "this should be on another line, or separated with `;`")
SWAG_ERROR(Hnt0014, "this is invalid in global scope")
SWAG_ERROR(Hnt0015, "this function is marked with the `Swag.Macro` attribute")
SWAG_ERROR(Hnt0016, "this function is marked with the `Swag.Mixin` attribute")
SWAG_ERROR(Hnt0017, "this function is marked with the `Swag.Inline` attribute")
SWAG_ERROR(Hnt0018, "this is a constant")
SWAG_ERROR(Hnt0019, "this should be `impl enum %s`")
SWAG_ERROR(Hnt0020, "this should be `impl %s`")
SWAG_ERROR(Hnt0021, "this should be a pointer")
SWAG_ERROR(Hnt0022, "this type is immutable (`const`)")
SWAG_ERROR(Hnt0023, "this call could be preceeded by `discard` if you do not want to use the return value")
SWAG_ERROR(Hnt0024, "this is a pointer type declaration because of `*`")
SWAG_ERROR(Hnt0025, "this could be casted with `cast(%s)`")
SWAG_ERROR(Hnt0026, "this should be removed")
SWAG_ERROR(Hnt0027, "this should be the `loop` expression to evaluate")
SWAG_ERROR(Hnt0028, "this should be the `loop` variable name or the expression to evaluate")
SWAG_ERROR(Hnt0029, "this should be the `visit` expression to evaluate")
SWAG_ERROR(Hnt0030, "this should be the expression to dereference")
SWAG_ERROR(Hnt0031, "this should be the range right expression")
SWAG_ERROR(Hnt0032, "this type is `%s` (could be casted with `cast(%s)`)")
SWAG_ERROR(Hnt0033, "this evaluates to 0")
SWAG_ERROR(Hnt0034, "this returns nothing")
SWAG_ERROR(Hnt0035, "this is an alias and should be an identifier")
SWAG_ERROR(Hnt0036, "this is a pointer and cannot be visited")
SWAG_ERROR(Hnt0037, "this pointer could be dereferenced with `dref`")

SWAG_ERROR(Nte0000, "here is its declaration")
SWAG_ERROR(Nte0001, "`%s` is %s of type `%s` which does not contain a subscope")
SWAG_ERROR(Nte0002, "occurred %s %s`%s`")
SWAG_ERROR(Nte0003, "occurred %s")
SWAG_ERROR(Nte0004, "occurred in generated code")
SWAG_ERROR(Nte0005, "is there a missing `self` ?")
SWAG_ERROR(Nte0006, "this `using` field can be converted")
SWAG_ERROR(Nte0007, "here is the `%s`")
SWAG_ERROR(Nte0008, "here is %s")
SWAG_ERROR(Nte0009, "you can run swag with --dbgcatch to attach the bytecode debugger when the error occurs")
SWAG_ERROR(Nte0010, "`%s` is %s")
SWAG_ERROR(Nte0011, "%s is marked with `Swag.NoReturn`, so the return is used inside %s")
SWAG_ERROR(Nte0012, "note: use `-w:<path>` or `--workspace:<path>` to specifiy a valid workspace folder, or execute swag from a valid workspace folder")
SWAG_ERROR(Nte0013, "symbol has been found thanks to a `using`")
SWAG_ERROR(Nte0014, "if you want to dereference variable `%s` like in C, use `dref %s`")
SWAG_ERROR(Nte0015, "here is one")
SWAG_ERROR(Nte0016, "here is another")
SWAG_ERROR(Nte0017, "when solving")
SWAG_ERROR(Nte0018, "when solving affectation")
SWAG_ERROR(Nte0019, "it is applied on this %s")
SWAG_ERROR(Nte0020, "if you want to declare a lambda, you should use `func(`")
SWAG_ERROR(Nte0021, "to close the left expression")
SWAG_ERROR(Nte0022, "to start the namespace body")
SWAG_ERROR(Nte0023, "to close the namespace body")
SWAG_ERROR(Nte0024, "here is a previous declaration")
SWAG_ERROR(Nte0025, "here is attribute `%s`")
SWAG_ERROR(Nte0026, "here is the %s")
SWAG_ERROR(Nte0027, "here is the declaration of `%s`")
SWAG_ERROR(Nte0028, "here is the declaration")
SWAG_ERROR(Nte0029, "here is the definition of `%s`")
SWAG_ERROR(Nte0030, "here is the definition of the tuple")
SWAG_ERROR(Nte0031, "here is the deprecated definition")
SWAG_ERROR(Nte0032, "here is the faulty attribute")
SWAG_ERROR(Nte0033, "here is the function")
SWAG_ERROR(Nte0034, "here is the missing value")
SWAG_ERROR(Nte0035, "here is the other `#import`")
SWAG_ERROR(Nte0036, "here is the other definition")
SWAG_ERROR(Nte0037, "here is the previous definition")
SWAG_ERROR(Nte0038, "here is the related command line option: `%s`")
SWAG_ERROR(Nte0039, "here is the variable declaration")
SWAG_ERROR(Nte0040, "here is `%s`")
SWAG_ERROR(Nte0041, "`%s` is a variable and variables inside expressions cannot be evaluated at compile time")
SWAG_ERROR(Nte0042, "`%s` is a function without the `Swag.ConstExpr` attribute (you could also use `#run` before the call)")
SWAG_ERROR(Nte0043, "symbol `%s` was not found in `%s`")
SWAG_ERROR(Nte0044, "symbol `%s` exists in interface scope `%s`")
SWAG_ERROR(Nte0045, "%s `%s` to be solved")
SWAG_ERROR(Nte0046, "%s `%s` is waiting for ")
SWAG_ERROR(Nte0047, ", found `%s` ")
SWAG_ERROR(Nte0048, ", found identifier `%s` ")
SWAG_ERROR(Nte0049, ", found symbol `%s` ")
SWAG_ERROR(Nte0050, ", found type `%s` ")
SWAG_ERROR(Nte0051, ") did you miss `var` or `const` to declare a global variable ?")
SWAG_ERROR(Nte0052, "as a `loop` variable name")
SWAG_ERROR(Nte0053, " (did you mean `%s` ?)")
SWAG_ERROR(Nte0054, " (did you mean `%s` or `%s` ?)")
SWAG_ERROR(Nte0055, " (did you mean `%s`, `%s` or `%s` ?)")
SWAG_ERROR(Nte0056, "the other one is an implicit 'using self' as a first parameter")
