#define Msg0000 "fatal error: invalid swag command '%s'"
#define Msg0001 "compare operation not allowed on type '%s'"
#define Msg0002 "type '%s' cannot be used in a range expression"
#define Msg0004 "cannot select function '%s' because '%s' has failed"
#define Msg0005 "operation '%s' not allowed on %s '%s'"
#define Msg0006 "parameter '%d' should be named"
#define Msg0007 "comparison operations are invalid on tuple types"
#define Msg0008 "unknown named parameter '%s'"
#define Msg0009 "slice can only be compared to 'null'"
#define Msg0010 "an interface can only be compared to 'null'"
#define Msg0011 "named parameter '%s' already used"
#define Msg0012 "cannot reference a type expression"
#define Msg0013 "%s '%s' cannot be referenced in that context because it's not an rvalue"
#define Msg0014 "fatal error: not enough memory !"
#define Msg0015 "bytecode stack overflow (maximum stack size is '--stack-size:%s')"
#define Msg0016 "not enough parameters for %s"
#define Msg0017 "invalid type declaration, symbol '%s' is not a type (it's %s)"
#define Msg0018 "here is the definition of '%s'"
#define Msg0020 "missing function call '()' to %s"
#define Msg0021 "array dimension cannot be evaluated at compile time"
#define Msg0022 "array dimension should be integer, but is '%s'"
#define Msg0023 "array dimension is 0"
#define Msg0024 "pointer to 'Swag.TypeInfo' should be 'const'"
#define Msg0025 "alias is public but '%s' is not"
#define Msg0026 "too many parameters for %s"
#define Msg0027 "alias can only be used with a type or an identifier"
#define Msg0028 "'Swag.Strict' attribute can only be used on a type alias"
#define Msg0029 "cannot alias multiple variables"
#define Msg0030 "alias cannot be used on %s"
#define Msg0031 "invalid bitcast type '%s' (should be native integer, char or float)"
#define Msg0032 "cannot bitcast from type '%s' (should be native integer, char or float)"
#define Msg0033 "cannot bitcast to a type with a bigger size ('%s' from '%s')"
#define Msg0034 "llvm backend unsupported os '%s'"
#define Msg0035 "not enough generic parameters for %s"
#define Msg0036 "error: backend: cannot locate windows sdk folder"
#define Msg0037 "cannot instantiate generic %s '%s' with an untyped integer, you need to specify a type\n"
#define Msg0038 "cannot instantiate generic %s '%s' with an untyped float, you need to specify a type\n"
#define Msg0039 "cannot instantiate generic struct '%s', missing contextual types replacements"
#define Msg0040 "partial type alias for generic struct instantiation is not supported"
#define Msg0041 "cannot instantiate generic function '%s', missing generic parameters"
#define Msg0042 "cannot instantiate generic function '%s', missing contextual types replacements"
#define Msg0043 "cannot instantiate variable because type '%s' is generic"
#define Msg0044 "too many generic parameters for %s '%s'"
#define Msg0045 "cannot create '%s' process (::CreatePipe)"
#define Msg0046 "cannot create process '%s'"
#define Msg0047 "bad type of parameter '%d' for %s, generic type '%s' is assigned to '%s' ('%s' provided)"
#define Msg0048 "cannot set environment variable 'SWAG_FOLDER' to '%s'\n"
#define Msg0049 "cannot access environment variable 'PATH'\n"
#define Msg0050 "bad type of parameter '%d' for %s ('%s' is expected for field '%s', '%s' provided)"
#define Msg0051 "cannot add '%s' to the 'PATH' environment variable\n"
#define Msg0052 "failed to start watcher service !"
#define Msg0053 "bad type of parameter '%d' for %s ('%s' expected, '%s' provided)"
#define Msg0054 "bad generic parameter '%d' for %s (type expected, value provided)"
#define Msg0055 "failed to update watcher service !"
#define Msg0056 "x64 backend unsupported os '%s'"
#define Msg0057 "bad generic parameter '%d' for %s (value expected, type provided)"
#define Msg0058 "[compiler internal] %s"
#define Msg0059 "[compiler internal] function '%s' does not release all registers; this is fine, but should be reported !"
#define Msg0060 "[compiler internal] function '%s' releases too many registers !"
#define Msg0061 "invalid number of arguments for special function '%s' ('%d' expected, '%d' provided)"
#define Msg0062 "too few arguments for special function '%s' (at least '%d' expected, only '%d' provided)"
#define Msg0063 "missing return type for special function '%s'"
#define Msg0064 "missing return type for special function '%s' ('%s' expected)"
#define Msg0065 "invalid return type for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0066 "invalid parameter '%d' for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0067 "special function '%s' should be defined in a 'impl' scope"
#define Msg0068 "missing parameters for special function '%s'"
#define Msg0069 "invalid first parameter type for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0070 "bad type of generic parameter '%d' for %s ('%s' expected, '%s' provided)"
#define Msg0071 "invalid number of generic parameters for special function '%s'"
#define Msg0072 "invalid generic parameter for special function '%s' ('string' expected, '%s' provided)"
#define Msg0073 "invalid number of generic parameters for special function '%s'"
#define Msg0074 "invalid generic parameter for special function '%s' ('bool' expected, '%s' provided)"
#define Msg0075 "'opVisit' should have the 'Swag.Macro' attribute"
#define Msg0076 "call level limit reached (maximum level is '--max-recurse:%d')"
#define Msg0077 "invalid parameter '2' for special function '%s' (cannot be of type '%s')"
#define Msg0078 "function '%s' does not match a special function/operator overload"
#define Msg0079 "cannot find special function '%s' in '%s'"
#define Msg0080 "unexpected end of file found in comment"
#define Msg0081 "invalid character '%s'"
#define Msg0082 "struct '%s' should be initialized in place with '{}' and not parenthesis (this is reserved for function calls)"
#define Msg0083 "%s '%s' is deprecated"
#define Msg0084 "here is the deprecated definition"
#define Msg0085 "identifier '%s' cannot be dereferenced like a struct (type is '%s')"
#define Msg0086 "variable '%s' has only been used to find function '%s'; use scope '%s' instead"
#define Msg0087 "only calls to 'Swag.Mixin' functions can be done at global scope ('%s' is %s)"
#define Msg0088 "function '%s' is not declared with the 'Swag.Mixin' attribute, and this is mandatory for a function call at global scope"
#define Msg0089 "'%s' cannot be evaluated at compile time"
#define Msg0090 "cannot evaluate function parameter at compile time (type is '%s')"
#define Msg0091 "cannot reference 'Swag.Compiler' %s '%s' from runtime %s"
#define Msg0092 "unused return value of lambda '%s'"
#define Msg0093 "identifier '%s' cannot be found in tuple"
#define Msg0094 "cannot discard a function call that returns nothing"
#define Msg0095 "here is the variable declaration"
#define Msg0096 "unused variable '%s'"
#define Msg0097 "%s '%s' has not been used as the first parameter to call '%s'"
#define Msg0098 "function '%s' should be called with '()' and not curlies (this is reserved for struct initialization)"
#define Msg0099 "invalid aliased identifiers because function '%s' is not a macro or a mixin"
#define Msg0100 "cannot reference 'opInit' special function (use '@init' instead)"
#define Msg0101 "cannot reference 'opDrop' special function (use '@drop' instead)"
#define Msg0102 "evaluation of a function parameter of type '%s' is not supported at compile time"
#define Msg0103 "cannot reference 'opPostCopy' special function (use '@postcopy' instead)"
#define Msg0104 "cannot reference 'opPostMove' special function (use '@postmove' instead)"
#define Msg0105 "cannot call empty function '%s'"
#define Msg0106 "here is the function"
#define Msg0107 "cannot reference 'Swag.Compiler' function '%s' from runtime function '%s'"
#define Msg0108 "cannot reference 'Swag.Test' function '%s' from '%s'"
#define Msg0109 "unused return value of function '%s'"
#define Msg0110 "identifier '%s' cannot be found in %s '%s'"
#define Msg0111 "cannot discard a function call that returns nothing"
#define Msg0112 "during generic expansion"
#define Msg0113 "none of the %d overloads could match"
#define Msg0114 "cannot take the address of a function with call parameters"
#define Msg0115 "ambiguous resolution of generic %s '%s'"
#define Msg0116 "ambiguous resolution of symbol '%s'"
#define Msg0117 "cannot use 'using' on two variables with the same type"
#define Msg0118 "during inline expansion"
#define Msg0119 "missing function call parameters"
#define Msg0120 "field name '%s' cannot be found in tuple"
#define Msg0121 
#define Msg0122 "unknown identifier '%s'"
#define Msg0123 "invalid lambda call, cannot reference structure member '%s'"
#define Msg0124 "invalid lambda call, '%s' is not a variable"
#define Msg0125 "identifier '%s' has call parameters, but is a variable of type '%s' and not a function"
#define Msg0126 "here is '%s'"
#define Msg0127 "identifier '%s' has call parameters, but is %s and not a function"
#define Msg0128 "during '#selectif' validation of function call"
#define Msg0129 "during '#checkif' validation of function call"
#define Msg0130 "invalid generic parameters, identifier '%s' is %s and not a function or a structure"
#define Msg0131 "when solving affectation"
#define Msg0132 "invalid reference to private scope"
#define Msg0133 "cannot resolve identifier '%s'"
#define Msg0134 "when solving"
#define Msg0135 "backtick can only be used inside an inline/macro block"
#define Msg0136 "back ticked identifier can only be used inside a 'Swag.Macro' function or an '#inline' block"
#define Msg0137 "'%s' cannot be used inside a struct special function"
#define Msg0138 "'%s' can only be used inside a function marked with 'throw', and '%s' is not"
#define Msg0139 "'%s' can only be used before a function call, and '%s' is %s"
#define Msg0140 "unknown compiler instruction '%s'"
#define Msg0141 "expected '[', '{', '(', '\"' or an intrinsic name, found character '%c'"
#define Msg0142 "operator '+' not allowed with operand type '%s'"
#define Msg0143 "operator '+' not allowed on type '%s'"
#define Msg0144 "pointer arithmetic not allowed on 'typeinfo'"
#define Msg0145 "invalid number syntax, a digit separator '_' cannot be followed by another digit separator"
#define Msg0146 "operator '-' not allowed with operand type '%s'"
#define Msg0147 "operator '-' not allowed on type '%s'"
#define Msg0148 "operator '*' not allowed on type '%s'"
#define Msg0149 "operator '/' not allowed on type '%s'"
#define Msg0150 "division by zero"
#define Msg0151 "invalid number syntax, missing at least one digit"
#define Msg0152 "invalid number syntax, a digit separator '_' cannot end a literal number"
#define Msg0153
#define Msg0154 "invalid number syntax, a digit separator '_' cannot start a literal number"
#define Msg0155 "invalid number syntax, a digit separator '_' cannot start a fractional part"
#define Msg0156 "invalid number syntax, a digit separator '_' cannot start an exponent part"
#define Msg0157 "operator '%' not allowed on type '%s'"
#define Msg0158 "here is a previous declaration"
#define Msg0159 "'Swag.Tls' and 'Swag.Compiler' attributes are exclusive"
#define Msg0160 "cannot assign a function pointer to a constant"
#define Msg0161 "cannot transform type '%s' to a constant array because 'opCount' returns '0'"
#define Msg0162 "cannot transform type '%s' to a constant array because 'opSlice' returns an empty slice"
#define Msg0163 "operator '|' not allowed on type '%s'"
#define Msg0164 "operator '&' not allowed on type '%s'"
#define Msg0165 "fatal error: cannot find 'SWAG_FOLDER' in the environment; you must run 'swag env' first at the Swag.exe location to register its path"
#define Msg0166 "fatal error: script file '%s' does not exist"
#define Msg0167 "operator '^' not allowed on type '%s'"
#define Msg0168 "invalid operation '%s' on a tuple type"
#define Msg0169
#define Msg0170 "operator '<<' not allowed on type '%s'"
#define Msg0171
#define Msg0172 "operator '>>' not allowed on type '%s'"
#define Msg0173 "shift operand should be 'u32' and not '%s'"
#define Msg0174 "this type is '%s' (could be casted with 'cast(%s)')"
#define Msg0175 "cannot cast implicitly from '%s' to '%s'"
#define Msg0176 "cannot cast, type '%s' does not implement interface '%s'"
#define Msg0177 "cannot cast from '%s' to '%s'"
#define Msg0178 "value '%I64d' is negative and not in the range of 'u8'"
#define Msg0179 "value '%I64u' is not in the range of 'u8'"
#define Msg0180 "value '%I64d' is negative and not in the range of 'u16'"
#define Msg0181 "value '%I64u' is not in the range of 'u16'"
#define Msg0182 "value '%I64d' is negative and not in the range of 'u32'"
#define Msg0183 "value '%I64u' is not in the range of 'u32'"
#define Msg0184
#define Msg0185 "value '%I64d' is negative and not in the range of 'u64'"
#define Msg0186 "value '%I64d' is not in the range of 's8'"
#define Msg0187 "value '%I64d' is not in the range of 's16'"
#define Msg0188 "value '%I64d' is not in the range of 's32'"
#define Msg0189 "value '%I64d' is not in the range of 's64'"
#define Msg0190
#define Msg0191 "value '%I64d' is truncated in 'f32'"
#define Msg0192 "value '%I64u' is truncated in 'f32'"
#define Msg0193 "value '%lf' is truncated in 'f32'"
#define Msg0194 "value '%I64d' is truncated in 'f64'"
#define Msg0195 "value '%I64u' is truncated in 'f64'"
#define Msg0196 "not enough initializers for '%s' ('%d' expected, '%d' provided)"
#define Msg0197 "too many initializers for '%s' ('%d' expected, '%d' provided)"
#define Msg0198
#define Msg0199 "forbidden 'opDrop' special function for '%s' because struct is marked with 'Swag.ConstExpr'"
#define Msg0200 "cannot cast from '%s' to '%s' because '%s' has multiple fields of type '%s' with 'using'"
#define Msg0201 "here is one"
#define Msg0202 "here is another"
#define Msg0203 "cannot cast, not enough initializers ('%d' expected, '%d' provided)"
#define Msg0204 "cannot cast, too many initializers ('%d' expected, '%d' provided)"
#define Msg0205 "not enough parameters in tuple initialization ('%d' expected, '%d' provided)"
#define Msg0206 "cannot reference variable '%s' because it's in another stack frame"
#define Msg0207 "[safety] truncated bits when casting expression from '%s' to '%s'"
#define Msg0208 "[safety] cast from a negative value of type '%s' to unsigned type '%s'"
#define Msg0209 "[safety] integer overflow during '+' operation on type '%s'"
#define Msg0210 "[safety] integer overflow during '-' operation on type '%s'"
#define Msg0211 "[safety] integer overflow during '*' operation on type '%s'"
#define Msg0212 "[safety] integer overflow during '+=' operation on type '%s'"
#define Msg0213 "[safety] integer overflow during '-=' operation on type '%s'"
#define Msg0214 "[safety] integer overflow during '*=' operation on type '%s'"
#define Msg0215 "[safety] '<<' shift operand value on type '%s' is greater than '%d'"
#define Msg0216 "[safety] '>>' shift operand value on type '%s' is greater than '%d'"
#define Msg0217 "[safety] integer overflow during '<<' operation on type '%s'"
#define Msg0218 "[safety] integer overflow during '>>' operation on type '%s'"
#define Msg0219 "[safety] '@abs' integer overflow on type '%s'"
#define Msg0220 "[safety] integer overflow when taking the negative value of type '%s'"
#define Msg0221 "[safety] division by zero"
#define Msg0222 "[safety] index out of range"
#define Msg0223 "cannot open #load file '%s'"
#define Msg0224 "'%s = %s' is impossible because special function 'opAffect' cannot be found in '%s'"
#define Msg0225 "'%s[index] = %s' is impossible because special function 'opIndexAffect' cannot be found in '%s'"
#define Msg0226 "cannot access by index because special function 'opIndex' cannot be found in type '%s'"
#define Msg0227 "cannot access '%s' by index because special function 'opIndex' cannot be found in type '%s'"
#define Msg0228 "[safety] invalid dynamic cast"
#define Msg0229 "[safety] bad slicing, lower bound is greater than upper bound"
#define Msg0230 "[safety] bad slicing, upper bound is out of range"
#define Msg0231 "copy semantic is forbidden for type '%s' because of 'Swag.NoCopy' attribute"
#define Msg0232 "'#dependencies' can only be used in the module configuration file"
#define Msg0233 "'#selectif' expression is not 'bool' ('%s' provided)"
#define Msg0234 "'#ast' expression is not 'string' ('%s' provided)"
#define Msg0235 "'#import' can only be used inside a '#dependencies' block"
#define Msg0236 "message expression is not a string"
#define Msg0237 "message expression cannot be evaluated at compile time"
#define Msg0238 "compiler assertion failed"
#define Msg0239 "'#macro' can only be used inside a 'Swag.Macro' function"
#define Msg0240 "expression should be of type 'code', but is '%s'"
#define Msg0241 "'#semerror' has not triggered an error"
#define Msg0242 "filename cannot be evaluated at compile time"
#define Msg0243 "'#load' parameter should be of type string ('%s' provided)"
#define Msg0244 "cannot find file '%s'"
#define Msg0245 "'#gettag' name expected, found a type"
#define Msg0246 "an identifier marked with '#scopefct' cannot be used in a scope"
#define Msg0247 "an identifier marked with '#scopefct' can only be used inside a function"
#define Msg0248 "'#hastag' name cannot be evaluated at compile time"
#define Msg0249 "'#hastag' parameter should be a string ('%s' provided)"
#define Msg0250 "'#gettag' name value cannot be evaluated at compile time"
#define Msg0251 "'#gettag' parameter should be a string, but is '%s'"
#define Msg0252 "type '%s' and type '%s' defined in the command line for '%s' are incompatible"
#define Msg0253 "here is the related command line option: '%s'"
#define Msg0254 "'#callerlocation' can only be set in a function parameter declaration"
#define Msg0255 "'#callerfunction' can only be set in a function parameter declaration"
#define Msg0256 "'#function' can only be called inside a function"
#define Msg0257 "failed to load module '%s' while resolving foreign function '%s': %s"
#define Msg0258 "cannot resolve foreign function call to '%s'"
#define Msg0259 "<foreign code>"
#define Msg0260 "invalid token '['"
#define Msg0261 "this is a pointer dereference ':'"
#define Msg0262 "symbol ':' is interpreted as a pointer dereference, but is followed by a symbol ('%s')"
#define Msg0263 "this should be the expression to dereference"
#define Msg0264 "invalid operator modifier '%s'"
#define Msg0265 "operator modifier '%s' already used once"
#define Msg0266 "operator modifier '%s' is invalid for operator '%s'"
#define Msg0267 "invalid compare operator '=', did you mean '==' ?"
#define Msg0268 "'#dependencies' can only be declared at the file level"
#define Msg0269 "missing '#main' function (executable entry point)"
#define Msg0270 "initializer list is empty"
#define Msg0271 "variable name or '?' expected in tuple unpacking"
#define Msg0272 "identifier '%s' starts with '__', and this is reserved by the language"
#define Msg0273 "unexpected generic parameters for variable '%s'"
#define Msg0274 "unexpected call parameters for variable '%s'"
#define Msg0275 "'@alias' variable name should be followed by a number"
#define Msg0276 "invalid '@alias' variable name '%s', '%s' is not a valid number"
#define Msg0277 "an '@alias' number should be in the range [0, 31] ('%u' provided)"
#define Msg0278 "invalid variable name '%s', cannot start with '@'"
#define Msg0279 "cannot decompose a tuple in %s"
#define Msg0280 "cannot evaluate constant expression of type '%s' at compile time"
#define Msg0281 "cannot evaluate constant expression of type '%s' at compile time, because struct is not marked with 'Swag.ConstExpr'"
#define Msg0282 "unpacking '%d' variable(s), but the tuple on the right contains '%d' element(s)"
#define Msg0283 "'#gettag' default value expected, found a type"
#define Msg0284 "'#import' location already defined as '%s'"
#define Msg0285 "expected an identifier, found a literal"
#define Msg0286 "'#import' version already defined as '%s'"
#define Msg0287 "here is the previous definition"
#define Msg0288 "'#import' version invalid format"
#define Msg0289 "version should be of the form 'version.revision.buildnum', with each number >= 0 or the '?' character"
#define Msg0290 "expected a struct, but symbol '%s' is %s"
#define Msg0291 "cannot unpack type '%s' which is not a struct"
#define Msg0292 "cannot unpack '%s' because it does not contain any field"
#define Msg0293 "attempt to unpack '%u' variables, but '%s' contains only '%u' field(s)"
#define Msg0294 "type to tuple conversion is not (yet?) supported for type '%s'"
#define Msg0295 "struct cannot be initialized twice"
#define Msg0296 "invalid variable name '%s' because '@alias' can only be used inside a macro or a mixin function"
#define Msg0297 "attribute 'Swag.Discardable' can only be used on a lambda variable (provided type is '%s')"
#define Msg0298 "constant should be initialized"
#define Msg0299 "non mutable variable should be initialized"
#define Msg0300 "reference should be initialized"
#define Msg0301 "affect not allowed from an array"
#define Msg0302 "[compiler internal] 'impl for' struct mismatch"
#define Msg0303 "missing initialization expression to deduce size of array"
#define Msg0304 "invalid initialization expression for an array"
#define Msg0305 "constant should be explicitly initialized"
#define Msg0306 "'slice' should be declared as immutable with 'const'"
#define Msg0307 "type of expression is 'void'"
#define Msg0308 "cannot deduce type from 'null'"
#define Msg0309 "unable to deduce type of %s '%s'"
#define Msg0310 "an enum variable should be initialized"
#define Msg0311 "cannot create constant because type '%s' is generic"
#define Msg0312 "cannot create variable because type '%s' is generic"
#define Msg0313 "global variable cannot be declared as 'public'"
#define Msg0314 "invalid file format, should be ascii, utf-8 or utf-8-bom"
#define Msg0315 "[compiler internal] Ast::output, unknown compiler function"
#define Msg0316 "identifier '%s' should be public"
#define Msg0317 "[compiler internal] Ast::output, unknown node"
#define Msg0318 "fatal error: missing script file; use '--file:<filename>.swgs' to specify a script to run"
#define Msg0319 "fatal error: invalid script file extension; should be '.swgs' instead of '%s'"
#define Msg0320 "cannot slice '%s' because special function 'opSlice' cannot be found in type '%s'"
#define Msg0321 "cannot evaluate tuple value at compile time because one of its members is not 'Swag.ConstExpr'"
#define Msg0322 "fatal error: invalid value for '--tag:%s' (%s)"
#define Msg0323 "found 'else' without a corresponding 'if'"
#define Msg0324 "found '#else' without a corresponding '#if'"
#define Msg0325 "found '#elif' without a corresponding '#if'"
#define Msg0326 "found ')' without a corresponding opening '('"
#define Msg0327 "found '}' without a corresponding opening '{'"
#define Msg0328 "found ']' without a corresponding opening '['"
#define Msg0329 "missing '%s' %s"
#define Msg0330 "expected '%s' instead of '%s' %s"
#define Msg0331 "line break or ';' is expected before '%s' to close the %s"
#define Msg0332 "cannot use operator 'orelse' on type '%s'"
#define Msg0333 "expected an alias name, found '%s'"
#define Msg0334 "'self' can only be used inside a struct or 'impl' block"
#define Msg0335
#define Msg0336
#define Msg0337 "cannot use a range in a switch with an expression"
#define Msg0338 "too many array dimensions (maximum is '254')"
#define Msg0339 "missing pointer declaration '*' after 'const'"
#define Msg0340 "too many pointer dimensions (maximim is '%u')"
#define Msg0341 "missing pointer '*' or reference '&' marker after 'const'"
#define Msg0342 "pointer to reference is not (yet?) supported"
#define Msg0343 "expected a type declaration, found '%s'"
#define Msg0344 "fatal error: cannot delete file '%s'"
#define Msg0345 "fatal error: cannot delete directory '%s'"
#define Msg0346 "symbol '%s' already defined in parent scope"
#define Msg0347 "fatal error: cannot create script file '%s'"
#define Msg0348 "private definition should appear at file or namespace scope"
#define Msg0349 "a %s definition should appear at file or namespace scope"
#define Msg0350 "'%s' attribute cannot be used in a file marked with '#global export', because the whole file is implicitly public"
#define Msg0351 "cannot declare a %s symbol in a private scope (%s '%s' is private)"
#define Msg0352 "unexpected token '%s' after 'private' attribute"
#define Msg0353 "unexpected token '%s' after 'protected' attribute"
#define Msg0354 "unexpected token '%s' after 'public' attribute"
#define Msg0355 "expected an attribute name, found '%s'"
#define Msg0356 "empty attribute"
#define Msg0357 "this should be a 'visit' variable name or the expression to evaluate"
#define Msg0358 "this implies another 'visit' variable name"
#define Msg0359 "this should be a 'visit' variable name"
#define Msg0360 "this should be the 'visit' expression to evaluate"
#define Msg0361 "this should be the 'loop' variable name or the expression to evaluate"
#define Msg0362 "this should be the 'loop' expression to evaluate"
#define Msg0363 "this should be the range right expression"
#define Msg0364 "'#mixin' replacement block can only be used inside a breakable statement"
#define Msg0365 "'#mixin' invalid replacement '%s'"
#define Msg0366 "'#mixin' empty replacement block"
#define Msg0367 "'#semerror' is invalid outside a test module (in the './tests' folder of the workspace)"
#define Msg0368 "'#semerror' cannot be in a '#if' block"
#define Msg0369 "'#global' should be defined first, at the top of the file"
#define Msg0370 "'#global export' already defined"
#define Msg0371 "'#global foreignlib' should be followed by a string"
#define Msg0372
#define Msg0373 "invalid pass name '%s'"
#define Msg0374 "'#global testerror' is invalid outside a test module (in the './tests' folder of the workspace)"
#define Msg0375 "'#global testwarning' is invalid outside a test module (in the './tests' folder of the workspace)"
#define Msg0376 "'#global' unexpected token '%s'"
#define Msg0377 "'#import' can only be used in the module configuration file"
#define Msg0378 "'#import' can only be declared at the top level scope"
#define Msg0379 "'#import' should be followed by a string"
#define Msg0380 "'#import' location defined twice"
#define Msg0381 "invalid location '%s'"
#define Msg0382 "'#import' version defined twice"
#define Msg0383 "invalid version '%s'"
#define Msg0384 "'#placeholder' can only be declared in a top level scope"
#define Msg0385 "'#placeholder' should be followed by an identifier"
#define Msg0386 "global 'using' should be declared at the top of the file"
#define Msg0387
#define Msg0388 "namespace definition should appear either at file scope or immediately within another namespace definition"
#define Msg0389 "missing namespace name before '{'"
#define Msg0390 "missing namespace name before ';'"
#define Msg0391 "namespace name should be an identifier ('%s' provided)"
#define Msg0392 "'swag' namespace is reserved by the compiler"
#define Msg0393 "namespace cannot have the same name as the module ('%s')"
#define Msg0394 "missing label identifier before '{'"
#define Msg0395 "invalid label identifier '%s'"
#define Msg0396 "expected an enum name, found '%s'"
#define Msg0397 "fatal error: module '%s' already exists in the '/modules' folder"
#define Msg0398 "here is the declaration of '%s'"
#define Msg0399 "'{' is expected instead of '%s'"
#define Msg0400 "enum value identifier expected"
#define Msg0401 "invalid token, identifier expected"
#define Msg0402 "invalid token, ',' expected"
#define Msg0403 "invalid named parameter '%s'"
#define Msg0404
#define Msg0405 "const before a function parameter name can only be followed by 'self'"
#define Msg0406 "'self' can only be used inside an 'impl' block"
#define Msg0407 "a method can only be declared inside a struct 'impl' block"
#define Msg0408 "invalid parameter name '%s'"
#define Msg0409 "missing function parameter type or assignment"
#define Msg0410 "invalid variable name '%s'"
#define Msg0411 "missing generic parameters"
#define Msg0412 "missing generic name or type"
#define Msg0413 "function names starting with '@' are reserved for intrinsics"
#define Msg0414 "missing function name instead of '%s'"
#define Msg0415
#define Msg0416 "special function '%s' should have a body"
#define Msg0417 "'@power' called with invalid values '%.3f' and '%.3f'"
#define Msg0418 "cannot cast from immutable type '%s' to mutable '%s'"
#define Msg0419
#define Msg0420
#define Msg0421
#define Msg0422
#define Msg0423 "'@log2' called with invalid value '%.3f'"
#define Msg0424 "'@log10' called with invalid value '%.3f'"
#define Msg0425 "'@sqrt' called with invalid value '%.3f'"
#define Msg0426 "'@asin' called with invalid value '%.3f'"
#define Msg0427 "'@acos' called with invalid value '%.3f'"
#define Msg0428 "'@log' called with invalid value '%.3f'"
#define Msg0429
#define Msg0430
#define Msg0431 "runtime variable '%s' is initialized to zero and cannot be changed at compile time; initialize it with '?' if this is intended"
#define Msg0432 "[compiler internal] unknown bytecode instruction '%s'"
#define Msg0433
#define Msg0434 "bytecode execution, "
#define Msg0435 "exception during compile time execution !"
#define Msg0436 "it could be a bug in the compile time part of your program"
#define Msg0437
#define Msg0438 "'for' is invalid for an enum implementation block"
#define Msg0439
#define Msg0440 "invalid generic parameters, should be naked"
#define Msg0441 "implementation block kind (%s) does not match the type of '%s' (%s)"
#define Msg0442
#define Msg0443
#define Msg0444 "expected a struct name, found '%s'"
#define Msg0445
#define Msg0446
#define Msg0447 "empty tuple definition"
#define Msg0448 "identifier expected"
#define Msg0449 "invalid token '%s' in tuple type, ',' or '}' are expected here"
#define Msg0450
#define Msg0451 "'using' on a member is invalid in an interface definition"
#define Msg0452
#define Msg0453 "'var' is not necessary to declare a field"
#define Msg0454 "invalid affect operator '==', did you mean '=' ?"
#define Msg0455 "invalid token '%s' in variable declaration, ':' or '=' are expected here"
#define Msg0456
#define Msg0457 "variable should have a type or should be initialized"
#define Msg0458
#define Msg0459 "too many digits in literal number"
#define Msg0460 "expected a binary digit, found '%s'"
#define Msg0461
#define Msg0462
#define Msg0463 "invalid hexadecimal digit '%s'"
#define Msg0464 "literal number is too big (cannot fit in 64 bits)"
#define Msg0465 "cannot take address of %s"
#define Msg0466 "floating point number exponent should have at least one digit"
#define Msg0467 "invalid literal number prefix '%s'"
#define Msg0468 "index out of range (index is '%I64u', maximum index is '%I64u')"
#define Msg0469 "cannot take address of constant"
#define Msg0470 "invalid address expression"
#define Msg0471 "cannot take address of a macro"
#define Msg0472 "cannot take address of a mixin"
#define Msg0473 "cannot take address of an inline function"
#define Msg0474 "slicing operator cannot be applied on an array with multiple dimensions"
#define Msg0475 "slicing operator cannot be applied on type '%s'"
#define Msg0476 "bad slicing, lower bound '%I64u' is greater than upper bound '%I64u'"
#define Msg0477 "bad slicing, upper bound '%I64u' is out of range"
#define Msg0478 "type '%s' is immutable and cannot be changed"
#define Msg0479
#define Msg0480
#define Msg0481 "cannot dereference type '%s'"
#define Msg0482 "cannot dereference a tuple type"
#define Msg0483 "cannot dereference type '%s'"
#define Msg0484
#define Msg0485 "array access type should be integer, but is '%s'"
#define Msg0486 "cannot dereference a 'void' pointer"
#define Msg0487 "this should be a pointer"
#define Msg0488 "%s '%s' cannot be dereferenced like a pointer"
#define Msg0489 "'@init' first parameter should be a pointer, but is '%s'"
#define Msg0490 "'@init' count parameter should be an integer, but is '%s'"
#define Msg0491 "too many initialization parameters for type '%s'"
#define Msg0492
#define Msg0493 "cannot call '@postcopy' on type '%s' because it is marked with the 'Swag.NoCopy' attribute"
#define Msg0494
#define Msg0495 "'%s' first parameter should be a pointer, but is '%s'"
#define Msg0496 "'%s' second parameter should be a pointer, but is '%s'"
#define Msg0497 "'%s' second parameter should be a pointer to type '%s', but points to '%s'"
#define Msg0498 "'%s' count parameter should be an integer, but is '%s'"
#define Msg0499 "unknown module dependency '%s'"
#define Msg0500 "missing '%d' test errors (%d raised)"
#define Msg0501 "missing '%d' test warnings (%d raised)"
#define Msg0502 "cannot open file '%s'"
#define Msg0503 "[compiler internal] semantic failed (%s)"
#define Msg0504 "operation '%s' not allowed, left type is '%s' and right type is '%s'"
#define Msg0505 "%s overflow, maximum size is 0x%I64x bytes"
#define Msg0506
#define Msg0507 "fatal error: invalid module '%s', configuration file '%s' is missing"
#define Msg0508 "cannot find '%s' in module folder '%s'"
#define Msg0509 "cannot access file '%s'"
#define Msg0510 "cannot fetch file '%s' for module dependency '%s'"
#define Msg0511 "dependency module folder '%s' does not exist"
#define Msg0512
#define Msg0513 "cannot resolve module dependency '%s' ('location' is empty)"
#define Msg0514 "invalid 'location' format; should have the form 'location=\"mode@accesspath\"'"
#define Msg0515 "invalid 'location' mode; should be 'swag' or 'disk', not '%s'"
#define Msg0516 "cannot resolve dependency to module '%s' because of two different major versions ('%d' and '%d')"
#define Msg0517 "here is the other '#import'"
#define Msg0518 "cannot resolve dependency to module '%s', version '%s' cannot be found at location '%s'"
#define Msg0519 "command line error: invalid --stack-size value (%s), valid range is [%s, %s]"
#define Msg0520 "command line error: invalid abi '%s' for x64 backend"
#define Msg0521 "command line error: invalid vendor '%s' for x64 backend"
#define Msg0522 "command line error: invalid os '%s' for x64 backend"
#define Msg0523 "command line error: invalid arch '%s' for x64 backend"
#define Msg0524 "cannot open file '%s' for writing"
#define Msg0525 "cannot write to file '%s'"
#define Msg0526 "[safety] '@memcpy' destination pointer is null"
#define Msg0527 "[safety] '@memcpy' source pointer is null"
#define Msg0528 "[safety] '@memmove' destination pointer is null"
#define Msg0529 "[safety] '@memmove' source pointer is null"
#define Msg0530 "[safety] '@memset' destination pointer is null"
#define Msg0531 "[safety] '@memcmp' first pointer is null"
#define Msg0532 "[safety] '@memcmp' second pointer is null"
#define Msg0533 "[safety] '@cstrlen' pointer is null"
#define Msg0534 "uncatched error when calling '%s'; missing 'try', 'assume' or 'catch'"
#define Msg0535 "'%s' can only be used before a call that can raise errors"
#define Msg0536 "stack overflow (maximum stack size is '--stack-size:%s')"
#define Msg0537 "cannot convert typeinfo '%s' to runtime typeinfo"
#define Msg0538 "fatal error: invalid value '%s' for command line '--tag:%s'; this is not a valid literal"
#define Msg0539 "fatal error: command line --tag '%s' unsupported type '%s'"
#define Msg0540 "fatal error: missing workspace folder '--workspace'"
#define Msg0541 "fatal error: workspace folder '%s' does not exist"
#define Msg0542 "fatal error: invalid workspace '%s', subfolder 'modules/' or 'tests/' does not exist"
#define Msg0543 "cannot create public directory '%s'"
#define Msg0544
#define Msg0545 "fatal error: cannot create target directory '%s'"
#define Msg0546 "fatal error: cache directory '%s' does not exist"
#define Msg0547 "fatal error: cannot create cache directory '%s'"
#define Msg0548
#define Msg0549 "module '%s', cannot resolve %s '%s'"
#define Msg0550 "module '%s', cannot resolve %s"
#define Msg0551 "here is the declaration"
#define Msg0552 "fatal error: some problems have been found in compiler bootstrap !!!"
#define Msg0553 "here is the definition of the tuple"
#define Msg0554 "fatal error: some problems have been found in compiler runtime !!!"
#define Msg0555 "unsupported tuple type in generic parameters"
#define Msg0556 "module '%s' cannot be found in that workspace"
#define Msg0557 "dependency module '%s' cannot be found in that workspace"
#define Msg0558 "llvm backend cannot create target '%s'"
#define Msg0559 "'move' cannot be applied to a constant expression"
#define Msg0560
#define Msg0561
#define Msg0562
#define Msg0563
#define Msg0564 "affect operation not allowed, left expression is const"
#define Msg0565 "affect operation not allowed, left expression is not an l-value"
#define Msg0566 "affect operation not allowed"
#define Msg0567 "affect operation not allowed, left expression is not a variable"
#define Msg0568
#define Msg0569 "cannot affect an expression of type 'void'"
#define Msg0570 "'%s' operation not allowed on type 'any'"
#define Msg0571 "affect not allowed on %s '%s'"
#define Msg0572 "affect not allowed, '%s' is %s"
#define Msg0573 "invalid operation on a tuple type"
#define Msg0574 "affect to tuple is not possible because right expression is not compatible"
#define Msg0575
#define Msg0576
#define Msg0577
#define Msg0578
#define Msg0579 "pointer arithmetic not allowed with operand type '%s'"
#define Msg0580
#define Msg0581
#define Msg0582 "expected an attribute, but '%s' is %s"
#define Msg0583 "attribute '%s' can only be applied to %s"
#define Msg0584 "it is applied on this %s"
#define Msg0585
#define Msg0586 "attribute '%s' cannot be used in that context"
#define Msg0587 "here is attribute '%s'"
#define Msg0588 "attribute '%s' cannot be applied to %s"
#define Msg0589 "here is the %s"
#define Msg0590
#define Msg0591 "attribute '%s' assigned twice to '%s' ('Swag.AttrMulti' is not present in the declaration of '%s')"
#define Msg0592 "here is the faulty attribute"
#define Msg0593 "'Swag.Safety' invalid value '%s'"
#define Msg0594 "'Swag.Optim' invalid value '%s'"
#define Msg0595 "'Swag.Pack' value should be 0 or a power of two ('%d' provided)"
#define Msg0596 "'Swag.Align' value should be a power of two ('%d' provided)"
#define Msg0597 "invalid attribute usage"
#define Msg0598 "invalid attribute '%s'"
#define Msg0599 "'Swag.ExportType' invalid value '%s'"
#define Msg0600 "attribute '%s' does not have the 'File' usage, and cannot be used with '#global'"
#define Msg0601
#define Msg0602 "attribute parameter cannot be evaluated at compile time"
#define Msg0603 "cannot delete file '%s'"
#define Msg0604 "cannot create directory '%s'"
#define Msg0605
#define Msg0606 "%s should return a value"
#define Msg0607 "switch without an expression cannot be marked as 'Swag.Complete'"
#define Msg0608 "invalid switch type 'any', you need to cast to a concrete type"
#define Msg0609 "invalid switch type '%s'"
#define Msg0610 "switch body is empty"
#define Msg0611 "switch value '%s' already defined"
#define Msg0612 "switch enum value '%s' already defined"
#define Msg0613 "switch value '%d' already defined"
#define Msg0614 "switch value '%f' already defined"
#define Msg0615 "expression cannot be evaluated at compile time, and switch is 'Swag.Complete'"
#define Msg0616 "'default' is invalid in a switch marked with 'Swag.Complete'"
#define Msg0617 "'Swag.Complete' attribute cannot be used on a switch with type '%s'"
#define Msg0618
#define Msg0619 "here is the missing value"
#define Msg0620 "switch is incomplete (missing '%s.%s')"
#define Msg0621
#define Msg0622
#define Msg0623
#define Msg0624 "cannot visit a tuple"
#define Msg0625 "special visit name is only valid for struct (type is '%s')"
#define Msg0626 "too many 'visit' alias names (maximum is '2', but '%u' are provided)"
#define Msg0627 "cannot visit a variadic type by pointer"
#define Msg0628 "this cannot be visited"
#define Msg0629 "invalid type '%s' for 'visit'"
#define Msg0630 "'@index' can only be used inside a breakable loop"
#define Msg0631 "unknown label '%s'"
#define Msg0632 "'break' can only be used inside a breakable block"
#define Msg0633 "'fallthrough' can only be used inside a 'switch' block"
#define Msg0634 "'fallthrough' can only be used inside a 'case' block"
#define Msg0635 "'fallthrough' cannot be used in the last 'case' of the switch"
#define Msg0636 "cannot visit an enum by pointer"
#define Msg0637 "'continue' can only be used inside a breakable loop"
#define Msg0638
#define Msg0639 "label name '%s' already defined in the hierarchy"
#define Msg0640
#define Msg0641
#define Msg0642
#define Msg0643
#define Msg0644
#define Msg0645 "variable initialized twice, first with type arguments, and then with this assignment"
#define Msg0646 "expected an interface, but '%s' is %s"
#define Msg0647
#define Msg0648 "expected a struct, but '%s' is %s"
#define Msg0649
#define Msg0650 "function '%s' is not part of interface '%s'"
#define Msg0651 "here is the definition of interface '%s'"
#define Msg0652 "function '%s' has an incorrect signature for interface '%s'"
#define Msg0653 "should be"
#define Msg0654 "missing first parameter 'self' for interface function '%s'"
#define Msg0655 "bad type for first parameter of interface function implementation ('self' expected, '%s' provided)"
#define Msg0656
#define Msg0657 "some functions of interface '%s' are not implemented"
#define Msg0658
#define Msg0659 "implementation block for '%s' is private but the corresponding identifier is not"
#define Msg0660 "implementation block for '%s' is not private but the corresponding identifier is"
#define Msg0661 "implementation block is not defined in the same scope as '%s' ('impl' parent scope is '%s', '%s' parent scope is '%s')"
#define Msg0662 "expected a struct or an enum, but '%s' is %s"
#define Msg0663
#define Msg0664 "unsupported alias as an implementation block name"
#define Msg0665
#define Msg0666 "struct cannot be marked with 'Swag.Opaque' because it is not public"
#define Msg0667 "struct cannot be marked with 'Swag.Opaque' because the whole file is exported ('#global export')"
#define Msg0668 "'using' is invalid on a constant"
#define Msg0669 "'using' on a field is only valid for a struct type ('%s' provided)"
#define Msg0670 "initialization expression cannot be evaluated at compile time"
#define Msg0671 "type '%s' is generic, but struct '%s' does not declare generic parameters"
#define Msg0672 "cannot resolve struct '%s' because type '%s' is generic"
#define Msg0673 "cannot find structure member '%s' to compute variable relocation"
#define Msg0674 "struct member name '%s' starts with 'item', and this is reserved by the language"
#define Msg0675 "embedded struct '%s' cannot be public"
#define Msg0676 "an interface can only contain members of type 'lambda' ('%s' provided)"
#define Msg0677 "missing parameters for interface member '%s' ('self' expected as first parameter)"
#define Msg0678
#define Msg0679 "bad type for first parameter of interface member ('self' expected, '%s' provided)"
#define Msg0680 "cannot initialize an interface member"
#define Msg0681 "cannot resolve interface because type '%s' is generic"
#define Msg0682 "cannot relocate an interface member"
#define Msg0683 "interface '%s' is empty"
#define Msg0684 "embedded interface '%s' cannot be public"
#define Msg0685
#define Msg0686
#define Msg0687
#define Msg0688
#define Msg0689 "'using' on a variable cannot be used in '%s' scope"
#define Msg0690
#define Msg0691 "'using' cannot be used on an enum variable"
#define Msg0692 "'using' cannot be used on a variable of type '%s'"
#define Msg0693
#define Msg0694 "invalid 'using' type"
#define Msg0695 "'using' cannot be used on type %s"
#define Msg0696 "symbol already defined"
#define Msg0697 "invalid type '%s' for enum flags (should be unsigned integer)"
#define Msg0698 "invalid type '%s' for enum index (should be integer)"
#define Msg0699 "dimension of enum array type '%s' should be specified"
#define Msg0700 "enum array type '%s' should be 'const'"
#define Msg0701 "enum slice type '%s' should be 'const'"
#define Msg0702 "expected an enum type, found '%s'"
#define Msg0703
#define Msg0704
#define Msg0705
#define Msg0706 "enum value '%s' of type '%s' should be initialized"
#define Msg0707
#define Msg0708 "enum value '%s' is out of range of 'u8'"
#define Msg0709 "cannot deduce flag value of '%s' because previous value is not power of two"
#define Msg0710 "enum value '%s' is out of range of 'u16'"
#define Msg0711
#define Msg0712 "enum value '%s' is out of range of 'u32'"
#define Msg0713
#define Msg0714 "enum value '%s' is out of range of 'u64'"
#define Msg0715
#define Msg0716 "enum value '%s' is out of range of 's8'"
#define Msg0717 "enum value '%s' is out of range of 's16'"
#define Msg0718 "enum value '%s' is out of range of 's32'"
#define Msg0719 "enum value '%s' is out of range of 's64'"
#define Msg0720 "command line error: invalid argument '%s'"
#define Msg0721
#define Msg0722 "command line error: argument '%s' should be followed by '%s'"
#define Msg0723
#define Msg0724 "command line error: argument '%s' should be followed by 'true' or 'false' ('%s')"
#define Msg0725 "command line error: argument '%s' should be followed by a string"
#define Msg0726
#define Msg0727 "command line error: argument '%s' should be followed by an integer value"
#define Msg0728 "command line error: argument '%s' should be followed by an integer value ('%s')"
#define Msg0729 "type 'code' is only valid in a 'Swag.Macro' or 'Swag.Mixin' function"
#define Msg0730 "type 'alias' is only valid in a 'Swag.Macro' or 'Swag.Mixin' function"
#define Msg0731 "invalid type '%s' for attribute parameter"
#define Msg0732
#define Msg0733 "inline function has variadic arguments, this is not yet supported"
#define Msg0734 "variadic argument should be the last one"
#define Msg0735
#define Msg0736
#define Msg0737 "compiler instruction '%s' is invalid as a default parameter value"
#define Msg0738 "parameter '%d' should have a default value"
#define Msg0739 "'#main' directive already defined"
#define Msg0740
#define Msg0741 "'@alias' names are not all contiguous in function '%s' (missing '@alias%u')"
#define Msg0742 "function with the 'Swag.Foreign' attribute cannot have a body"
#define Msg0743 "compiler special function cannot have the 'Swag.Inline' attribute"
#define Msg0744 "'#test' functions can only be used in a test module (in the './tests' folder of the workspace)"
#define Msg0745 "function with the 'Swag.Test' attribute cannot have a return value"
#define Msg0746 "function with the 'Swag.Test' attribute cannot have parameters"
#define Msg0747 "%s cannot be public"
#define Msg0748 "not all control paths of %s return a value"
#define Msg0749 "%s missing return value"
#define Msg0750 "'#compiler' function should have 'Swag.CompilerMsgMask' as a parameter"
#define Msg0751
#define Msg0752
#define Msg0753 "function '%s' cannot have the 'Swag.Complete' attribute, this is reserved for 'opAffect'"
#define Msg0754 "function '%s' cannot have the 'Swag.Implicit' attribute, this is reserved for 'opAffect' and 'opCast'"
#define Msg0755 "function '%s' cannot have the 'Swag.NoReturn' attribute without 'Swag.Macro' or 'Swag.Mixin'"
#define Msg0756 "function '%s' cannot have the 'Swag.Implicit' attribute because it's generic"
#define Msg0757 "function '%s' is marked with 'Swag.Macro' and 'Swag.Inline' attributes at the same time"
#define Msg0758 "function '%s' is marked with 'Swag.Macro' and 'Swag.Mixin' attributes at the same time"
#define Msg0759 "function '%s' is marked with 'Swag.Mixin' and 'Swag.Inline' attributes at the same time"
#define Msg0760 "function '%s' is marked with 'Swag.Mixin' and 'Swag.Macro' attributes at the same time"
#define Msg0761 "function '%s' cannot be marked with 'Swag.Macro' attribute"
#define Msg0762 "function '%s' cannot be marked with 'Swag.Mixin' attribute"
#define Msg0763 "function '%s' cannot be marked with 'Swag.Inline' attribute"
#define Msg0764 "function cannot return a value of type '%s'"
#define Msg0765 "struct '%s' has the 'Swag.NoCopy' attribute, so 'opPostCopy' is irrelevant"
#define Msg0766 "function cannot have a return type because it is flagged with the 'Swag.NoReturn' attribute"
#define Msg0767 "function cannot have the 'Swag.Discardable' attribute because it returns 'void'"
#define Msg0768 "unreachable code"
#define Msg0769 "'retval' can only be used in a function body"
#define Msg0770
#define Msg0771 "'retval' cannot be used in a function that returns nothing"
#define Msg0772 "missing a return value ('%s')"
#define Msg0773 "this should be removed"
#define Msg0774 "returning a value of type '%s', but %s returns nothing"
#define Msg0775 "cannot expand '%s' because this is recursive"
#define Msg0776 "invalid name alias"
#define Msg0777 "invalid name alias, should be an identifier"
#define Msg0778 "invalid name alias, should be a single identifier"
#define Msg0779
#define Msg0780 "alias name '%s' is unused and should be removed"
#define Msg0781 "cannot expand '%s' in global scope because it contains sub declarations, this is not (yet?) supported"
#define Msg0782 "'@mkforeign' should have a lambda type as a first parameter"
#define Msg0783 "'@mkforeign' should have a 'const *void' as a second parameter"
#define Msg0784 "'@mkcallback' should have a lambda value as a first parameter"
#define Msg0785 "callback type not supported, too many parameters (maximum is '%d')"
#define Msg0786 "callback return type '%s' not supported"
#define Msg0787 "'%s' should have a pointer as a first parameter"
#define Msg0788 "'%s' cannot have 'null' as first parameter"
#define Msg0789 "'@mkany' should have a pointer as a first parameter"
#define Msg0790 "'@mkany' cannot have 'null' as first parameter"
#define Msg0791 "'pointer to value and type are not related (first parameter is a pointer to type '%s' but second parameter is type '%s')"
#define Msg0792 "'@mkany' should have a 'typeinfo' or a type value as a second parameter ('%s' provided)"
#define Msg0793 "'@mkinterface' should have a one dimension pointer or a struct as a first parameter"
#define Msg0794 "'@mkinterface' should have a typeinfo as a second parameter"
#define Msg0795 "'@mkinterface' should have an interface as a third parameter"
#define Msg0796 "'@dataof' cannot be used on a tuple type"
#define Msg0797 "'@dataof' cannot be applied to expression of type '%s'"
#define Msg0798 "expression cannot be evaluated at compile time"
#define Msg0799
#define Msg0800 "'@countof' cannot be used on a tuple type"
#define Msg0801 "'@countof' cannot be used on type '%s'"
#define Msg0802 "constant value should be unsigned, but is '%d'"
#define Msg0803
#define Msg0804
#define Msg0805 "constant value should be unsigned, but is '%I64d'"
#define Msg0806 "'@spread' can only be called as a function parameter"
#define Msg0807 "expression of type '%s' cannot be spreaded"
#define Msg0808
#define Msg0809
#define Msg0810 "cannot evaluate type in that context because it's generic"
#define Msg0811
#define Msg0812 "size cannot be computed because expression is generic"
#define Msg0813
#define Msg0814 "alignement cannot be computed because expression is generic"
#define Msg0815
#define Msg0816
#define Msg0817 "fatal error: workspace folder '%s' already exists"
#define Msg0818 "fatal error: cannot create directory '%s'"
#define Msg0819
#define Msg0820
#define Msg0821
#define Msg0822
#define Msg0823
#define Msg0824 "fatal error: cannot create file '%s'"
#define Msg0825
#define Msg0826
#define Msg0827 "negate an unsigned type ('%s') is not allowed"
#define Msg0828 "minus operation not allowed on type '%s'"
#define Msg0829 "cannot negate number '%d' because '%u' is not in the range of 's8'"
#define Msg0830 "cannot negate number '%d' because '%u' is not in the range of 's16'"
#define Msg0831 "cannot negate number '%d' because '%u' is not in the range of 's32'"
#define Msg0832 "cannot negate number '%I64d' because '%I64u' is not in the range of 's64'"
#define Msg0833 "bit inversion operation not allowed on type '%s'"
#define Msg0834 "%s size overflow"
#define Msg0835 "expected an identifier, found symbol '%s'"
#define Msg0836
#define Msg0837
#define Msg0838 "type 'Self' cannot be used outside an 'impl', 'struct' or 'interface' block"
#define Msg0839 "struct initialization should be done with '{}' and not parenthesis (this is reserved for function calls)"
#define Msg0840 "array size should be defined before the type name"
#define Msg0841 "invalid token '%s' after 'discard'"
#define Msg0842 "'%s' can only be used inside a function"
#define Msg0843 "invalid 'try' inside '%s' expression"
#define Msg0844 "invalid 'catch' inside '%s' expression"
#define Msg0845 "invalid 'assume' inside '%s' expression"
#define Msg0846 "invalid 'throw' inside '%s' expression"
#define Msg0847
#define Msg0848 "'catch' can only be used inside a function"
#define Msg0849
#define Msg0850
#define Msg0851
#define Msg0852
#define Msg0853 "'%s' should be immediatly followed by an identifier"
#define Msg0854 "'throw' can only be used inside a function"
#define Msg0855
#define Msg0856
#define Msg0857
#define Msg0858
#define Msg0859 "[safety] dereferencing a null pointer"
#define Msg0860
#define Msg0861 "intrinsic parameter expression cannot be empty"
#define Msg0862 "expression is empty"
#define Msg0863 "missing 'if' boolean expression before '{'"
#define Msg0864 "missing 'while' boolean expression before '{'"
#define Msg0865 "'case' or 'default' expected"
#define Msg0866 "'default' already defined"
#define Msg0867 "missing 'case' expression before ':'"
#define Msg0868 "missing 'case' expression before 'break'"
#define Msg0869 "'case' statement is empty"
#define Msg0870 "opVisit special name expected"
#define Msg0871 "missing the 'visit' expression to evaluate before '{'"
#define Msg0872 "missing another 'visit' variable name after ',' and before ':'"
#define Msg0873
#define Msg0874 "missing the 'loop' expression to evaluate before '{'"
#define Msg0875
#define Msg0876 "invalid label name, you should add ';' or put a valid label identifier"
#define Msg0877 "invalid label name, identifier expected"
#define Msg0878 "missing '#if' expression"
#define Msg0879 "missing '#global if' expression"
#define Msg0880 "no corresponding '}' has been found"
#define Msg0881 "identifier is preceeded with '.', but no scope can be found in context"
#define Msg0882
#define Msg0883 "missing function parameters before '{'"
#define Msg0884 "here is the other definition"
#define Msg0885 "symbol '%s' already defined as %s in an accessible scope"
#define Msg0886 "symbol '%s' already defined in an accessible scope"
#define Msg0887
#define Msg0888 "symbol '%s' already defined with the same signature in an accessible scope"
#define Msg0889
#define Msg0890 "symbol '%s' already defined as a name alias in an accessible scope"
#define Msg0891 "invalid '%s', use '%s' instead to do a logical test"
#define Msg0892 "placeholder identifier '%s' has not been solved"
#define Msg0893 "identifier '%s' has not been solved (do you have a cycle ?)"
#define Msg0894 "variable '%s' is used before being declared"
#define Msg0895 "expected a top level instruction"
#define Msg0896 "expected an embedded instruction or a curly block"
#define Msg0897 "expected a left expression"
#define Msg0898 "expected a left expression for variable declaration"
#define Msg0899 "expected an expression"
#define Msg0900 ", found symbol '%s' "
#define Msg0901 ", found identifier '%s' "
#define Msg0902 ", found type '%s' "
#define Msg0903 ", found token '%s' "
#define Msg0904 "; did you miss 'var' or 'const' to declare a global variable ?"
#define Msg0905 "unexpected end of line found in string literal"
#define Msg0906 "initialization value cannot be evaluated at compile time because 'opAffect' is not 'Swag.ConstExpr'"
#define Msg0907 "cannot cast from type '%s' to pointer type; only type 'uint' is accepted"
#define Msg0908 "'%s = %s' is impossible because special function 'opAffect' cannot be found in '%s'"
#define Msg0909 "type '%s' cannot be used in an union because it contains 'opPostCopy' (or one of its members does)"
#define Msg0910 "type '%s' cannot be used in an union because it contains 'opPostMove' (or one of its members does)"
#define Msg0911 "type '%s' cannot be used in an union because it contains 'opDrop' (or one of its members does)"

#define Hnt0000 "this divisor expression is zero"
#define Hnt0001 "this '@sqrt' is called with a negative value"
#define Hnt0002 "this value can only be converted to type '%s' with a dynamic call to 'opAffect'"
#define Hnt0003 "this is a static reference to a struct member"
#define Hnt0004 "this should be 'const %s'"
#define Hnt0005 "this could be casted to 'uint'"
#define Hnt0006
#define Hnt0007
#define Hnt0008
#define Hnt0009
#define Hnt0010
#define Hnt0011 "this type is '%s'"
#define Hnt0012 "this return (%s) should have type '%s'"
#define Hnt0013 "this should be on another line, or separated with ';'"
#define Hnt0014 "this is invalid in global scope"
#define Hnt0015 "this function is marked with the 'Swag.Macro' attribute"
#define Hnt0016 "this function is marked with the 'Swag.Mixin' attribute"
#define Hnt0017 "this function is marked with the 'Swag.Inline' attribute"
#define Hnt0018 "this is a constant"
#define Hnt0019 "this should be 'impl enum %s'"
#define Hnt0020 "this should be 'impl %s'"
#define Hnt0021
#define Hnt0022 "this type is immutable ('const')"
#define Hnt0023 "this call could be preceeded by 'discard' if you do not want to use the return value"
#define Hnt0024 "this is a pointer type declaration because of '*'"

#define Note000 "here is its declaration"
#define Note001 "'%s' is %s of type '%s' which does not contain a subscope"
#define Note002 "occurred %s %s'%s'"
#define Note003 "occurred %s"
#define Note004 "occurred in generated code"
#define Note005 "is there a missing 'self' ?"
#define Note006 "did you mean '%s' ?"
#define Note007 "here is the '%s'"
#define Note008 "here is %s"
#define Note009 "you can run swag with --dbgcatch to attach the bytecode debugger when the error occurs"
#define Note010 "'%s' is %s"
#define Note011 "%s is marked with 'Swag.NoReturn', so the return is used inside %s"
#define Note012 "note: use '-w:<path>' or '--workspace:<path>' to specifiy a valid workspace folder, or execute swag from a valid workspace folder"
#define Note013 "symbol has been found thanks to a 'using'"
#define Note014 "if you want to dereference variable '%s' like in C, use 'dref %s'"

#define Rem0000 "this could be casted with 'cast(%s)'"
#define Rem0001 "symbol '%s' was not found in '%s'"
#define Rem0002 "symbol '%s' exists in interface scope '%s'"
