SWAG_ERROR(Err0000, "fatal error: invalid swag command `%s`")
SWAG_ERROR(Err0001, "comparison operations are not allowed on type `%s`")
SWAG_ERROR(Err0002, "the type `%s` should not be used in a range expression")
SWAG_ERROR(Err0004, "cannot use the function `%s` because `%s` has failed")
SWAG_ERROR(Err0005, "the operation `%s` is not allowed on %s `%s`")
SWAG_ERROR(Err0006, "%s should be named because some parameters before are named")
SWAG_ERROR(Err0007, "comparison operations are not allowed on tuples")
SWAG_ERROR(Err0008, "use of an unknown named parameter `%s`")
SWAG_ERROR(Err0009, "a slice can only be compared to `null`")
SWAG_ERROR(Err0010, "an interface can only be compared to `null` or to another interface")
SWAG_ERROR(Err0011, "the named parameter `%s` is already defined")
SWAG_ERROR(Err0012, "expected an expression, found a type")
SWAG_ERROR(Err0013, "%s `%s` cannot be referenced in that context because it's not a value")
SWAG_ERROR(Err0014, "fatal error: not enough memory !")
SWAG_ERROR(Err0015, "bytecode stack overflow (maximum stack size is `--stack-size:%s`)")
SWAG_ERROR(Err0016, "not enough parameters for %s")
SWAG_ERROR(Err0017, "invalid type declaration, symbol `%s` is not a type (it is %s)")
SWAG_ERROR(Err0018, "cannot make %s public because %s `%s` is not public")
SWAG_ERROR(Err0020, "expected arguments `()` when calling %s")
SWAG_ERROR(Err0021, "the array dimension cannot be evaluated at compile time")
SWAG_ERROR(Err0022, "the array dimension should be of type integer (and `%s` is provided)")
SWAG_ERROR(Err0023, "the array dimension is 0")
SWAG_ERROR(Err0024, "a pointer to `Swag.TypeInfo` should be `const`")
SWAG_ERROR(Err0025, "the alias is public but `%s` is not")
SWAG_ERROR(Err0026, "too many parameters for %s (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0027, "an alias should only be used with a type or an identifier")
SWAG_ERROR(Err0028, "the `Swag.Strict` attribute should only be used on a type alias")
SWAG_ERROR(Err0029, "cannot alias a struct member")
SWAG_ERROR(Err0030, "alias should not be used on %s")
SWAG_ERROR(Err0031, "unexpected bitcast type `%s` (should be integer, rune or float)")
SWAG_ERROR(Err0032, "cannot bitcast from type `%s` (should be integer, pointer, rune or float)")
SWAG_ERROR(Err0033, "cannot bitcast to a type with a bigger size (`%s` from `%s`)")
SWAG_ERROR(Err0034, "ambiguous conversion of struct `%s` to interface `%s`")
SWAG_ERROR(Err0035, "not enough generic parameters for %s")
SWAG_ERROR(Err0036, "error: backend: cannot locate windows sdk folder")
SWAG_ERROR(Err0037, "the operation `%s` is not allowed because the left expression is an enum type (`%s`) not marked with `Swag.EnumFlags`")
SWAG_ERROR(Err0038, "the operation `%s` is not allowed because the right expression is an enum type (`%s`) not marked with `Swag.EnumFlags`")
SWAG_ERROR(Err0039, "cannot instantiate the generic struct `%s` because of missing contextual types replacements")
SWAG_ERROR(Err0040, "a partial type alias (`%s`) for a generic struct instantiation is not supported")
SWAG_ERROR(Err0041, "cannot instantiate the generic function `%s` because of missing generic parameters")
SWAG_ERROR(Err0042, "cannot instantiate the generic function `%s` because of missing contextual types replacements")
SWAG_ERROR(Err0043, "too many parameters for special function `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0044, "too many generic parameters for %s `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0045, "cannot create `%s` process (::CreatePipe)")
SWAG_ERROR(Err0046, "cannot create process `%s`")
SWAG_ERROR(Err0047, "mismatched types for %s of %s, generic type `%s` is assigned to `%s` (`%s` provided)")
SWAG_ERROR(Err0048, "unexpected type (`*Swag.CVaList` expected, `%s` provided")
SWAG_ERROR(Err0049, "expected the generic parameters of %s")
SWAG_ERROR(Err0050, "mismatched types for %s of %s (`%s` is expected for field `%s`, `%s` provided)")
SWAG_ERROR(Err0051, "cannot add `%s` to the `PATH` environment variable")
SWAG_ERROR(Err0052, "unexpected return value in a %s")
SWAG_ERROR(Err0053, "mismatched types for %s of %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0054, "unexpected generic %s for %s (a type is expected but a value is provided)")
SWAG_ERROR(Err0055, "`%s` should not be used as an expression")
SWAG_ERROR(Err0056, "x64 backend unsupported os `%s`")
SWAG_ERROR(Err0057, "unexpected generic %s for %s (a value is expected but a type is provided)")
SWAG_ERROR(Err0058, "cannot convert the type `%s` to a constant expression")
SWAG_ERROR(Err0059, "cannot convert the slice of type `%s` to a constant expression")
SWAG_ERROR(Err0060, "a compiler constant cannot be referenced at runtime")
SWAG_ERROR(Err0061, "no enough arguments for special function `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0062, "too few arguments for special function `%s` (at least `%d` expected, only `%d` provided)")
SWAG_ERROR(Err0063, "expected the return type of special function `%s`")
SWAG_ERROR(Err0064, "expected the return type of special function `%s` (`%s` expected)")
SWAG_ERROR(Err0065, "unexpected return type of special function `%s` (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0066, "mismatched types for %s of special function `%s` (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0067, "unexpected special function `%s` outside `impl`")
SWAG_ERROR(Err0068, "expected the parameters of special function `%s`")
SWAG_ERROR(Err0069, "unexpected first parameter type for special function `%s` (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0070, "unexpected type of generic %s for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0071, "unexpected number of generic parameters for special function `%s`")
SWAG_ERROR(Err0072, "unexpected generic parameter for special function `%s` (`string` expected, `%s` provided)")
SWAG_ERROR(Err0073, "unexpected number of generic parameters for special function `%s`")
SWAG_ERROR(Err0074, "unexpected generic parameter for special function `%s` (`bool` expected, `%s` provided)")
SWAG_ERROR(Err0075, "`opVisit` should have the `Swag.Macro` attribute")
SWAG_ERROR(Err0076, "the call level limit has been reached (the maximum level is `--max-recurse:%d`)")
SWAG_ERROR(Err0077, "unexpected second parameter for special function `%s` (cannot be of type `%s`)")
SWAG_ERROR(Err0078, "reserved function name `%s`")
SWAG_ERROR(Err0079, "cannot find special function `%s` in `%s`")
SWAG_ERROR(Err0080, "unexpected end of file found in the comment")
SWAG_ERROR(Err0081, "unexpected character `%s`")
SWAG_ERROR(Err0082, "the struct `%s` should be initialized in place with `{}` and not parenthesis (this is reserved for function calls)")
SWAG_ERROR(Err0083, "the %s `%s` is deprecated (marked with `Swag.Deprecated`)")
SWAG_ERROR(Err0084, "`@runes` should have a string as a parameter (`%s` provided)")
SWAG_ERROR(Err0085, "the identifier `%s` cannot be dereferenced like a struct (type is `%s`)")
SWAG_ERROR(Err0086, "the variable `%s` has only been used to find function `%s`; use the scope `%s` instead")
SWAG_ERROR(Err0087, "unexpected function call")
SWAG_ERROR(Err0088, "unexpected specified lambda parameter type")
SWAG_ERROR(Err0089, "`%s` cannot be evaluated at compile time")
SWAG_ERROR(Err0090, "cannot evaluate function parameter at compile time (type is `%s`)")
SWAG_ERROR(Err0091, "cannot reference the compile time %s `%s` (marked with `Swag.Compiler`) from runtime %s")
SWAG_ERROR(Err0092, "unused return value of lambda `%s`")
SWAG_ERROR(Err0093, "the identifier `%s` cannot be found in the tuple")
SWAG_ERROR(Err0094, "cannot discard a function call that returns nothing")
SWAG_ERROR(Err0095, "unexpected type of ufcs (first) parameter for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0096, "variable `%s` is used alone")
SWAG_ERROR(Err0097, "%s `%s` has not been used as the first parameter to call `%s`")
SWAG_ERROR(Err0098, "the function `%s` should be called with `()` and not curlies (this is reserved for struct initialization)")
SWAG_ERROR(Err0099, "unexpected aliased identifiers because the function `%s` is not a macro or a mixin")
SWAG_ERROR(Err0100, "unexpected call to the `opInit` special function (use `@init` instead)")
SWAG_ERROR(Err0101, "unexpected call to the `opDrop` special function (use `@drop` instead)")
SWAG_ERROR(Err0102, "evaluation of a function parameter of type `%s` is not supported at compile time")
SWAG_ERROR(Err0103, "unexpected call to the `opPostCopy` special function (use `@postcopy` instead)")
SWAG_ERROR(Err0104, "unexpected call to the `opPostMove` special function (use `@postmove` instead)")
SWAG_ERROR(Err0105, "cannot call an empty function (`%s`)")
SWAG_ERROR(Err0106, "unexpected type of `self` parameter for %s (`%s` expected, `%s` provided)")
SWAG_ERROR(Err0107, "referencing a compile time function (function `%s` is marked with `Swag.Compiler`) from runtime %s")
SWAG_ERROR(Err0108, "referencing a test function (function `%s` is marked with `Swag.Test`) from runtime `%s`")
SWAG_ERROR(Err0109, "unused return value of function `%s`")
SWAG_ERROR(Err0110, "the identifier `%s` cannot be found in %s `%s`")
SWAG_ERROR(Err0111, "during public export")
SWAG_ERROR(Err0112, "during generic expansion")
SWAG_ERROR(Err0113, "found %d overloads for `%s` but no one could match")
SWAG_ERROR(Err0114, "cannot take the address of a function with call parameters")
SWAG_ERROR(Err0115, "ambiguous resolution of generic %s `%s`")
SWAG_ERROR(Err0116, "ambiguous resolution of symbol `%s`")
SWAG_ERROR(Err0117, "cannot use `with` or `using` on two variables with the same type (`%s`)")
SWAG_ERROR(Err0118, "during inline expansion")
SWAG_ERROR(Err0119, "unsupported generic type deduction, this is too complicated (embedded tuples)")
SWAG_ERROR(Err0120, "expected a closure capture argument after `,` and before `|`")
SWAG_ERROR(Err0121, "expected a single identifier %s")
SWAG_ERROR(Err0122, "use of undeclared identifier `%s`")
SWAG_ERROR(Err0123, "the generic value `%s` has already been deduced from parameters to be `%s` (and `%s` is provided here)")
SWAG_ERROR(Err0124, "invalid lambda call, `%s` is not a variable (it is %s)")
SWAG_ERROR(Err0125, "the identifier `%s` has call parameters, but is a variable of type `%s` and not a function")
SWAG_ERROR(Err0126, "the `opSlice` special function should return a string or a slice (`%s` provided)")
SWAG_ERROR(Err0127, "the identifier `%s` has call parameters, but is %s and not a function")
SWAG_ERROR(Err0128, "during the `#selectif` validation of the function call")
SWAG_ERROR(Err0129, "during the `#checkif` validation of the function call")
SWAG_ERROR(Err0130, "unexpected generic parameters, the identifier `%s` is %s and not a function or a struct")
SWAG_ERROR(Err0132, "invalid reference to file scope")
SWAG_ERROR(Err0133, "cannot resolve the identifier `%s`")
SWAG_ERROR(Err0135, "unexpected generic parameters for %s `%s`")
SWAG_ERROR(Err0136, "an identifier with a backtick should only be used inside a `Swag.Macro` function or an `#inline` block")
SWAG_ERROR(Err0137, "`%s` should not be used inside a struct special function (`%s`)")
SWAG_ERROR(Err0138, "`%s` should only be used inside a function marked with `throw`, and `%s` is not")
SWAG_ERROR(Err0139, "`%s` should only be used before a function call, and `%s` is %s")
SWAG_ERROR(Err0140, "use of an unknown compiler instruction `%s`")
SWAG_ERROR(Err0141, "expected `[`, `{`, `(`, `\"` or an intrinsic name, found character `%c`")
SWAG_ERROR(Err0142, "operator `+` is not allowed with operand type `%s`")
SWAG_ERROR(Err0143, "operator `+` is not allowed on type `%s`")
SWAG_ERROR(Err0144, "pointer arithmetic is not allowed on `typeinfo`")
SWAG_ERROR(Err0145, "a digit separator `_` should not be followed by another digit separator")
SWAG_ERROR(Err0146, "operator `-` is not allowed with operand type `%s`")
SWAG_ERROR(Err0147, "operator `-` is not allowed on type `%s`")
SWAG_ERROR(Err0148, "operator `*` is not allowed on type `%s`")
SWAG_ERROR(Err0149, "operator `/` is not allowed on type `%s`")
SWAG_ERROR(Err0150, "division by zero")
SWAG_ERROR(Err0151, "expected at least one digit in the binary number")
SWAG_ERROR(Err0152, "a digit separator `_` should not end a literal number")
SWAG_ERROR(Err0153, "error reading source file `%s`")
SWAG_ERROR(Err0154, "a digit separator `_` should not start a literal number")
SWAG_ERROR(Err0155, "a digit separator `_` should not start a fractional part")
SWAG_ERROR(Err0156, "a digit separator `_` should not start an exponent part")
SWAG_ERROR(Err0157, "operator `%` is not allowed on type `%s`")
SWAG_ERROR(Err0158, "not enough hexadecimal digit, %s")
SWAG_ERROR(Err0159, "the `Swag.Tls` and `Swag.Compiler` attributes are exclusive")
SWAG_ERROR(Err0160, "cannot assign a function pointer to a constant")
SWAG_ERROR(Err0161, "cannot transform the type `%s` to a constant array because `opCount` returns `0`")
SWAG_ERROR(Err0162, "cannot transform the type `%s` to a constant array because `opSlice` returns an empty slice")
SWAG_ERROR(Err0163, "operator `|` is not allowed on type `%s`")
SWAG_ERROR(Err0164, "operator `&` is not allowed on type `%s`")
SWAG_ERROR(Err0165, "use of undeclared type `%s`")
SWAG_ERROR(Err0166, "fatal error: script file `%s` does not exist")
SWAG_ERROR(Err0167, "operator `^` is not allowed on type `%s`")
SWAG_ERROR(Err0168, "unexpected operation `%s` on a tuple type")
SWAG_ERROR(Err0169, "more than one module with the name `%s` is present in the workspace (path is `%s`)")
SWAG_ERROR(Err0170, "operator `<<` is not allowed on type `%s`")
SWAG_ERROR(Err0171, "expected the type of the array after the dimensions, but found `%s`")
SWAG_ERROR(Err0172, "operator `>>` is not allowed on type `%s`")
SWAG_ERROR(Err0173, "a shift operand should be of type `u32` and not `%s`")
SWAG_ERROR(Err0174, "unexpected hexadecimal digit `%c`, %s")
SWAG_ERROR(Err0175, "cannot cast implicitly from `%s` to `%s`")
SWAG_ERROR(Err0176, "cannot cast from struct to interface because `%s` (or one of its `using` fields) does not implement `%s`")
SWAG_ERROR(Err0177, "cannot cast from `%s` to `%s`")
SWAG_ERROR(Err0178, "cannot cast from a closure type to a lambda")
SWAG_ERROR(Err0179, "unexpected closure definition at global scope")
SWAG_ERROR(Err0180, "value `%I64d` is negative and does not fit in the unsigned type `%s`")
SWAG_ERROR(Err0181, "value `%I64u` does not fit in the type `%s`")
SWAG_ERROR(Err0182, "ambiguous resolution of special function `%s`")
SWAG_ERROR(Err0183, "value `%s` (`%I64u` in decimal) does not fit in the type `%s`")
SWAG_ERROR(Err0184, "`\\x` escape code needs 2 of them")
SWAG_ERROR(Err0185, "cannot affect a closure to a lambda type")
SWAG_ERROR(Err0186, "cannot find special function `%s` in `%s` when solving operator `%s`")
SWAG_ERROR(Err0187, "missing index when dereferencing array `%s`")
SWAG_ERROR(Err0188, "not enough parameters for %s (missing `%s` of type `%s`)")
SWAG_ERROR(Err0189, "expected arguments `()` when calling %s")
SWAG_ERROR(Err0190, "unexpected `throw` in attribute declaration")
SWAG_ERROR(Err0191, "too many parameters for %s (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0192, "pointer arithmetic is not allowed")
SWAG_ERROR(Err0193, "cannot slice a pointer which does not allow pointer arithmetic")
SWAG_ERROR(Err0194, "cannot dereference by index because the type does not allow pointer arithmetic")
SWAG_ERROR(Err0195, "too many parameters in tuple initialization (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0196, "not enough initializers for `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0197, "too many initializers for `%s` (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0198, "a `#run` block should not be used as an expression")
SWAG_ERROR(Err0199, "unexpected `opDrop` special function for `%s` because the struct is marked with `Swag.ConstExpr`")
SWAG_ERROR(Err0200, "cannot cast from `%s` to `%s` because `%s` has multiple fields of type `%s` with `using`")
SWAG_ERROR(Err0201, "the `%s` is referencing itself, which makes it recursive")
SWAG_ERROR(Err0202, "expected a type inside the tuple type definition, found `%s`")
SWAG_ERROR(Err0203, "cannot cast, not enough initializers (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0204, "cannot cast, too many initializers (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0205, "not enough parameters in tuple initialization (`%d` expected, `%d` provided)")
SWAG_ERROR(Err0206, "cannot reference the variable `%s` because it is in another stack frame")
SWAG_ERROR(Err0207, "[safety] truncated bits when casting expression from `%s` to `%s`")
SWAG_ERROR(Err0208, "[safety] cast from a negative value of type `%s` to unsigned type `%s`")
SWAG_ERROR(Err0209, "[safety] integer overflow during `+` operation on type `%s`")
SWAG_ERROR(Err0210, "[safety] integer overflow during `-` operation on type `%s`")
SWAG_ERROR(Err0211, "[safety] integer overflow during `*` operation on type `%s`")
SWAG_ERROR(Err0212, "[safety] integer overflow during `+=` operation on type `%s`")
SWAG_ERROR(Err0213, "[safety] integer overflow during `-=` operation on type `%s`")
SWAG_ERROR(Err0214, "[safety] integer overflow during `*=` operation on type `%s`")
SWAG_ERROR(Err0215, "[safety] `<<` shift operand value on type `%s` is greater than `%d`")
SWAG_ERROR(Err0216, "[safety] `>>` shift operand value on type `%s` is greater than `%d`")
SWAG_ERROR(Err0217, "[safety] integer overflow during `<<` operation on type `%s`")
SWAG_ERROR(Err0218, "[safety] integer overflow during `>>` operation on type `%s`")
SWAG_ERROR(Err0219, "[safety] `@abs` integer overflow on type `%s`")
SWAG_ERROR(Err0220, "[safety] integer overflow when taking the negative value of type `%s`")
SWAG_ERROR(Err0221, "[safety] division by zero")
SWAG_ERROR(Err0222, "[safety] index out of range")
SWAG_ERROR(Err0223, "cannot open #load file `%s`")
SWAG_ERROR(Err0224, "`\\u` escape code needs 4 of them")
SWAG_ERROR(Err0225, "`%s[index] = %s` is impossible because special function `opIndexAffect` cannot be found in `%s`")
SWAG_ERROR(Err0226, "cannot access by index because special function `opIndex` cannot be found in type `%s`")
SWAG_ERROR(Err0227, "cannot access `%s` by index because special function `opIndex` cannot be found in type `%s`")
SWAG_ERROR(Err0228, "use of an unknown function `%s`")
SWAG_ERROR(Err0229, "[safety] bad slicing, lower bound is greater than upper bound")
SWAG_ERROR(Err0230, "[safety] bad slicing, upper bound is out of range")
SWAG_ERROR(Err0231, "the copy of type `%s` is disabled because the struct is marked with `Swag.NoCopy`")
SWAG_ERROR(Err0232, "`#dependencies` should only be used in the module configuration file (`module.swg`)")
SWAG_ERROR(Err0233, "a `#selectif` expression should be of type `bool` (`%s` provided)")
SWAG_ERROR(Err0234, "`#ast` expression should be of type `string` (`%s` provided)")
SWAG_ERROR(Err0235, "`#import` should only be used inside a `#dependencies` block")
SWAG_ERROR(Err0236, "expected a type `string` as an `#assert` message (`%s` provided)")
SWAG_ERROR(Err0237, "`#assert` message string cannot be evaluated at compile time")
SWAG_ERROR(Err0238, "compiler assertion failed")
SWAG_ERROR(Err0239, "`#macro` should only be used inside a `Swag.Macro` function")
SWAG_ERROR(Err0240, "the expression should be of type `code`, but is `%s`")
SWAG_ERROR(Err0241, "`#semerror` has not triggered an error")
SWAG_ERROR(Err0242, "the filename cannot be evaluated at compile time")
SWAG_ERROR(Err0243, "the `#load` parameter should be of type string (`%s` provided)")
SWAG_ERROR(Err0244, "cannot find file `%s`")
SWAG_ERROR(Err0245, "`@gettag` name expected, found a type")
SWAG_ERROR(Err0246, "[safety] unexpected switch value (switch is marked with `Swag.Complete`)")
SWAG_ERROR(Err0247, "`#include` should only be used inside a `#dependencies` block")
SWAG_ERROR(Err0248, "`@hastag` name cannot be evaluated at compile time")
SWAG_ERROR(Err0249, "`@hastag` should be a string (`%s` provided)")
SWAG_ERROR(Err0250, "`@gettag` name value cannot be evaluated at compile time")
SWAG_ERROR(Err0251, "`@gettag` parameter should be a string, but is `%s`")
SWAG_ERROR(Err0252, "type `%s` and type `%s` defined in the command line for `%s` are incompatible")
SWAG_ERROR(Err0253, "`\\U` escape code needs 8 of them")
SWAG_ERROR(Err0254, "`#callerlocation` should only be used in a function parameter declaration")
SWAG_ERROR(Err0255, "`#callerfunction` should only be used in a function parameter declaration")
SWAG_ERROR(Err0256, "unknown `defer` mode `%s`")
SWAG_ERROR(Err0257, "failed to load the module `%s` while resolving the foreign function `%s`: %s")
SWAG_ERROR(Err0258, "cannot resolve the foreign function call to `%s`")
SWAG_ERROR(Err0259, "unrecognized character escape sequence `%c`")
SWAG_ERROR(Err0260, "unexpected character `[`")
SWAG_ERROR(Err0261, "cannot convert a boolean literal to `%s`")
SWAG_ERROR(Err0262, "unexpected character literal `%s` (this is a string, not a character)")
SWAG_ERROR(Err0263, "cannot convert the character literal to `u8`, value `%u` is too big")
SWAG_ERROR(Err0264, "unexpected operator modifier `%s`")
SWAG_ERROR(Err0265, "the operator modifier `%s` is already used once")
SWAG_ERROR(Err0266, "the operator modifier `%s` is invalid for operator `%s`")
SWAG_ERROR(Err0267, "unexpected compare operator `=`, do you mean `==` ?")
SWAG_ERROR(Err0268, "`#dependencies` should only be declared at the file level")
SWAG_ERROR(Err0269, "expected the `#main` function (executable entry point)")
SWAG_ERROR(Err0270, "the initializer list is empty")
SWAG_ERROR(Err0271, "a variable name or `?` is expected in a tuple unpacking, found `%s`")
SWAG_ERROR(Err0272, "the identifier `%s` starts with `__`, and this is reserved by the language")
SWAG_ERROR(Err0273, "unexpected generic parameters for the variable `%s`")
SWAG_ERROR(Err0274, "unexpected call parameters for the variable `%s`")
SWAG_ERROR(Err0275, "`@alias` special variable name should be followed by a number")
SWAG_ERROR(Err0276, "unexpected special variable name `%s`, `@alias` should be followed by a number (`%s` provided)")
SWAG_ERROR(Err0277, "an `@alias` number should be in the range [0, 31] (`%u` provided)")
SWAG_ERROR(Err0278, "invalid variable name `%s` (cannot start with `@`)")
SWAG_ERROR(Err0279, "unexpected tuple unpacking in %s")
SWAG_ERROR(Err0280, "cannot evaluate constant expression of type `%s` at compile time")
SWAG_ERROR(Err0281, "cannot evaluate constant expression of type `%s` at compile time because struct is not marked with `Swag.ConstExpr`")
SWAG_ERROR(Err0282, "attempt to unpack `%d` variable(s), but the expression on the right contains `%d` element(s)")
SWAG_ERROR(Err0283, "`@gettag` default value expected, found a type")
SWAG_ERROR(Err0284, "`#import` location already defined as `%s`")
SWAG_ERROR(Err0285, "expected an identifier, found a literal")
SWAG_ERROR(Err0286, "`#import` version already defined as `%s`")
SWAG_ERROR(Err0287, "cannot convert the character literal to `u16`, value `%u` is too big")
SWAG_ERROR(Err0288, "`#import` version invalid format")
SWAG_ERROR(Err0289, "the version should be of the form `version.revision.buildnum`, with each number >= 0 or the `?` character")
SWAG_ERROR(Err0290, "expected a struct, but symbol `%s` is %s")
SWAG_ERROR(Err0291, "cannot unpack the type `%s` (expected a struct or a tuple)")
SWAG_ERROR(Err0292, "cannot unpack `%s` because it does not contain any field")
SWAG_ERROR(Err0293, "attempt to unpack `%u` variable(s), but the tuple on the right contains `%u` field(s)")
SWAG_ERROR(Err0294, "`@mixin` special variable name should be followed by a number")
SWAG_ERROR(Err0295, "a struct cannot be initialized twice")
SWAG_ERROR(Err0296, "unexpected special variable name `%s`, `@mixin` should be followed by a number (`%s` provided)")
SWAG_ERROR(Err0297, "the attribute `Swag.Discardable` should only be used on a lambda variable (provided type is `%s`)")
SWAG_ERROR(Err0298, "a constant should be initialized")
SWAG_ERROR(Err0299, "a non mutable variable should be initialized")
SWAG_ERROR(Err0300, "a reference should be initialized")
SWAG_ERROR(Err0301, "a `@mixin` number should be in the range [0, 9] (`%u` provided)")
SWAG_ERROR(Err0302, "cannot convert from `string` to `%s`")
SWAG_ERROR(Err0303, "the size of the array cannot be deduced because there's no initialization expression")
SWAG_ERROR(Err0304, "cannot find #include file `%s`")
SWAG_ERROR(Err0305, "a constant should be explicitly initialized")
SWAG_ERROR(Err0306, "the `slice` type should be declared as immutable with `const` because the right expression is const")
SWAG_ERROR(Err0307, "the initialization expression is `void`")
SWAG_ERROR(Err0308, "cannot deduce the variable type because the expression is `null`")
SWAG_ERROR(Err0309, "unable to deduce type of %s `%s`")
SWAG_ERROR(Err0310, "the deduced `with` variable `%s` has only been used to find function `%s`; use the scope `%s` instead")
SWAG_ERROR(Err0311, "cannot create the constant because the type `%s` is generic")
SWAG_ERROR(Err0312, "cannot create the variable because the type `%s` is generic")
SWAG_ERROR(Err0313, "a global variable cannot be declared as `public`")
SWAG_ERROR(Err0314, "unexpected file format, should be ascii, utf-8 or utf-8-bom")
SWAG_ERROR(Err0315, "expected a variable name, found `%s`")
SWAG_ERROR(Err0316, "%s `%s` should be public because it is referenced in a public context")
SWAG_ERROR(Err0317, "cannot convert the floating point number `%Lf`")
SWAG_ERROR(Err0318, "fatal error: missing script file; use `--file:<filename>.swgs` to specify a script to run")
SWAG_ERROR(Err0319, "fatal error: invalid script file extension; should be `.swgs` instead of `%s`")
SWAG_ERROR(Err0320, "cannot slice `%s` because the special function `opSlice` has not been found in type `%s`")
SWAG_ERROR(Err0321, "cannot evaluate the tuple value at compile time because one of its members is not `Swag.ConstExpr`")
SWAG_ERROR(Err0322, "fatal error: invalid value for `--tag:%s` (%s)")
SWAG_ERROR(Err0323, "found `else` without a corresponding `if`")
SWAG_ERROR(Err0324, "found `#else` without a corresponding `#if`")
SWAG_ERROR(Err0325, "found `#elif` without a corresponding `#if`")
SWAG_ERROR(Err0326, "found `)` without a corresponding opening `(`")
SWAG_ERROR(Err0327, "found `}` without a corresponding opening `{`")
SWAG_ERROR(Err0328, "found `]` without a corresponding opening `[`")
SWAG_ERROR(Err0329, "missing `%s` %s")
SWAG_ERROR(Err0330, "expected `%s` instead of `%s` %s")
SWAG_ERROR(Err0331, "a line break or `;` is expected before `%s` to close the %s")
SWAG_ERROR(Err0332, "cannot use the operator `orelse` on type `%s`")
SWAG_ERROR(Err0333, "expected an alias name, found `%s`")
SWAG_ERROR(Err0334, "`self` should only be used inside a struct or `impl` block")
SWAG_ERROR(Err0335, "`#import` has a specific revision (`%d`) but undefined major version (`?`)")
SWAG_ERROR(Err0336, "`#import` has a specific build number (`%d`) but undefined revision (`?`)")
SWAG_ERROR(Err0337, "cannot use a range in a switch with an expression")
SWAG_ERROR(Err0338, "too many array dimensions (maximum is `254`)")
SWAG_ERROR(Err0339, "expected a pointer declaration `*` after `const`")
SWAG_ERROR(Err0340, "too many pointer dimensions (maximim is `%u`)")
SWAG_ERROR(Err0341, "literal number `%I64u` is not in the range of `u8`")
SWAG_ERROR(Err0342, nullptr)
SWAG_ERROR(Err0343, "expected a type declaration, found `%s`")
SWAG_ERROR(Err0344, "fatal error: cannot delete file `%s`")
SWAG_ERROR(Err0345, "fatal error: cannot delete directory `%s`")
SWAG_ERROR(Err0346, "the symbol `%s` is already defined in the parent scope")
SWAG_ERROR(Err0347, "fatal error: cannot create script file `%s`")
SWAG_ERROR(Err0348, "`#self` should only be used inside a function")
SWAG_ERROR(Err0349, "a %s definition should appear at file or namespace scope")
SWAG_ERROR(Err0350, "`%s` attribute should not be used in a file marked with `#global export` because the whole file is implicitly public")
SWAG_ERROR(Err0351, "found `elif` without a corresponding `if`")
SWAG_ERROR(Err0352, "cannot deduce the generic parameters when calling the special %s")
SWAG_ERROR(Err0353, "unexpected token `%s` after the `%s` expose attribute")
SWAG_ERROR(Err0354, "unexpected attribute usage (`%s`) after the `%s` expose attribute")
SWAG_ERROR(Err0355, "expected an attribute name, found `%s`")
SWAG_ERROR(Err0356, "the attribute usage is empty")
SWAG_ERROR(Err0357, "literal number `%I64u` is not in the range of `u16`")
SWAG_ERROR(Err0358, "literal number `%I64u` is not in the range of `u32`")
SWAG_ERROR(Err0359, "literal number `%I64d` is not in the range of `s8`")
SWAG_ERROR(Err0360, "literal number `%I64d` is not in the range of `s16`")
SWAG_ERROR(Err0361, "literal number `%I64d` is not in the range of `s32`")
SWAG_ERROR(Err0362, "literal number `%I64u` is not in the range of `rune`")
SWAG_ERROR(Err0363, "`#include` should only be declared at the top level scope")
SWAG_ERROR(Err0364, "a `#mixin` replacement block should only be used inside a breakable statement (`loop`, `visit`, `for` ...)")
SWAG_ERROR(Err0365, "`#mixin` invalid replacement `%s`")
SWAG_ERROR(Err0366, "`#mixin` has an empty replacement block")
SWAG_ERROR(Err0367, "`#semerror` is invalid outside a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0368, "`#semerror` cannot be in a `#if` block")
SWAG_ERROR(Err0369, "`#global` should be defined first, at the top of the file")
SWAG_ERROR(Err0370, "`#global export` already defined")
SWAG_ERROR(Err0371, "`#global foreignlib` should be followed by a string")
SWAG_ERROR(Err0372, "`#global using` can only be used in a module configuration file")
SWAG_ERROR(Err0373, "unexpected pass name `%s`")
SWAG_ERROR(Err0374, "`#global testerror` is invalid outside a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0375, "`#global testwarning` is invalid outside a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0376, "`#global` unexpected instruction `%s`")
SWAG_ERROR(Err0377, "`#import` should only be used in the module configuration file (`module.swg`)")
SWAG_ERROR(Err0378, "`#import` should only be declared at the top level scope")
SWAG_ERROR(Err0379, "`#import` should be followed by a string")
SWAG_ERROR(Err0380, "`#import` location defined twice")
SWAG_ERROR(Err0381, "invalid location `%s`")
SWAG_ERROR(Err0382, "`#import` version defined twice")
SWAG_ERROR(Err0383, "invalid version `%s`")
SWAG_ERROR(Err0384, "a `#placeholder` should only be declared in a top level scope")
SWAG_ERROR(Err0385, "`#placeholder` should be followed by an identifier")
SWAG_ERROR(Err0386, "a global `using` should be declared at the top of the file")
SWAG_ERROR(Err0387, "invalid literal number conversion of `%I64u`")
SWAG_ERROR(Err0388, "a namespace definition should appear either at file scope or immediately within another namespace definition")
SWAG_ERROR(Err0389, "expected the namespace name before `{`")
SWAG_ERROR(Err0390, "expected the namespace name before `;`")
SWAG_ERROR(Err0391, "a namespace name should be an identifier (`%s` provided)")
SWAG_ERROR(Err0392, "the `%s` namespace is reserved by the compiler")
SWAG_ERROR(Err0393, "a namespace cannot have the same name as the module (`%s`)")
SWAG_ERROR(Err0394, "literal number `%I64u` is not in the range of `u8`")
SWAG_ERROR(Err0395, "unexpected label identifier `%s`")
SWAG_ERROR(Err0396, "expected an enum name, found `%s`")
SWAG_ERROR(Err0397, "fatal error: module `%s` already exists in the `/modules` folder")
SWAG_ERROR(Err0398, "literal number `%I64u` is not in the range of `u16`")
SWAG_ERROR(Err0399, "`{` is expected instead of `%s`")
SWAG_ERROR(Err0400, "expected an enum value identifier, found `%s`")
SWAG_ERROR(Err0401, "expected an identifier")
SWAG_ERROR(Err0402, "unexpected token, `,` expected")
SWAG_ERROR(Err0403, "invalid named parameter `%s`")
SWAG_ERROR(Err0404, "literal number `%I64u` is not in the range of `u32`")
SWAG_ERROR(Err0405, "const before a function parameter name can only be followed by `self`")
SWAG_ERROR(Err0406, "`self` should only be used inside an `impl` block")
SWAG_ERROR(Err0407, "a method should only be declared inside an `impl` block")
SWAG_ERROR(Err0408, "unexpected parameter name `%s`")
SWAG_ERROR(Err0409, "expected the function parameter type or assignment (`:` or `=`)")
SWAG_ERROR(Err0410, "invalid variable name `%s`")
SWAG_ERROR(Err0411, "expected the generic parameters")
SWAG_ERROR(Err0412, "expected a generic name or a type")
SWAG_ERROR(Err0413, "invalid function name `%s`")
SWAG_ERROR(Err0414, "expected the function name instead of `%s`")
SWAG_ERROR(Err0415, "literal number `%I64u` is not in the range of `s8`")
SWAG_ERROR(Err0416, "expected `{` to start the %s body, found `;`")
SWAG_ERROR(Err0417, "`@power` called with invalid values `%.3f` and `%.3f`")
SWAG_ERROR(Err0418, "cannot cast from an immutable type (`%s`) to a mutable one (`%s`)")
SWAG_ERROR(Err0419, "a cycle has been detected during resolution of %s `%s`")
SWAG_ERROR(Err0422, "literal number `%I64u` is not in the range of `s16`")
SWAG_ERROR(Err0423, "`@log2` is called with an invalid value (`%.3f`)")
SWAG_ERROR(Err0424, "`@log10` is called with an invalid value (`%.3f`)")
SWAG_ERROR(Err0425, "`@sqrt` is called with an invalid value (`%.3f`)")
SWAG_ERROR(Err0426, "`@asin` is called with an invalid value (`%.3f`)")
SWAG_ERROR(Err0427, "`@acos` is called with an invalid value (`%.3f`)")
SWAG_ERROR(Err0428, "`@log` is called with an invalid value (`%.3f`)")
SWAG_ERROR(Err0429, "literal number `%I64u` is not in the range of `s32`")
SWAG_ERROR(Err0430, "literal number `%I64u` is not in the range of `s64`")
SWAG_ERROR(Err0431, "the runtime variable `%s` is initialized to zero and cannot be changed at compile time; initialize it with `?` if this is intended")
SWAG_ERROR(Err0432, "literal number `%I64u` is not in the range of `rune`")
SWAG_ERROR(Err0433, "invalid literal number conversion of `%I64u`")
SWAG_ERROR(Err0434, "expected at least one digit in the hexadecimal number")
SWAG_ERROR(Err0435, "exception during compile time execution !")
SWAG_ERROR(Err0436, "it could be a bug in the compile time part of your program")
SWAG_ERROR(Err0437, "literal suffix type must be native (`%s` provided)")
SWAG_ERROR(Err0438, "`for` is invalid for an enum implementation block")
SWAG_ERROR(Err0439, "unexpected literal suffix type (`%s`)")
SWAG_ERROR(Err0440, "unexpected generic parameters, should be naked")
SWAG_ERROR(Err0441, "the implementation block kind (%s) does not match the type of `%s` (%s)")
SWAG_ERROR(Err0442, "`@cvastart` intrinsic should only be used in a function with its last argument of type `cvarargs`")
SWAG_ERROR(Err0443, "`@cvaarg` unsupported type `%s`")
SWAG_ERROR(Err0444, "expected a struct name, found `%s`")
SWAG_ERROR(Err0445, "`@cvaarg` unsupported type `%s` (type has been promoted to `%s` at the call site)")
SWAG_ERROR(Err0446, "a parameter of type `cvarargs` cannot be passed from function to function")
SWAG_ERROR(Err0447, "empty tuple definition")
SWAG_ERROR(Err0448, "expected an identifier")
SWAG_ERROR(Err0449, "unexpected token `%s` in tuple type, `,` or `}` are expected here")
SWAG_ERROR(Err0450, "too many generic parameters for special function `%s`")
SWAG_ERROR(Err0451, "`using` on a member is invalid in an interface definition")
SWAG_ERROR(Err0452, "a method should not be declared inside an `enum impl` block")
SWAG_ERROR(Err0453, "`var` is not necessary to declare a field inside a struct")
SWAG_ERROR(Err0454, "unexpected affect operator `==`, do you mean `=` ?")
SWAG_ERROR(Err0455, "expected `:` or `=` in the variable declaration, found `%s`")
SWAG_ERROR(Err0456, "expected `(` to start the closure parameters")
SWAG_ERROR(Err0457, "the variable should have a type or should be initialized")
SWAG_ERROR(Err0458, "unexpected specified lambda return type")
SWAG_ERROR(Err0459, "too many digits in the literal number")
SWAG_ERROR(Err0460, "expected a binary digit, found `%s`")
SWAG_ERROR(Err0461, "`#include` should only be used in the module configuration file (`module.swg`)")
SWAG_ERROR(Err0462, "cannot take the address of a function parameter of type `%s`")
SWAG_ERROR(Err0463, "expected an hexadecimal digit, found `%s`")
SWAG_ERROR(Err0464, "literal number is too big (cannot fit in 64 bits)")
SWAG_ERROR(Err0465, "cannot take the address of %s")
SWAG_ERROR(Err0466, "a floating point number exponent should have at least one digit")
SWAG_ERROR(Err0467, "unexpected literal number prefix `%s` (should be `0x` or `0b`)")
SWAG_ERROR(Err0468, "the index is out of range (index is `%I64u` but the maximum value is `%I64u`)")
SWAG_ERROR(Err0469, "cannot take the address of a constant of type `%s`")
SWAG_ERROR(Err0470, "invalid address expression")
SWAG_ERROR(Err0471, "cannot take the address of a macro")
SWAG_ERROR(Err0472, "cannot take the address of a mixin")
SWAG_ERROR(Err0473, "cannot take the address of an inline function")
SWAG_ERROR(Err0474, "the slicing operator cannot be applied on an array with multiple dimensions (type is `%s`)")
SWAG_ERROR(Err0475, "the slicing operator cannot be applied on type `%s`")
SWAG_ERROR(Err0476, "the lower bound `%I64u` of the slicing arguments is greater than the upper bound `%I64u`")
SWAG_ERROR(Err0477, "the upper bound `%I64u` of the slicing arguments is out of range (maximum value is `%I64u`)")
SWAG_ERROR(Err0478, "the special function `%s` cannot have generic parameters")
SWAG_ERROR(Err0479, "`#include` should be followed by a string")
SWAG_ERROR(Err0480, "cannot take the address by index of a struct")
SWAG_ERROR(Err0481, "cannot dereference type `%s`")
SWAG_ERROR(Err0482, "cannot dereference a tuple type like a pointer or an array")
SWAG_ERROR(Err0483, "unexpected affect expression in `with`")
SWAG_ERROR(Err0484, "unexpected interface lambda declaration")
SWAG_ERROR(Err0485, "an array access value should be of type integer (`%s` provided)")
SWAG_ERROR(Err0486, "cannot dereference a pointer to `void`")
SWAG_ERROR(Err0487, nullptr)
SWAG_ERROR(Err0488, "%s `%s` cannot be dereferenced like a pointer")
SWAG_ERROR(Err0489, "the `@init` first parameter should be a pointer (`%s` provided)")
SWAG_ERROR(Err0490, "the `@init` second parameter should be an integer (`%s` provided)")
SWAG_ERROR(Err0491, "too many initialization parameters for type `%s`")
SWAG_ERROR(Err0492, nullptr)
SWAG_ERROR(Err0493, "cannot call `@postcopy` on type `%s` because it is marked with the `Swag.NoCopy` attribute")
SWAG_ERROR(Err0494, nullptr)
SWAG_ERROR(Err0495, "`%s` first parameter should be a pointer, but is `%s`")
SWAG_ERROR(Err0496, "`%s` second parameter should be a pointer, but is `%s`")
SWAG_ERROR(Err0497, "`%s` second parameter should be a pointer to type `%s`, but points to `%s`")
SWAG_ERROR(Err0498, "`%s` count parameter should be an integer, but is `%s`")
SWAG_ERROR(Err0499, "use of an unknown module dependency `%s`")
SWAG_ERROR(Err0500, "expected `%d` test errors (%d raised)")
SWAG_ERROR(Err0501, "expected `%d` test warnings (%d raised)")
SWAG_ERROR(Err0502, "cannot open file `%s`")
SWAG_ERROR(Err0503, nullptr)
SWAG_ERROR(Err0504, "the operation `%s` is not allowed, left type is `%s` and right type is `%s`")
SWAG_ERROR(Err0505, "%s overflow, the maximum supported size is `0x%I64x` bytes")
SWAG_ERROR(Err0506, nullptr)
SWAG_ERROR(Err0507, "fatal error: invalid module `%s`, configuration file `%s` is missing")
SWAG_ERROR(Err0508, "cannot find `%s` in module folder `%s`")
SWAG_ERROR(Err0509, "cannot access file `%s`")
SWAG_ERROR(Err0510, "cannot fetch file `%s` for module dependency `%s`")
SWAG_ERROR(Err0511, "dependency module folder `%s` does not exist")
SWAG_ERROR(Err0512, "a %s cannot be marked with the `Swag.NoReturn` attribute")
SWAG_ERROR(Err0513, "cannot resolve the module dependency `%s` (`location` is empty)")
SWAG_ERROR(Err0514, "invalid `location` format; should have the form `location=\"mode@accesspath\"`")
SWAG_ERROR(Err0515, "invalid `location` mode; should be `swag` or `disk`, not `%s`")
SWAG_ERROR(Err0516, "cannot resolve the dependency to module `%s` because of two different major versions (`%d` and `%d`)")
SWAG_ERROR(Err0517, nullptr)
SWAG_ERROR(Err0518, "cannot resolve the dependency to module `%s`, version `%s` cannot be found at location `%s`")
SWAG_ERROR(Err0519, "command line error: invalid --stack-size value (%s), valid range is [%s, %s]")
SWAG_ERROR(Err0520, nullptr)
SWAG_ERROR(Err0521, nullptr)
SWAG_ERROR(Err0522, "command line error: invalid os `%s` for x64 backend")
SWAG_ERROR(Err0523, "command line error: invalid arch `%s` for x64 backend")
SWAG_ERROR(Err0524, "cannot open file `%s` for writing")
SWAG_ERROR(Err0525, "cannot write to file `%s`")
SWAG_ERROR(Err0526, nullptr)
SWAG_ERROR(Err0527, nullptr)
SWAG_ERROR(Err0528, nullptr)
SWAG_ERROR(Err0529, nullptr)
SWAG_ERROR(Err0530, nullptr)
SWAG_ERROR(Err0531, nullptr)
SWAG_ERROR(Err0532, "a literal with a suffix (in that case `%s`) should only be used in a struct conversion")
SWAG_ERROR(Err0533, nullptr)
SWAG_ERROR(Err0534, "uncatched error when calling `%s` (expected `try`, `assume` or `catch`)")
SWAG_ERROR(Err0535, "`%s` should only be used before a function call that can raise errors (a function marked with `throw`)")
SWAG_ERROR(Err0536, "stack overflow (maximum stack size is `--stack-size:%s`)")
SWAG_ERROR(Err0537, "cannot convert typeinfo `%s` to runtime typeinfo")
SWAG_ERROR(Err0538, "fatal error: invalid value `%s` for command line `--tag:%s`; this is not a valid literal")
SWAG_ERROR(Err0539, "fatal error: command line --tag `%s` unsupported type `%s`")
SWAG_ERROR(Err0540, "fatal error: expected workspace folder `--workspace`")
SWAG_ERROR(Err0541, "fatal error: workspace folder `%s` does not exist")
SWAG_ERROR(Err0542, "fatal error: invalid workspace `%s`, subfolder `modules/` or `tests/` does not exist")
SWAG_ERROR(Err0543, "fatal error: cannot create public directory `%s`")
SWAG_ERROR(Err0544, nullptr)
SWAG_ERROR(Err0545, "fatal error: cannot create target directory `%s`")
SWAG_ERROR(Err0546, "fatal error: cache directory `%s` does not exist")
SWAG_ERROR(Err0547, "fatal error: cannot create cache directory `%s`")
SWAG_ERROR(Err0548, nullptr)
SWAG_ERROR(Err0549, "cannot resolve %s `%s`")
SWAG_ERROR(Err0550, "cannot resolve type `%s`")
SWAG_ERROR(Err0551, nullptr)
SWAG_ERROR(Err0552, "fatal error: some problems have been found in compiler bootstrap !!!")
SWAG_ERROR(Err0553, nullptr)
SWAG_ERROR(Err0554, "fatal error: some problems have been found in compiler runtime !!!")
SWAG_ERROR(Err0555, "tuple types in generic parameters are not (yet?) supported")
SWAG_ERROR(Err0556, "the module `%s` cannot be found in that workspace")
SWAG_ERROR(Err0557, "dependency module `%s` cannot be found in that workspace")
SWAG_ERROR(Err0558, "llvm backend cannot create target `%s`")
SWAG_ERROR(Err0559, "`move` cannot be applied to a constant expression (type is `%s`)")
SWAG_ERROR(Err0560, "the `retval` type is invalid for a function return type")
SWAG_ERROR(Err0561, "`]` should not be followed by a line break when declaring an array type")
SWAG_ERROR(Err0562, nullptr)
SWAG_ERROR(Err0563, nullptr)
SWAG_ERROR(Err0564, "the affectation is not allowed because the left expression is immutable (`const`)")
SWAG_ERROR(Err0565, "the affectation is not allowed because the left expression is not a value")
SWAG_ERROR(Err0566, "the affectation is not allowed")
SWAG_ERROR(Err0567, "the affectation is not allowed because the left expression is not a variable")
SWAG_ERROR(Err0568, nullptr)
SWAG_ERROR(Err0569, "cannot affect an expression of type `void`")
SWAG_ERROR(Err0570, "`%s` operation is not allowed on type `any`")
SWAG_ERROR(Err0571, "the affectation is not allowed on %s `%s`")
SWAG_ERROR(Err0572, "the affectation is not allowed, `%s` is %s")
SWAG_ERROR(Err0573, "unexpected operation on a tuple type")
SWAG_ERROR(Err0574, "the affectation to the tuple is not possible because the right expression is not compatible")
SWAG_ERROR(Err0575, nullptr)
SWAG_ERROR(Err0576, nullptr)
SWAG_ERROR(Err0577, nullptr)
SWAG_ERROR(Err0578, nullptr)
SWAG_ERROR(Err0579, "pointer arithmetic is not allowed with operand type `%s`")
SWAG_ERROR(Err0580, nullptr)
SWAG_ERROR(Err0581, nullptr)
SWAG_ERROR(Err0582, "expected an attribute, but `%s` is %s")
SWAG_ERROR(Err0583, "the attribute `%s` can only be applied to %s")
SWAG_ERROR(Err0585, nullptr)
SWAG_ERROR(Err0586, "the attribute `%s` should not be used in that context")
SWAG_ERROR(Err0587, nullptr)
SWAG_ERROR(Err0588, "the attribute `%s` cannot be applied to %s")
SWAG_ERROR(Err0589, nullptr)
SWAG_ERROR(Err0590, nullptr)
SWAG_ERROR(Err0591, "the attribute `%s` is assigned twice, and `Swag.AttrMulti` is not present in the declaration of `%s`")
SWAG_ERROR(Err0592, nullptr)
SWAG_ERROR(Err0593, "unexpected `Swag.Safety` parameter `%s`")
SWAG_ERROR(Err0594, "unexpected `Swag.Optim` parameter `%s`")
SWAG_ERROR(Err0595, "a `Swag.Pack` value should be 0 or a power of two (`%d` provided)")
SWAG_ERROR(Err0596, "a `Swag.Align` value should be a power of two (`%d` provided)")
SWAG_ERROR(Err0597, "unexpected attribute usage")
SWAG_ERROR(Err0598, "invalid attribute `%s`")
SWAG_ERROR(Err0599, "unexpected `Swag.ExportType` parameter `%s`")
SWAG_ERROR(Err0600, "the attribute `%s` does not have the `Swag.AttributeUsage.File` usage, so it should not be used with `#global`")
SWAG_ERROR(Err0601, "the `Swag.Using` is empty")
SWAG_ERROR(Err0602, "the attribute parameter cannot be evaluated at compile time")
SWAG_ERROR(Err0603, "cannot delete file `%s`")
SWAG_ERROR(Err0604, "cannot create directory `%s`")
SWAG_ERROR(Err0605, nullptr)
SWAG_ERROR(Err0606, "%s should return a value")
SWAG_ERROR(Err0607, "a switch without an expression cannot be marked as `Swag.Complete`")
SWAG_ERROR(Err0608, "unexpected switch type `any`, you need to cast to a concrete type")
SWAG_ERROR(Err0609, "unexpected switch type `%s`")
SWAG_ERROR(Err0610, "the switch body is empty")
SWAG_ERROR(Err0611, "the switch value `%s` has already been defined")
SWAG_ERROR(Err0612, "the switch enum value `%s` has already been defined")
SWAG_ERROR(Err0613, "the switch value `%d` has already been defined")
SWAG_ERROR(Err0614, "the switch value `%f` has already been defined")
SWAG_ERROR(Err0615, "the expression cannot be evaluated at compile time, and the switch is marked with `Swag.Complete`")
SWAG_ERROR(Err0616, "the `default` statement should be removed in a switch marked with `Swag.Complete`")
SWAG_ERROR(Err0617, nullptr)
SWAG_ERROR(Err0618, nullptr)
SWAG_ERROR(Err0619, nullptr)
SWAG_ERROR(Err0620, "the switch is incomplete (missing `%s.%s`)")
SWAG_ERROR(Err0621, nullptr)
SWAG_ERROR(Err0622, "expected a constant name, found `%s`")
SWAG_ERROR(Err0623, "expected a variable type or an assignment (`:` or `=`)")
SWAG_ERROR(Err0624, "cannot visit a tuple type")
SWAG_ERROR(Err0625, "a special visit name is only valid for a struct (and type is `%s`)")
SWAG_ERROR(Err0626, "too many `visit` alias names (maximum is `2`, but `%u` are provided)")
SWAG_ERROR(Err0627, "cannot visit a variadic type by pointer")
SWAG_ERROR(Err0628, "a pointer type (`%s`) cannot be visited with `visit`")
SWAG_ERROR(Err0629, "an expression of type `%s` cannot be visited with `visit`")
SWAG_ERROR(Err0630, "`@index` should only be used inside a breakable loop (`visit`, `loop` ...)")
SWAG_ERROR(Err0631, "use of an unknown label `%s`")
SWAG_ERROR(Err0632, "`break` should only be used inside a breakable block")
SWAG_ERROR(Err0633, "`fallthrough` should only be used inside a `switch` block")
SWAG_ERROR(Err0634, "`fallthrough` should only be used inside a `case` block")
SWAG_ERROR(Err0635, "`fallthrough` should not be used in the last `case` of a `switch`")
SWAG_ERROR(Err0636, "cannot visit an enum by pointer")
SWAG_ERROR(Err0637, "`continue` should only be used inside a breakable loop (`for`, `visit`, `loop`, `while` ...)")
SWAG_ERROR(Err0638, nullptr)
SWAG_ERROR(Err0639, "label name `%s` already defined in the hierarchy")
SWAG_ERROR(Err0640, nullptr)
SWAG_ERROR(Err0641, nullptr)
SWAG_ERROR(Err0642, nullptr)
SWAG_ERROR(Err0643, nullptr)
SWAG_ERROR(Err0644, nullptr)
SWAG_ERROR(Err0645, "the variable is initialized twice, first with type arguments, and then with an assignment")
SWAG_ERROR(Err0646, "expected an interface, but `%s` is %s")
SWAG_ERROR(Err0647, nullptr)
SWAG_ERROR(Err0648, "expected a struct, but `%s` is %s")
SWAG_ERROR(Err0649, nullptr)
SWAG_ERROR(Err0650, nullptr)
SWAG_ERROR(Err0651, nullptr)
SWAG_ERROR(Err0652, "the function `%s` has an incorrect signature for interface `%s`")
SWAG_ERROR(Err0653, "should be")
SWAG_ERROR(Err0654, "expected `self` as a first parameter for the interface function `%s`")
SWAG_ERROR(Err0655, "unexpected type for the first parameter of interface function implementation (`self` expected, `%s` provided)")
SWAG_ERROR(Err0656, nullptr)
SWAG_ERROR(Err0657, "some functions of the interface `%s` are not implemented")
SWAG_ERROR(Err0658, nullptr)
SWAG_ERROR(Err0659, "the implementation block for `%s` is private but the corresponding identifier is not")
SWAG_ERROR(Err0660, "the implementation block for `%s` is not private but the corresponding identifier is")
SWAG_ERROR(Err0661, "the implementation block is not defined in the same scope as `%s` (`impl` parent scope is `%s`, `%s` parent scope is `%s`)")
SWAG_ERROR(Err0662, "expected a struct or an enum, but `%s` is %s")
SWAG_ERROR(Err0663, nullptr)
SWAG_ERROR(Err0664, "unsupported alias as an implementation block name")
SWAG_ERROR(Err0665, "the expose attribute `%s` should only be used in a global scope")
SWAG_ERROR(Err0666, "the struct cannot be marked with `Swag.Opaque` because it is not public")
SWAG_ERROR(Err0667, "the struct cannot be marked with `Swag.Opaque` because the whole file is exported (`#global export`)")
SWAG_ERROR(Err0668, "`using` is not possible on a constant")
SWAG_ERROR(Err0669, "`using` on a field is only valid for a struct type (`%s` provided)")
SWAG_ERROR(Err0670, "the initialization expression cannot be evaluated at compile time")
SWAG_ERROR(Err0671, "the type `%s` is generic, but struct `%s` does not declare generic parameters")
SWAG_ERROR(Err0672, "cannot resolve the struct `%s` because the type `%s` is generic")
SWAG_ERROR(Err0673, "cannot find the struct member `%s` to compute the relocation (`Swag.Offset` attribute)")
SWAG_ERROR(Err0674, "invalid struct member name `%s`")
SWAG_ERROR(Err0675, "an embedded struct (`%s`) cannot be public")
SWAG_ERROR(Err0676, "an interface can only contain members of type `lambda` (`%s` provided)")
SWAG_ERROR(Err0677, "expected at least one parameter for the interface member `%s` (`self` is expected as a first parameter)")
SWAG_ERROR(Err0678, nullptr)
SWAG_ERROR(Err0679, "unexpected type for the first parameter of interface member (`self` expected, `%s` provided)")
SWAG_ERROR(Err0680, "cannot initialize an interface member")
SWAG_ERROR(Err0681, "cannot resolve the interface because the type `%s` is generic")
SWAG_ERROR(Err0682, "an interface member cannot be relocated with `Swag.Offset`")
SWAG_ERROR(Err0683, "the interface `%s` is empty")
SWAG_ERROR(Err0684, "an embedded interface (`%s`) cannot be public")
SWAG_ERROR(Err0685, nullptr)
SWAG_ERROR(Err0686, nullptr)
SWAG_ERROR(Err0687, nullptr)
SWAG_ERROR(Err0688, nullptr)
SWAG_ERROR(Err0689, "`using` on a variable should not be used in `%s` scope")
SWAG_ERROR(Err0690, nullptr)
SWAG_ERROR(Err0691, "`using` is not possible on an enum variable")
SWAG_ERROR(Err0692, "`using` is not possible on a variable of type `%s`")
SWAG_ERROR(Err0693, nullptr)
SWAG_ERROR(Err0694, "unexpected `using` type")
SWAG_ERROR(Err0695, "`using` is not possible on type `%s` (expected a namespace, a struct, an enum or a variable)")
SWAG_ERROR(Err0696, nullptr)
SWAG_ERROR(Err0697, "unexpected type `%s` for an enum marked with `Swag.EnumFlags` (should be an unsigned integer)")
SWAG_ERROR(Err0698, "unexpected type `%s` for an enum marked with `Swag.EnumIndex` (should be an integer)")
SWAG_ERROR(Err0699, "the dimension of the enum array type should be specified (type is `%s`)")
SWAG_ERROR(Err0700, "the enum array type `%s` should be `const`")
SWAG_ERROR(Err0701, "the enum slice type `%s` should be `const`")
SWAG_ERROR(Err0702, "expected an enum type, found `%s`")
SWAG_ERROR(Err0703, "`with` should not be used on type `%s` (expected a namespace, an enum or a struct)")
SWAG_ERROR(Err0704, nullptr)
SWAG_ERROR(Err0705, nullptr)
SWAG_ERROR(Err0706, "the enum value `%s` of type `%s` should be initialized")
SWAG_ERROR(Err0707, nullptr)
SWAG_ERROR(Err0708, "the enum value `%s` is out of range of `u8`")
SWAG_ERROR(Err0709, "cannot deduce the flag value of `%s` because the previous value is not power of two")
SWAG_ERROR(Err0710, "the enum value `%s` is out of range of `u16`")
SWAG_ERROR(Err0711, nullptr)
SWAG_ERROR(Err0712, "the enum value `%s` is out of range of `u32`")
SWAG_ERROR(Err0713, nullptr)
SWAG_ERROR(Err0714, "the enum value `%s` is out of range of `u64`")
SWAG_ERROR(Err0715, nullptr)
SWAG_ERROR(Err0716, "the enum value `%s` is out of range of `s8`")
SWAG_ERROR(Err0717, "the enum value `%s` is out of range of `s16`")
SWAG_ERROR(Err0718, "the enum value `%s` is out of range of `s32`")
SWAG_ERROR(Err0719, "the enum value `%s` is out of range of `s64`")
SWAG_ERROR(Err0720, "command line error: invalid argument `%s`")
SWAG_ERROR(Err0721, nullptr)
SWAG_ERROR(Err0722, "command line error: argument `%s` should be followed by `%s`")
SWAG_ERROR(Err0723, nullptr)
SWAG_ERROR(Err0724, "command line error: argument `%s` should be followed by `true` or `false` (`%s`)")
SWAG_ERROR(Err0725, "command line error: argument `%s` should be followed by a string")
SWAG_ERROR(Err0726, "unexpected `->` in attribute declaration")
SWAG_ERROR(Err0727, "command line error: argument `%s` should be followed by an integer value")
SWAG_ERROR(Err0728, "command line error: argument `%s` should be followed by an integer value (`%s`)")
SWAG_ERROR(Err0729, "the type `code` is only valid in a `Swag.Macro` or `Swag.Mixin` function")
SWAG_ERROR(Err0730, nullptr)
SWAG_ERROR(Err0731, "unexpected type `%s` for attribute parameter")
SWAG_ERROR(Err0732, "unexpected function return type `void`, this is not necessary")
SWAG_ERROR(Err0733, "the inline function has variadic arguments, this is not yet supported")
SWAG_ERROR(Err0734, "a variadic parameter should be the last one")
SWAG_ERROR(Err0735, "the type `cvarargs` should only be used for a function parameter")
SWAG_ERROR(Err0736, "the type `code` should only be used for a function parameter")
SWAG_ERROR(Err0737, "compiler instruction `%s` is invalid as a default parameter value")
SWAG_ERROR(Err0738, "%s should have a default value because some arguments before have one")
SWAG_ERROR(Err0739, "the `#main` function has already been defined")
SWAG_ERROR(Err0740, "the affectation is not allowed because the function argument `%s` is immutable (`const`)")
SWAG_ERROR(Err0741, "some `@alias` names in the function `%s` are not contiguous (missing `@alias%u`)")
SWAG_ERROR(Err0742, "a function with the `Swag.Foreign` attribute cannot have a body")
SWAG_ERROR(Err0743, "compiler special function cannot have the `Swag.Inline` attribute")
SWAG_ERROR(Err0744, "`#test` functions should only be used in a test module (in the `./tests` folder of the workspace)")
SWAG_ERROR(Err0745, "a function with the `Swag.Test` attribute cannot have a return value")
SWAG_ERROR(Err0746, "a function with the `Swag.Test` attribute cannot have parameters")
SWAG_ERROR(Err0747, "%s cannot be public")
SWAG_ERROR(Err0748, "not all control paths of %s return a value")
SWAG_ERROR(Err0749, "the %s returns a type `%s`, but the body is missing a `return`")
SWAG_ERROR(Err0750, "a `#message` function should have a parameter of type `Swag.CompilerMsgMask`")
SWAG_ERROR(Err0751, "the function `%s` has the `Swag.NotGeneric` attribute but seems to be generic")
SWAG_ERROR(Err0752, "the function `%s` cannot have generic parameters because it is flagged with the `Swag.NotGeneric` attribute")
SWAG_ERROR(Err0753, "the function `%s` cannot have the `Swag.Complete` attribute, this is reserved for `opAffect` or `opAffectSuffix`")
SWAG_ERROR(Err0754, "the function `%s` cannot have the `Swag.Implicit` attribute, this is reserved for `opAffect`, `opAffectSuffix` and `opCast`")
SWAG_ERROR(Err0755, "%s cannot have the `Swag.NoReturn` attribute without `Swag.Macro` or `Swag.Mixin`")
SWAG_ERROR(Err0756, "%s cannot have the `Swag.Implicit` attribute because it is generic")
SWAG_ERROR(Err0757, "%s is marked with `Swag.Macro` and `Swag.Inline` attributes at the same time")
SWAG_ERROR(Err0758, "%s is marked with `Swag.Macro` and `Swag.Mixin` attributes at the same time")
SWAG_ERROR(Err0759, "%s is marked with `Swag.Mixin` and `Swag.Inline` attributes at the same time")
SWAG_ERROR(Err0760, "%s is marked with `Swag.Mixin` and `Swag.Macro` attributes at the same time")
SWAG_ERROR(Err0761, "a %s cannot be marked with the `Swag.Macro` attribute")
SWAG_ERROR(Err0762, "a %s cannot be marked with the `Swag.Mixin` attribute")
SWAG_ERROR(Err0763, "a %s cannot be marked with the `Swag.Inline` attribute")
SWAG_ERROR(Err0764, "a function cannot return a value of type `%s`")
SWAG_ERROR(Err0765, "the struct `%s` has the `Swag.NoCopy` attribute, so `opPostCopy` is irrelevant")
SWAG_ERROR(Err0766, "the function cannot have a return type because it is flagged with the `Swag.NoReturn` attribute")
SWAG_ERROR(Err0767, "the function `%s` cannot have the `Swag.Discardable` attribute because it returns nothing")
SWAG_ERROR(Err0768, "unreachable code")
SWAG_ERROR(Err0769, "the `retval` type should only be used in a function body")
SWAG_ERROR(Err0770, "the return type has already been deduced to be `%s` (and `%s` is provided)")
SWAG_ERROR(Err0771, "the `retval` type should not be used in a function that returns nothing")
SWAG_ERROR(Err0772, "expected an expression of type `%s` after `return`")
SWAG_ERROR(Err0773, "the return type has already been deduced to be nothing")
SWAG_ERROR(Err0774, "returning a value of type `%s`, but the %s returns nothing")
SWAG_ERROR(Err0775, "cannot expand `%s` because this is recursive")
SWAG_ERROR(Err0776, nullptr)
SWAG_ERROR(Err0777, nullptr)
SWAG_ERROR(Err0778, nullptr)
SWAG_ERROR(Err0779, "expected a return value because the return type has already been deduced to be `%s`")
SWAG_ERROR(Err0780, "the alias name `%s` is unused and should be removed")
SWAG_ERROR(Err0781, "cannot expand `%s` in global scope because it contains sub declarations, this is not (yet?) supported")
SWAG_ERROR(Err0782, "`@mkforeign` should have a lambda type as a first parameter")
SWAG_ERROR(Err0783, "`@mkforeign` should have a `const *void` as a second parameter")
SWAG_ERROR(Err0784, "`@mkcallback` should have a lambda value as a first parameter")
SWAG_ERROR(Err0785, "`@mkcallback` should not be used with a function with more than `%d` parameters (`%d` provided)")
SWAG_ERROR(Err0786, "`@mkcallback` should not be used with a function that returns type `%s` (only simple types are supported)")
SWAG_ERROR(Err0787, "`%s` should have a pointer as a first parameter")
SWAG_ERROR(Err0788, "`%s` cannot have `null` as a first parameter")
SWAG_ERROR(Err0789, "`@mkany` should have a pointer as a first parameter")
SWAG_ERROR(Err0790, "`@mkany` cannot have `null` as a first parameter")
SWAG_ERROR(Err0791, "the pointer to the value and the type are not related (the first parameter is a pointer to `%s` but the second parameter is of type `%s`)")
SWAG_ERROR(Err0792, "`@mkany` should have a `typeinfo` or a type value as a second parameter (`%s` provided)")
SWAG_ERROR(Err0793, "`@mkinterface` should have a one dimension pointer or a struct as a first parameter")
SWAG_ERROR(Err0794, "`@mkinterface` should have a typeinfo as a second parameter")
SWAG_ERROR(Err0795, "`@mkinterface` should have an interface as a third parameter")
SWAG_ERROR(Err0796, "`@dataof` should not be used on a tuple type")
SWAG_ERROR(Err0797, "`@dataof` should not be applied to expression of type `%s`")
SWAG_ERROR(Err0798, "the expression cannot be evaluated at compile time")
SWAG_ERROR(Err0799, "unsupported `@stringof` expression")
SWAG_ERROR(Err0800, "`@countof` should not be used on a tuple type")
SWAG_ERROR(Err0801, "`@countof` should not be used on type `%s`")
SWAG_ERROR(Err0802, "constant value should be unsigned, but is `%d`")
SWAG_ERROR(Err0803, "unsupported `@nameof` expression")
SWAG_ERROR(Err0804, "a `#message` function should have a parameter of type `Swag.CompilerMsgMask` (`%s` provided)")
SWAG_ERROR(Err0805, "constant value should be unsigned, but is `%I64d`")
SWAG_ERROR(Err0806, "`@spread` can only be called as a function parameter")
SWAG_ERROR(Err0807, "an expression of type `%s` cannot be spreaded")
SWAG_ERROR(Err0808, "cannot instantiate generic %s `%s` with an untyped value (you need to cast to a sized type)")
SWAG_ERROR(Err0809, nullptr)
SWAG_ERROR(Err0810, "the type cannot be evaluated in that context because it is generic")
SWAG_ERROR(Err0811, "`Swag.Foreign` module name should not be empty")
SWAG_ERROR(Err0812, "the size cannot be computed because the expression is generic")
SWAG_ERROR(Err0813, "`Swag.Foreign` module name should not have a file extension starting with `.`")
SWAG_ERROR(Err0814, "the alignement cannot be computed because the expression is generic")
SWAG_ERROR(Err0815, "unexpected usage of %s (`%s`) as a generic argument")
SWAG_ERROR(Err0816, "'.' in a 'with' statement should be followed by an identifier")
SWAG_ERROR(Err0817, "fatal error: workspace folder `%s` already exists")
SWAG_ERROR(Err0818, "fatal error: cannot create directory `%s`")
SWAG_ERROR(Err0819, "cannot alias a pointer or an array reference")
SWAG_ERROR(Err0820, "the enum `%s` is already defined")
SWAG_ERROR(Err0821, "cannot unpack the variable `%s` from the struct `%s` because there`s no corresponding member")
SWAG_ERROR(Err0822, "`using` on a variable with a pointer type is only possible for a pointer to a struct (and type is `%s`)")
SWAG_ERROR(Err0823, "the `case` statement is empty, you should add a `break`")
SWAG_ERROR(Err0824, "fatal error: cannot create file `%s`")
SWAG_ERROR(Err0825, "expected `,` or `]`, found `%s`")
SWAG_ERROR(Err0826, "unexpected `[` when accessing an array with multiple dimensions")
SWAG_ERROR(Err0827, "unexpected negation of an unsigned type (`%s`)")
SWAG_ERROR(Err0828, "the minus operation is not allowed on type `%s`")
SWAG_ERROR(Err0829, "cannot negate number `%d` because `%u` is not in the range of `s8`")
SWAG_ERROR(Err0830, "cannot negate number `%d` because `%u` is not in the range of `s16`")
SWAG_ERROR(Err0831, "cannot negate number `%d` because `%u` is not in the range of `s32`")
SWAG_ERROR(Err0832, "cannot negate number `%I64d` because `%I64u` is not in the range of `s64`")
SWAG_ERROR(Err0833, "a bit inversion operation is not allowed on type `%s`")
SWAG_ERROR(Err0834, "%s size overflow")
SWAG_ERROR(Err0835, "expected an identifier, found symbol `%s`")
SWAG_ERROR(Err0836, "usage of '.' in a statement is only valid inside a `with` block")
SWAG_ERROR(Err0837, "unexpected symbol `%s` after the %s")
SWAG_ERROR(Err0838, "type `Self` should not be used outside an `impl`, `struct` or `interface` block")
SWAG_ERROR(Err0839, "unexpected symbol `%s` in a type declaration")
SWAG_ERROR(Err0840, "the array size should be defined before the type name")
SWAG_ERROR(Err0841, "unexpected token `%s` after `discard`")
SWAG_ERROR(Err0842, "`%s` should only be used inside a function")
SWAG_ERROR(Err0843, "unexpected `try` inside `%s` expression")
SWAG_ERROR(Err0844, "unexpected `catch` inside `%s` expression")
SWAG_ERROR(Err0845, "unexpected `assume` inside `%s` expression")
SWAG_ERROR(Err0846, "unexpected `throw` inside `%s` expression")
SWAG_ERROR(Err0847, "`discard try/assume/catch` cannot be followed by a block")
SWAG_ERROR(Err0848, "`catch` should only be used inside a function")
SWAG_ERROR(Err0849, "expected an identifier")
SWAG_ERROR(Err0850, "expected an identifier, found '%s'")
SWAG_ERROR(Err0851, "generating an `impl` block is only possible in a `#message` with `Swag.CompilerMsgMask.AttributeGen`")
SWAG_ERROR(Err0852, "`AttributeUsage.KindMsgGen` can only be used with `AttributeUsage.Struct` or `AttributeUsage.Enum`")
SWAG_ERROR(Err0853, "`%s` should be immediatly followed by an identifier")
SWAG_ERROR(Err0854, "`throw` should only be used inside a function")
SWAG_ERROR(Err0855, "unexpected comma, expecting `)` or another function parameter")
SWAG_ERROR(Err0856, "unexpected comma, expecting `)` or another function argument")
SWAG_ERROR(Err0857, "unexpected end of file found in the string literal")
SWAG_ERROR(Err0858, "`%s` should not be followed by a line break %s")
SWAG_ERROR(Err0859, "`compileString` cannot be executed in the current context (this is too late)")
SWAG_ERROR(Err0860, "a %s cannot be marked with the `Swag.NotGeneric` attribute")
SWAG_ERROR(Err0861, "an intrinsic parameter expression cannot be empty")
SWAG_ERROR(Err0862, "the expression is empty")
SWAG_ERROR(Err0863, "expected the `if` boolean expression before `{`")
SWAG_ERROR(Err0864, "expected the `while` boolean expression before `{`")
SWAG_ERROR(Err0865, "expected `case` or `default`")
SWAG_ERROR(Err0866, "`default` already defined")
SWAG_ERROR(Err0867, "expected a `case` expression before `:`")
SWAG_ERROR(Err0868, "expected a `case` expression before `break`")
SWAG_ERROR(Err0869, "the `case` statement is empty, you should add a `break` or a `fallthrough`")
SWAG_ERROR(Err0870, "opVisit special name expected")
SWAG_ERROR(Err0871, "expected the `visit` expression to evaluate before `{`")
SWAG_ERROR(Err0872, "expected another `visit` variable name after `,` and before `:`")
SWAG_ERROR(Err0873, "ufcs on closure is not (yet?) supported")
SWAG_ERROR(Err0874, "expected the `loop` expression to evaluate before `{`")
SWAG_ERROR(Err0875, "cannot capture `%s` because it is a closure")
SWAG_ERROR(Err0876, "invalid label name, you should add `;` or put a valid label identifier")
SWAG_ERROR(Err0877, "invalid label name, identifier expected")
SWAG_ERROR(Err0878, "expected the `#if` expression")
SWAG_ERROR(Err0879, "expected the `#global if` expression")
SWAG_ERROR(Err0880, "no corresponding `}` has been found")
SWAG_ERROR(Err0881, "the identifier `%s` is preceeded with `.` but no corresponding enum or 'with' can be deduced")
SWAG_ERROR(Err0882, "capture size overflow (total size is `%u` bytes but maximum authorized is `%u`)")
SWAG_ERROR(Err0883, "expected the function parameters before `{`")
SWAG_ERROR(Err0884, "cannot capture `%s` because it's not a plain old data struct (the type implements `opDrop`, `opPostCopy` or `opPostMove`)")
SWAG_ERROR(Err0885, "the symbol `%s` is already defined as %s in an accessible scope")
SWAG_ERROR(Err0886, "the symbol `%s` is already defined in an accessible scope")
SWAG_ERROR(Err0887, "cannot capture `%s` because type `%s` is not supported")
SWAG_ERROR(Err0888, "the return value of intrinsic `%s` cannot be discarded")
SWAG_ERROR(Err0889, "cannot initialize a type `%s` with `%s` because no corresponding `opAffectSuffix` function can be found in `%s`")
SWAG_ERROR(Err0890, "the symbol `%s` is already defined as a name alias in an accessible scope")
SWAG_ERROR(Err0891, "invalid `%s`, use `%s` instead to do a logical test")
SWAG_ERROR(Err0892, "unused return value of intrinsic `%s`")
SWAG_ERROR(Err0893, "generic symbol `%s` is already declared in a top level context")
SWAG_ERROR(Err0894, "`mtd` or `mtdc` can only be used in a struct or interface context")
SWAG_ERROR(Err0895, "expected a top level instruction")
SWAG_ERROR(Err0896, "expected an embedded instruction or a curly block")
SWAG_ERROR(Err0897, "expected a left expression")
SWAG_ERROR(Err0898, "expected a variable declaration")
SWAG_ERROR(Err0899, "expected an expression")
SWAG_ERROR(Err0905, "unexpected end of line found in the string literal")
SWAG_ERROR(Err0906, "the initialization value cannot be evaluated at compile time because `opAffect` is not `Swag.ConstExpr`")
SWAG_ERROR(Err0907, "cannot cast from type `%s` to a pointer type (only type `uint` is accepted)")
SWAG_ERROR(Err0908, "cannot initialize a type `%s` with `%s` because no corresponding `opAffect` function can be found in `%s`")
SWAG_ERROR(Err0909, "the type `%s` should not be used in an union because it contains `opPostCopy` (or one of its members does)")
SWAG_ERROR(Err0910, "the type `%s` should not be used in an union because it contains `opPostMove` (or one of its members does)")
SWAG_ERROR(Err0911, "the type `%s` should not be used in an union because it contains `opDrop` (or one of its members does)")
SWAG_ERROR(Err0912, "expected `:` after the variable name `%s`, found a literal")