SWAG_ERROR(Hlp0000, "an attribute declaration should not have a return value starting with `->`")
SWAG_ERROR(Hlp0001, "an attribute declaration cannot be marked with `throw`")
SWAG_ERROR(Hlp0002, "is there a missing `self` ?")
SWAG_ERROR(Hlp0003, "you can affect a lambda to a closure type, but not the other way around")
SWAG_ERROR(Hlp0004, "if you want to declare a lambda, you should use `func(` or `closure(`")
SWAG_ERROR(Hlp0005, "if you want to dereference variable `%s` like in C, use `dref %s`")
SWAG_ERROR(Hlp0006, "to access an array with multiple dimensions, the syntax is [x, y], not [x][y]")
SWAG_ERROR(Hlp0007, "methods (`mtd` and `mtdc`) are reserved for structs and interfaces")
SWAG_ERROR(Hlp0008, "a function name starting with `@` is reserved for intrinsics")
SWAG_ERROR(Hlp0009, "a struct member name starting with `item` is reserved by the language")
SWAG_ERROR(Hlp0010, "`@alias` should only be used inside a `Swag.Macro` or a `Swag.Mixin` function")
SWAG_ERROR(Hlp0011, "valid safety values are `boundcheck`, `overflow`, `math`, `switch` and `cast`")
SWAG_ERROR(Hlp0012, "`Swag.Optim` valid values are `bytecode` and `backend`")
SWAG_ERROR(Hlp0013, "`Swag.ExportType` valid values are `methods` and `nozero`")
SWAG_ERROR(Hlp0014, "a function name starting with `op` and followed by a letter in upper case is reserved for struct special functions")
SWAG_ERROR(Hlp0015, "a struct special function should be defined in a corresponding `impl` scope")
SWAG_ERROR(Hlp0016, "all function parameters are immutable and cannot be changed")
SWAG_ERROR(Hlp0017, "a closure can only be defined in a function")
SWAG_ERROR(Hlp0018, "when the parameter types of a lambda are inferred, the return type will be inferred too")
SWAG_ERROR(Hlp0019, "you cannot mix inferred and specified types in lambda parameters")
SWAG_ERROR(Hlp0020, "`@mixin` should only be used inside a `Swag.Mixin` function")
SWAG_ERROR(Hlp0021, "a generic argument must be either a value or a type")
SWAG_ERROR(Hlp0022, "this kind of constant does not have an associated memory storage")
SWAG_ERROR(Hlp0023, "valid modes are `defer(err)` and `defer(noerr)`")
SWAG_ERROR(Hlp0024, "to declare a multi dimensional array, syntax is [N1, N2, ...] and not [N1][N2][...]")
SWAG_ERROR(Hlp0025, "you cannot declare a slice or a static array of another slice or array")
SWAG_ERROR(Hlp0026, "a public struct should export all its special functions")
SWAG_ERROR(Hlp0027, "a private struct should not export its special functions")
SWAG_ERROR(Hlp0028, "is there a missing `using` before `self` ?")
SWAG_ERROR(Hlp0029, "you can use `mtd` or `mtdc` instead of `func` to declare an implicit `using self` as a first parameter")
SWAG_ERROR(Hlp0030, "if you want an infinite loop, use `loop { ... }` instead")