SWAG_ERROR(Msg0488, "%s '%s' cannot be dereferenced like a pointer")
SWAG_ERROR(Msg0013, "%s '%s' cannot be referenced in that context because it's not a value")
SWAG_ERROR(Msg0097, "%s '%s' has not been used as the first parameter to call '%s'")
SWAG_ERROR(Msg0083, "%s '%s' is deprecated")
SWAG_ERROR(Msg0420, "%s '%s' is waiting for ")
SWAG_ERROR(Msg0421, "%s '%s' to be solved")
SWAG_ERROR(Msg0747, "%s cannot be public")
SWAG_ERROR(Msg0756, "%s cannot have the 'Swag.Implicit' attribute because it's generic")
SWAG_ERROR(Msg0755, "%s cannot have the 'Swag.NoReturn' attribute without 'Swag.Macro' or 'Swag.Mixin'")
SWAG_ERROR(Msg0749, "%s has a return type '%s', but the body is missing a 'return'")
SWAG_ERROR(Msg0757, "%s is marked with 'Swag.Macro' and 'Swag.Inline' attributes at the same time")
SWAG_ERROR(Msg0758, "%s is marked with 'Swag.Macro' and 'Swag.Mixin' attributes at the same time")
SWAG_ERROR(Msg0759, "%s is marked with 'Swag.Mixin' and 'Swag.Inline' attributes at the same time")
SWAG_ERROR(Msg0760, "%s is marked with 'Swag.Mixin' and 'Swag.Macro' attributes at the same time")
SWAG_ERROR(Msg0088, "%s is not declared with the 'Swag.Mixin' attribute, and this is mandatory for a function call at global scope")
SWAG_ERROR(Msg0505, "%s overflow, maximum size is 0x%I64x bytes")
SWAG_ERROR(Msg0606, "%s should return a value")
SWAG_ERROR(Msg0834, "%s size overflow")
SWAG_ERROR(Msg0237, "'#assert' message string cannot be evaluated at compile time")
SWAG_ERROR(Msg0234, "'#ast' expression is not 'string' ('%s' provided)")
SWAG_ERROR(Msg0255, "'#callerfunction' can only be set in a function parameter declaration")
SWAG_ERROR(Msg0254, "'#callerlocation' can only be set in a function parameter declaration")
SWAG_ERROR(Msg0750, "'#compiler' function should have a parameter of type 'Swag.CompilerMsgMask'")
SWAG_ERROR(Msg0268, "'#dependencies' can only be declared at the file level")
SWAG_ERROR(Msg0232, "'#dependencies' can only be used in the module configuration file ('module.swg')")
SWAG_ERROR(Msg0256, "'#function' can only be used inside a function")
SWAG_ERROR(Msg0283, "'#gettag' default value expected, found a type")
SWAG_ERROR(Msg0245, "'#gettag' name expected, found a type")
SWAG_ERROR(Msg0250, "'#gettag' name value cannot be evaluated at compile time")
SWAG_ERROR(Msg0251, "'#gettag' parameter should be a string, but is '%s'")
SWAG_ERROR(Msg0370, "'#global export' already defined")
SWAG_ERROR(Msg0371, "'#global foreignlib' should be followed by a string")
SWAG_ERROR(Msg0374, "'#global testerror' is invalid outside a test module (in the './tests' folder of the workspace)")
SWAG_ERROR(Msg0375, "'#global testwarning' is invalid outside a test module (in the './tests' folder of the workspace)")
SWAG_ERROR(Msg0369, "'#global' should be defined first, at the top of the file")
SWAG_ERROR(Msg0376, "'#global' unexpected instruction '%s'")
SWAG_ERROR(Msg0248, "'#hastag' name cannot be evaluated at compile time")
SWAG_ERROR(Msg0249, "'#hastag' parameter should be a string ('%s' provided)")
SWAG_ERROR(Msg0378, "'#import' can only be declared at the top level scope")
SWAG_ERROR(Msg0377, "'#import' can only be used in the module configuration file ('module.swg')")
SWAG_ERROR(Msg0235, "'#import' can only be used inside a '#dependencies' block")
SWAG_ERROR(Msg0336, "'#import' has a specific build number ('%d') but undefined revision ('?')")
SWAG_ERROR(Msg0335, "'#import' has a specific revision ('%d') but undefined major version ('?')")
SWAG_ERROR(Msg0284, "'#import' location already defined as '%s'")
SWAG_ERROR(Msg0380, "'#import' location defined twice")
SWAG_ERROR(Msg0379, "'#import' should be followed by a string")
SWAG_ERROR(Msg0286, "'#import' version already defined as '%s'")
SWAG_ERROR(Msg0382, "'#import' version defined twice")
SWAG_ERROR(Msg0288, "'#import' version invalid format")
SWAG_ERROR(Msg0243, "'#load' parameter should be of type string ('%s' provided)")
SWAG_ERROR(Msg0239, "'#macro' can only be used inside a 'Swag.Macro' function")
SWAG_ERROR(Msg0739, "'#main' function already defined once")
SWAG_ERROR(Msg0366, "'#mixin' empty replacement block")
SWAG_ERROR(Msg0365, "'#mixin' invalid replacement '%s'")
SWAG_ERROR(Msg0364, "'#mixin' replacement block can only be used inside a breakable statement ('loop', 'visit', 'for' ...)")
SWAG_ERROR(Msg0384, "'#placeholder' can only be declared in a top level scope")
SWAG_ERROR(Msg0385, "'#placeholder' should be followed by an identifier")
SWAG_ERROR(Msg0233, "'#selectif' expression is not 'bool' ('%s' provided)")
SWAG_ERROR(Msg0368, "'#semerror' cannot be in a '#if' block")
SWAG_ERROR(Msg0241, "'#semerror' has not triggered an error")
SWAG_ERROR(Msg0367, "'#semerror' is invalid outside a test module (in the './tests' folder of the workspace)")
SWAG_ERROR(Msg0744, "'#test' functions can only be used in a test module (in the './tests' folder of the workspace)")
SWAG_ERROR(Msg0908, "'%s = %s' is impossible because no corresponding 'opAffect' function cannot be found in '%s'")
SWAG_ERROR(Msg0350, "'%s' attribute cannot be used in a file marked with '#global export', because the whole file is implicitly public")
SWAG_ERROR(Msg0535, "'%s' can only be used before a function call that can raise errors (function marked with 'throw')")
SWAG_ERROR(Msg0139, "'%s' can only be used before a function call, and '%s' is %s")
SWAG_ERROR(Msg0138, "'%s' can only be used inside a function marked with 'throw', and '%s' is not")
SWAG_ERROR(Msg0842, "'%s' can only be used inside a function")
SWAG_ERROR(Msg0089, "'%s' cannot be evaluated at compile time")
SWAG_ERROR(Msg0137, "'%s' cannot be used inside a struct special function")
SWAG_ERROR(Msg0788, "'%s' cannot have 'null' as first parameter")
SWAG_ERROR(Msg0498, "'%s' count parameter should be an integer, but is '%s'")
SWAG_ERROR(Msg0495, "'%s' first parameter should be a pointer, but is '%s'")
SWAG_ERROR(Msg0570, "'%s' operation not allowed on type 'any'")
SWAG_ERROR(Msg0497, "'%s' second parameter should be a pointer to type '%s', but points to '%s'")
SWAG_ERROR(Msg0496, "'%s' second parameter should be a pointer, but is '%s'")
SWAG_ERROR(Msg0853, "'%s' should be immediatly followed by an identifier")
SWAG_ERROR(Msg0787, "'%s' should have a pointer as a first parameter")
SWAG_ERROR(Msg0858, "'%s' should not be followed by a line break %s")
SWAG_ERROR(Msg0225, "'%s[index] = %s' is impossible because special function 'opIndexAffect' cannot be found in '%s'")
SWAG_ERROR(Msg0427, "'@acos' called with invalid value '%.3f'")
SWAG_ERROR(Msg0741, "'@alias' names are not all contiguous in function '%s' (missing '@alias%u')")
SWAG_ERROR(Msg0275, "'@alias' special variable name should be followed by a number")
SWAG_ERROR(Msg0426, "'@asin' called with invalid value '%.3f'")
SWAG_ERROR(Msg0800, "'@countof' cannot be used on a tuple type")
SWAG_ERROR(Msg0801, "'@countof' cannot be used on type '%s'")
SWAG_ERROR(Msg0797, "'@dataof' cannot be applied to expression of type '%s'")
SWAG_ERROR(Msg0796, "'@dataof' cannot be used on a tuple type")
SWAG_ERROR(Msg0630, "'@index' can only be used inside a breakable loop ('visit', 'loop' ...)")
SWAG_ERROR(Msg0490, "'@init' count parameter should be an integer, but is '%s'")
SWAG_ERROR(Msg0489, "'@init' first parameter should be a pointer, but is '%s'")
SWAG_ERROR(Msg0428, "'@log' called with invalid value '%.3f'")
SWAG_ERROR(Msg0424, "'@log10' called with invalid value '%.3f'")
SWAG_ERROR(Msg0423, "'@log2' called with invalid value '%.3f'")
SWAG_ERROR(Msg0790, "'@mkany' cannot have 'null' as first parameter")
SWAG_ERROR(Msg0792, "'@mkany' should have a 'typeinfo' or a type value as a second parameter ('%s' provided)")
SWAG_ERROR(Msg0789, "'@mkany' should have a pointer as a first parameter")
SWAG_ERROR(Msg0784, "'@mkcallback' should have a lambda value as a first parameter")
SWAG_ERROR(Msg0783, "'@mkforeign' should have a 'const *void' as a second parameter")
SWAG_ERROR(Msg0782, "'@mkforeign' should have a lambda type as a first parameter")
SWAG_ERROR(Msg0793, "'@mkinterface' should have a one dimension pointer or a struct as a first parameter")
SWAG_ERROR(Msg0794, "'@mkinterface' should have a typeinfo as a second parameter")
SWAG_ERROR(Msg0795, "'@mkinterface' should have an interface as a third parameter")
SWAG_ERROR(Msg0417, "'@power' called with invalid values '%.3f' and '%.3f'")
SWAG_ERROR(Msg0806, "'@spread' can only be called as a function parameter")
SWAG_ERROR(Msg0425, "'@sqrt' called with invalid value '%.3f'")
SWAG_ERROR(Msg0596, "'Swag.Align' value should be a power of two ('%d' provided)")
SWAG_ERROR(Msg0617, "'Swag.Complete' attribute cannot be used on a switch with type '%s'")
SWAG_ERROR(Msg0599, "'Swag.ExportType' invalid value '%s'")
SWAG_ERROR(Msg0594, "'Swag.Optim' invalid value '%s'")
SWAG_ERROR(Msg0595, "'Swag.Pack' value should be 0 or a power of two ('%d' provided)")
SWAG_ERROR(Msg0593, "'Swag.Safety' invalid value '%s'")
SWAG_ERROR(Msg0028, "'Swag.Strict' attribute can only be used on a type alias")
SWAG_ERROR(Msg0159, "'Swag.Tls' and 'Swag.Compiler' attributes are exclusive")
SWAG_ERROR(Msg0561, "']' should not be followed by a line break when declaring an array type")
SWAG_ERROR(Msg0632, "'break' can only be used inside a breakable block")
SWAG_ERROR(Msg0865, "'case' or 'default' expected")
SWAG_ERROR(Msg0869, "'case' statement is empty, you should add a 'break' or a 'fallthrough'")
SWAG_ERROR(Msg0823, "'case' statement is empty, you should add a 'break'")
SWAG_ERROR(Msg0848, "'catch' can only be used inside a function")
SWAG_ERROR(Msg0637, "'continue' can only be used inside a breakable loop ('for', 'visit', 'loop', 'while' ...)")
SWAG_ERROR(Msg0866, "'default' already defined")
SWAG_ERROR(Msg0616, "'default' is invalid in a switch marked with 'Swag.Complete'")
SWAG_ERROR(Msg0634, "'fallthrough' can only be used inside a 'case' block")
SWAG_ERROR(Msg0633, "'fallthrough' can only be used inside a 'switch' block")
SWAG_ERROR(Msg0635, "'fallthrough' cannot be used in the last 'case' of the switch")
SWAG_ERROR(Msg0438, "'for' is invalid for an enum implementation block")
SWAG_ERROR(Msg0559, "'move' cannot be applied to a constant expression (type is '%s')")
SWAG_ERROR(Msg0075, "'opVisit' should have the 'Swag.Macro' attribute")
SWAG_ERROR(Msg0791, "'pointer to value and type are not related (first parameter is a pointer to type '%s' but second parameter is type '%s')")
SWAG_ERROR(Msg0769, "'retval' type can only be used in a function body")
SWAG_ERROR(Msg0771, "'retval' type cannot be used in a function that returns nothing")
SWAG_ERROR(Msg0560, "'retval' type is invalid for a function return type")
SWAG_ERROR(Msg0334, "'self' can only be used inside a struct or 'impl' block")
SWAG_ERROR(Msg0406, "'self' can only be used inside an 'impl' block")
SWAG_ERROR(Msg0306, "'slice' type should be declared as immutable with 'const', because right expression is const")
SWAG_ERROR(Msg0392, "'swag' namespace is reserved by the compiler")
SWAG_ERROR(Msg0854, "'throw' can only be used inside a function")
SWAG_ERROR(Msg0692, "'using' cannot be used on a variable of type '%s'")
SWAG_ERROR(Msg0691, "'using' cannot be used on an enum variable")
SWAG_ERROR(Msg0695, "'using' cannot be used on type %s")
SWAG_ERROR(Msg0668, "'using' is invalid on a constant")
SWAG_ERROR(Msg0669, "'using' on a field is only valid for a struct type ('%s' provided)")
SWAG_ERROR(Msg0451, "'using' on a member is invalid in an interface definition")
SWAG_ERROR(Msg0689, "'using' on a variable cannot be used in '%s' scope")
SWAG_ERROR(Msg0822, "'using' on a variable with a type pointer can only be used on a pointer to a struct (type is '%s')")
SWAG_ERROR(Msg0453, "'var' is not necessary to declare a field inside a struct")
SWAG_ERROR(Msg0399, "'{' is expected instead of '%s'")
SWAG_ERROR(Msg0903, ", found '%s' ")
SWAG_ERROR(Msg0901, ", found identifier '%s' ")
SWAG_ERROR(Msg0900, ", found symbol '%s' ")
SWAG_ERROR(Msg0902, ", found type '%s' ")
SWAG_ERROR(Msg0904, ") did you miss 'var' or 'const' to declare a global variable ?")
SWAG_ERROR(Msg0215, "[safety] '<<' shift operand value on type '%s' is greater than '%d'")
SWAG_ERROR(Msg0216, "[safety] '>>' shift operand value on type '%s' is greater than '%d'")
SWAG_ERROR(Msg0219, "[safety] '@abs' integer overflow on type '%s'")
SWAG_ERROR(Msg0533, "[safety] '@cstrlen' pointer is null")
SWAG_ERROR(Msg0531, "[safety] '@memcmp' first pointer is null")
SWAG_ERROR(Msg0532, "[safety] '@memcmp' second pointer is null")
SWAG_ERROR(Msg0526, "[safety] '@memcpy' destination pointer is null")
SWAG_ERROR(Msg0527, "[safety] '@memcpy' source pointer is null")
SWAG_ERROR(Msg0528, "[safety] '@memmove' destination pointer is null")
SWAG_ERROR(Msg0529, "[safety] '@memmove' source pointer is null")
SWAG_ERROR(Msg0530, "[safety] '@memset' destination pointer is null")
SWAG_ERROR(Msg0229, "[safety] bad slicing, lower bound is greater than upper bound")
SWAG_ERROR(Msg0230, "[safety] bad slicing, upper bound is out of range")
SWAG_ERROR(Msg0208, "[safety] cast from a negative value of type '%s' to unsigned type '%s'")
SWAG_ERROR(Msg0859, "[safety] dereferencing a null pointer")
SWAG_ERROR(Msg0221, "[safety] division by zero")
SWAG_ERROR(Msg0222, "[safety] index out of range")
SWAG_ERROR(Msg0211, "[safety] integer overflow during '*' operation on type '%s'")
SWAG_ERROR(Msg0214, "[safety] integer overflow during '*=' operation on type '%s'")
SWAG_ERROR(Msg0209, "[safety] integer overflow during '+' operation on type '%s'")
SWAG_ERROR(Msg0212, "[safety] integer overflow during '+=' operation on type '%s'")
SWAG_ERROR(Msg0210, "[safety] integer overflow during '-' operation on type '%s'")
SWAG_ERROR(Msg0213, "[safety] integer overflow during '-=' operation on type '%s'")
SWAG_ERROR(Msg0217, "[safety] integer overflow during '<<' operation on type '%s'")
SWAG_ERROR(Msg0218, "[safety] integer overflow during '>>' operation on type '%s'")
SWAG_ERROR(Msg0220, "[safety] integer overflow when taking the negative value of type '%s'")
SWAG_ERROR(Msg0228, "[safety] invalid dynamic cast, types mismatch")
SWAG_ERROR(Msg0207, "[safety] truncated bits when casting expression from '%s' to '%s'")
SWAG_ERROR(Msg0763, "a %s cannot be marked with 'Swag.Inline' attribute")
SWAG_ERROR(Msg0761, "a %s cannot be marked with 'Swag.Macro' attribute")
SWAG_ERROR(Msg0762, "a %s cannot be marked with 'Swag.Mixin' attribute")
SWAG_ERROR(Msg0512, "a %s cannot be marked with 'Swag.NoReturn' attribute")
SWAG_ERROR(Msg0860, "a %s cannot be marked with 'Swag.NotGeneric' attribute")
SWAG_ERROR(Msg0349, "a %s definition should appear at file or namespace scope")
SWAG_ERROR(Msg0407, "a method can only be declared inside an 'impl' block")
SWAG_ERROR(Msg0301, "affect not allowed from an array")
SWAG_ERROR(Msg0571, "affect not allowed on %s '%s'")
SWAG_ERROR(Msg0572, "affect not allowed, '%s' is %s")
SWAG_ERROR(Msg0566, "affect operation not allowed")
SWAG_ERROR(Msg0564, "affect operation not allowed, left expression is immutable ('const')")
SWAG_ERROR(Msg0567, "affect operation not allowed, left expression is not a variable")
SWAG_ERROR(Msg0565, "affect operation not allowed, left expression is not an l-value")
SWAG_ERROR(Msg0574, "affect to tuple is not possible because right expression is not compatible")
SWAG_ERROR(Msg0027, "alias can only be used with a type or an identifier")
SWAG_ERROR(Msg0030, "alias cannot be used on %s")
SWAG_ERROR(Msg0025, "alias is public but '%s' is not")
SWAG_ERROR(Msg0780, "alias name '%s' is unused and should be removed")
SWAG_ERROR(Msg0814, "alignement cannot be computed because expression is generic")
SWAG_ERROR(Msg0115, "ambiguous resolution of generic %s '%s'")
SWAG_ERROR(Msg0116, "ambiguous resolution of symbol '%s'")
SWAG_ERROR(Msg0277, "an '@alias' number should be in the range [0, 31] ('%u' provided)")
SWAG_ERROR(Msg0310, "an enum variable should be initialized with a valid value or with '?'")
SWAG_ERROR(Msg0247, "an identifier marked with '#scopefct' can only be used inside a function")
SWAG_ERROR(Msg0246, "an identifier marked with '#scopefct' cannot be used in a scope")
SWAG_ERROR(Msg0010, "an interface can only be compared to 'null'")
SWAG_ERROR(Msg0676, "an interface can only contain members of type 'lambda' ('%s' provided)")
SWAG_ERROR(Msg0485, "array access type should be integer, but is '%s'")
SWAG_ERROR(Msg0021, "array dimension cannot be evaluated at compile time")
SWAG_ERROR(Msg0023, "array dimension is 0")
SWAG_ERROR(Msg0022, "array dimension should be integer, but is '%s'")
SWAG_ERROR(Msg0840, "array size should be defined before the type name")
SWAG_ERROR(Msg0293, "attempt to unpack '%u' variables, but '%s' contains only '%u' field(s)")
SWAG_ERROR(Msg0591, "attribute '%s' assigned twice to '%s' ('Swag.AttrMulti' is not present in the declaration of '%s')")
SWAG_ERROR(Msg0583, "attribute '%s' can only be applied to %s")
SWAG_ERROR(Msg0588, "attribute '%s' cannot be applied to %s")
SWAG_ERROR(Msg0586, "attribute '%s' cannot be used in that context")
SWAG_ERROR(Msg0600, "attribute '%s' does not have the 'Swag.AttributeUsage.File' usage, so it cannot be used with '#global'")
SWAG_ERROR(Msg0297, "attribute 'Swag.Discardable' can only be used on a lambda variable (provided type is '%s')")
SWAG_ERROR(Msg0190, "attribute declaration ('attr'), unlike function, cannot be marked with 'throw'")
SWAG_ERROR(Msg0726, "attribute declaration ('attr'), unlike function, should not have a return value starting with '->'")
SWAG_ERROR(Msg0602, "attribute parameter cannot be evaluated at compile time")
SWAG_ERROR(Msg0136, "back ticked identifier can only be used inside a 'Swag.Macro' function or an '#inline' block")
SWAG_ERROR(Msg0135, "backtick can only be used inside an inline/macro block")
SWAG_ERROR(Msg0054, "bad generic parameter '%d' for %s (type expected, value provided)")
SWAG_ERROR(Msg0057, "bad generic parameter '%d' for %s (value expected, type provided)")
SWAG_ERROR(Msg0476, "bad slicing arguments, lower bound '%I64u' is greater than upper bound '%I64u'")
SWAG_ERROR(Msg0477, "bad slicing arguments, upper bound '%I64u' is out of range")
SWAG_ERROR(Msg0655, "bad type for first parameter of interface function implementation ('self' expected, '%s' provided)")
SWAG_ERROR(Msg0679, "bad type for first parameter of interface member ('self' expected, '%s' provided)")
SWAG_ERROR(Msg0070, "bad type of generic parameter '%d' for %s ('%s' expected, '%s' provided)")
SWAG_ERROR(Msg0053, "bad type of parameter '%d' for %s ('%s' expected, '%s' provided)")
SWAG_ERROR(Msg0050, "bad type of parameter '%d' for %s ('%s' is expected for field '%s', '%s' provided)")
SWAG_ERROR(Msg0047, "bad type of parameter '%d' for %s, generic type '%s' is assigned to '%s' ('%s' provided)")
SWAG_ERROR(Msg0833, "bit inversion operation not allowed on type '%s'")
SWAG_ERROR(Msg0434, "bytecode execution, ")
SWAG_ERROR(Msg0015, "bytecode stack overflow (maximum stack size is '--stack-size:%s')")
SWAG_ERROR(Msg0076, "call level limit reached (maximum level is '--max-recurse:%d')")
SWAG_ERROR(Msg0786, "callback return type '%s' not supported")
SWAG_ERROR(Msg0785, "callback type not supported, too many parameters (maximum is '%d')")
SWAG_ERROR(Msg0227, "cannot access '%s' by index because special function 'opIndex' cannot be found in type '%s'")
SWAG_ERROR(Msg0226, "cannot access by index because special function 'opIndex' cannot be found in type '%s'")
SWAG_ERROR(Msg0049, "cannot access environment variable 'PATH'")
SWAG_ERROR(Msg0509, "cannot access file '%s'")
SWAG_ERROR(Msg0051, "cannot add '%s' to the 'PATH' environment variable")
SWAG_ERROR(Msg0569, "cannot affect an expression of type 'void'")
SWAG_ERROR(Msg0819, "cannot alias a pointer or an array reference")
SWAG_ERROR(Msg0029, "cannot alias a struct member")
SWAG_ERROR(Msg0160, "cannot assign a function pointer to a constant")
SWAG_ERROR(Msg0032, "cannot bitcast from type '%s' (should be native integer, char or float)")
SWAG_ERROR(Msg0033, "cannot bitcast to a type with a bigger size ('%s' from '%s')")
SWAG_ERROR(Msg0493, "cannot call '@postcopy' on type '%s' because it is marked with the 'Swag.NoCopy' attribute")
SWAG_ERROR(Msg0105, "cannot call empty function '%s'")
SWAG_ERROR(Msg0200, "cannot cast from '%s' to '%s' because '%s' has multiple fields of type '%s' with 'using'")
SWAG_ERROR(Msg0177, "cannot cast from '%s' to '%s'")
SWAG_ERROR(Msg0418, "cannot cast from immutable type '%s' to mutable '%s'")
SWAG_ERROR(Msg0907, "cannot cast from type '%s' to pointer type; only type 'uint' is accepted")
SWAG_ERROR(Msg0175, "cannot cast implicitly from '%s' to '%s'")
SWAG_ERROR(Msg0203, "cannot cast, not enough initializers ('%d' expected, '%d' provided)")
SWAG_ERROR(Msg0204, "cannot cast, too many initializers ('%d' expected, '%d' provided)")
SWAG_ERROR(Msg0176, "cannot cast, type '%s' does not implement interface '%s'")
SWAG_ERROR(Msg0059, "cannot convert slice of type '%s' to a constant expression")
SWAG_ERROR(Msg0058, "cannot convert type '%s' to a constant expression")
SWAG_ERROR(Msg0537, "cannot convert typeinfo '%s' to runtime typeinfo")
SWAG_ERROR(Msg0045, "cannot create '%s' process (::CreatePipe)")
SWAG_ERROR(Msg0311, "cannot create constant because type '%s' is generic")
SWAG_ERROR(Msg0604, "cannot create directory '%s'")
SWAG_ERROR(Msg0046, "cannot create process '%s'")
SWAG_ERROR(Msg0312, "cannot create variable because type '%s' is generic")
SWAG_ERROR(Msg0351, "cannot declare a %s symbol in a private scope (%s '%s' is private)")
SWAG_ERROR(Msg0279, "cannot decompose a tuple in %s")
SWAG_ERROR(Msg0709, "cannot deduce flag value of '%s' because previous value is not power of two")
SWAG_ERROR(Msg0308, "cannot deduce type from 'null'")
SWAG_ERROR(Msg0603, "cannot delete file '%s'")
SWAG_ERROR(Msg0486, "cannot dereference a 'void' pointer")
SWAG_ERROR(Msg0482, "cannot dereference a tuple type like a pointer or an array")
SWAG_ERROR(Msg0481, "cannot dereference type '%s'")
SWAG_ERROR(Msg0094, "cannot discard a function call that returns nothing")
SWAG_ERROR(Msg0280, "cannot evaluate constant expression of type '%s' at compile time")
SWAG_ERROR(Msg0281, "cannot evaluate constant expression of type '%s' at compile time, because struct is not marked with 'Swag.ConstExpr'")
SWAG_ERROR(Msg0090, "cannot evaluate function parameter at compile time (type is '%s')")
SWAG_ERROR(Msg0321, "cannot evaluate tuple value at compile time because one of its members is not 'Swag.ConstExpr'")
SWAG_ERROR(Msg0810, "cannot evaluate type in that context because it's generic")
SWAG_ERROR(Msg0775, "cannot expand '%s' because this is recursive")
SWAG_ERROR(Msg0781, "cannot expand '%s' in global scope because it contains sub declarations, this is not (yet?) supported")
SWAG_ERROR(Msg0510, "cannot fetch file '%s' for module dependency '%s'")
SWAG_ERROR(Msg0508, "cannot find '%s' in module folder '%s'")
SWAG_ERROR(Msg0244, "cannot find file '%s'")
SWAG_ERROR(Msg0079, "cannot find special function '%s' in '%s'")
SWAG_ERROR(Msg0673, "cannot find struct member '%s' to compute variable relocation ('Swag.Offset' attribute)")
SWAG_ERROR(Msg0680, "cannot initialize an interface member")
SWAG_ERROR(Msg0038, "cannot instantiate generic %s '%s' with an untyped float, you need to specify a type\n")
SWAG_ERROR(Msg0037, "cannot instantiate generic %s '%s' with an untyped integer, you need to specify a type\n")
SWAG_ERROR(Msg0042, "cannot instantiate generic function '%s', missing contextual types replacements")
SWAG_ERROR(Msg0041, "cannot instantiate generic function '%s', missing generic parameters")
SWAG_ERROR(Msg0039, "cannot instantiate generic struct '%s', missing contextual types replacements")
SWAG_ERROR(Msg0043, "cannot instantiate variable because type '%s' is generic")
SWAG_ERROR(Msg0832, "cannot negate number '%I64d' because '%I64u' is not in the range of 's64'")
SWAG_ERROR(Msg0830, "cannot negate number '%d' because '%u' is not in the range of 's16'")
SWAG_ERROR(Msg0831, "cannot negate number '%d' because '%u' is not in the range of 's32'")
SWAG_ERROR(Msg0829, "cannot negate number '%d' because '%u' is not in the range of 's8'")
SWAG_ERROR(Msg0223, "cannot open #load file '%s'")
SWAG_ERROR(Msg0524, "cannot open file '%s' for writing")
SWAG_ERROR(Msg0502, "cannot open file '%s'")
SWAG_ERROR(Msg0108, "cannot reference 'Swag.Test' function '%s' from '%s'")
SWAG_ERROR(Msg0101, "cannot reference 'opDrop' special function (use '@drop' instead)")
SWAG_ERROR(Msg0100, "cannot reference 'opInit' special function (use '@init' instead)")
SWAG_ERROR(Msg0103, "cannot reference 'opPostCopy' special function (use '@postcopy' instead)")
SWAG_ERROR(Msg0104, "cannot reference 'opPostMove' special function (use '@postmove' instead)")
SWAG_ERROR(Msg0060, "cannot reference a compiler constant at runtime")
SWAG_ERROR(Msg0091, "cannot reference compile time %s '%s' (marked with 'Swag.Compiler') from runtime %s")
SWAG_ERROR(Msg0107, "cannot reference compile time function '%s' (marked with 'Swag.Compiler') from runtime function '%s'")
SWAG_ERROR(Msg0206, "cannot reference variable '%s' because it's in another stack frame")
SWAG_ERROR(Msg0682, "cannot relocate an interface member")
SWAG_ERROR(Msg0516, "cannot resolve dependency to module '%s' because of two different major versions ('%d' and '%d')")
SWAG_ERROR(Msg0518, "cannot resolve dependency to module '%s', version '%s' cannot be found at location '%s'")
SWAG_ERROR(Msg0258, "cannot resolve foreign function call to '%s'")
SWAG_ERROR(Msg0133, "cannot resolve identifier '%s'")
SWAG_ERROR(Msg0681, "cannot resolve interface because type '%s' is generic")
SWAG_ERROR(Msg0513, "cannot resolve module dependency '%s' ('location' is empty)")
SWAG_ERROR(Msg0672, "cannot resolve struct '%s' because type '%s' is generic")
SWAG_ERROR(Msg0004, "cannot select function '%s' because '%s' has failed")
SWAG_ERROR(Msg0048, "cannot set environment variable 'SWAG_FOLDER' to '%s'\n")
SWAG_ERROR(Msg0320, "cannot slice '%s' because special function 'opSlice' cannot be found in type '%s'")
SWAG_ERROR(Msg0465, "cannot take address of %s")
SWAG_ERROR(Msg0471, "cannot take address of a macro")
SWAG_ERROR(Msg0472, "cannot take address of a mixin")
SWAG_ERROR(Msg0473, "cannot take address of an inline function")
SWAG_ERROR(Msg0469, "cannot take address of constant")
SWAG_ERROR(Msg0114, "cannot take the address of a function with call parameters")
SWAG_ERROR(Msg0161, "cannot transform type '%s' to a constant array because 'opCount' returns '0'")
SWAG_ERROR(Msg0162, "cannot transform type '%s' to a constant array because 'opSlice' returns an empty slice")
SWAG_ERROR(Msg0292, "cannot unpack '%s' because it does not contain any field")
SWAG_ERROR(Msg0291, "cannot unpack type '%s' (expected a struct)")
SWAG_ERROR(Msg0821, "cannot unpack variable '%s' from struct '%s' because there's no corresponding member")
SWAG_ERROR(Msg0117, "cannot use 'using' on two variables with the same type")
SWAG_ERROR(Msg0337, "cannot use a range in a switch with an expression")
SWAG_ERROR(Msg0332, "cannot use operator 'orelse' on type '%s'")
SWAG_ERROR(Msg0624, "cannot visit a tuple type")
SWAG_ERROR(Msg0627, "cannot visit a variadic type by pointer")
SWAG_ERROR(Msg0636, "cannot visit an enum by pointer")
SWAG_ERROR(Msg0525, "cannot write to file '%s'")
SWAG_ERROR(Msg0722, "command line error: argument '%s' should be followed by '%s'")
SWAG_ERROR(Msg0724, "command line error: argument '%s' should be followed by 'true' or 'false' ('%s')")
SWAG_ERROR(Msg0725, "command line error: argument '%s' should be followed by a string")
SWAG_ERROR(Msg0728, "command line error: argument '%s' should be followed by an integer value ('%s')")
SWAG_ERROR(Msg0727, "command line error: argument '%s' should be followed by an integer value")
SWAG_ERROR(Msg0519, "command line error: invalid --stack-size value (%s), valid range is [%s, %s]")
SWAG_ERROR(Msg0520, "command line error: invalid abi '%s' for x64 backend")
SWAG_ERROR(Msg0523, "command line error: invalid arch '%s' for x64 backend")
SWAG_ERROR(Msg0720, "command line error: invalid argument '%s'")
SWAG_ERROR(Msg0522, "command line error: invalid os '%s' for x64 backend")
SWAG_ERROR(Msg0521, "command line error: invalid vendor '%s' for x64 backend")
SWAG_ERROR(Msg0001, "compare operation not allowed on type '%s'")
SWAG_ERROR(Msg0007, "comparison operations are invalid on tuple types")
SWAG_ERROR(Msg0238, "compiler assertion failed")
SWAG_ERROR(Msg0737, "compiler instruction '%s' is invalid as a default parameter value")
SWAG_ERROR(Msg0743, "compiler special function cannot have the 'Swag.Inline' attribute")
SWAG_ERROR(Msg0405, "const before a function parameter name can only be followed by 'self'")
SWAG_ERROR(Msg0305, "constant should be explicitly initialized")
SWAG_ERROR(Msg0298, "constant should be initialized")
SWAG_ERROR(Msg0805, "constant value should be unsigned, but is '%I64d'")
SWAG_ERROR(Msg0802, "constant value should be unsigned, but is '%d'")
SWAG_ERROR(Msg0231, "copy semantic is forbidden for type '%s' because of 'Swag.NoCopy' attribute")
SWAG_ERROR(Msg0557, "dependency module '%s' cannot be found in that workspace")
SWAG_ERROR(Msg0511, "dependency module folder '%s' does not exist")
SWAG_ERROR(Msg0699, "dimension of enum array type '%s' should be specified")
SWAG_ERROR(Msg0150, "division by zero")
SWAG_ERROR(Msg0129, "during '#checkif' validation of function call")
SWAG_ERROR(Msg0128, "during '#selectif' validation of function call")
SWAG_ERROR(Msg0112, "during generic expansion")
SWAG_ERROR(Msg0118, "during inline expansion")
SWAG_ERROR(Msg0684, "embedded interface '%s' cannot be public")
SWAG_ERROR(Msg0675, "embedded struct '%s' cannot be public")
SWAG_ERROR(Msg0356, "empty attribute")
SWAG_ERROR(Msg0447, "empty tuple definition")
SWAG_ERROR(Msg0820, "enum '%s' already defined")
SWAG_ERROR(Msg0700, "enum array type '%s' should be 'const'")
SWAG_ERROR(Msg0701, "enum slice type '%s' should be 'const'")
SWAG_ERROR(Msg0717, "enum value '%s' is out of range of 's16'")
SWAG_ERROR(Msg0718, "enum value '%s' is out of range of 's32'")
SWAG_ERROR(Msg0719, "enum value '%s' is out of range of 's64'")
SWAG_ERROR(Msg0716, "enum value '%s' is out of range of 's8'")
SWAG_ERROR(Msg0710, "enum value '%s' is out of range of 'u16'")
SWAG_ERROR(Msg0712, "enum value '%s' is out of range of 'u32'")
SWAG_ERROR(Msg0714, "enum value '%s' is out of range of 'u64'")
SWAG_ERROR(Msg0708, "enum value '%s' is out of range of 'u8'")
SWAG_ERROR(Msg0706, "enum value '%s' of type '%s' should be initialized")
SWAG_ERROR(Msg0153, "error reading source file '%s'")
SWAG_ERROR(Msg0036, "error: backend: cannot locate windows sdk folder")
SWAG_ERROR(Msg0102, "evaluation of a function parameter of type '%s' is not supported at compile time")
SWAG_ERROR(Msg0435, "exception during compile time execution !")
SWAG_ERROR(Msg0330, "expected '%s' instead of '%s' %s")
SWAG_ERROR(Msg0825, "expected ',' or ']', found '%s'")
SWAG_ERROR(Msg0455, "expected ':' or '=' in variable declaration, found '%s'")
SWAG_ERROR(Msg0141, "expected '[', '{', '(', '\"' or an intrinsic name, found character '%c'")
SWAG_ERROR(Msg0416, "expected '{' to start the %s body, found ';'")
SWAG_ERROR(Msg0460, "expected a binary digit, found '%s'")
SWAG_ERROR(Msg0622, "expected a constant name, found '%s'")
SWAG_ERROR(Msg0897, "expected a left expression")
SWAG_ERROR(Msg0121, "expected a single identifier %s")
SWAG_ERROR(Msg0444, "expected a struct name, found '%s'")
SWAG_ERROR(Msg0662, "expected a struct or an enum, but '%s' is %s")
SWAG_ERROR(Msg0648, "expected a struct, but '%s' is %s")
SWAG_ERROR(Msg0290, "expected a struct, but symbol '%s' is %s")
SWAG_ERROR(Msg0895, "expected a top level instruction")
SWAG_ERROR(Msg0236, "expected a type 'string' as an '#assert' message ('%s' provided)")
SWAG_ERROR(Msg0343, "expected a type declaration, found '%s'")
SWAG_ERROR(Msg0202, "expected a type inside a tuple type definition, found '%s'")
SWAG_ERROR(Msg0898, "expected a variable declaration")
SWAG_ERROR(Msg0315, "expected a variable name, found '%s'")
SWAG_ERROR(Msg0333, "expected an alias name, found '%s'")
SWAG_ERROR(Msg0355, "expected an attribute name, found '%s'")
SWAG_ERROR(Msg0582, "expected an attribute, but '%s' is %s")
SWAG_ERROR(Msg0896, "expected an embedded instruction or a curly block")
SWAG_ERROR(Msg0396, "expected an enum name, found '%s'")
SWAG_ERROR(Msg0702, "expected an enum type, found '%s'")
SWAG_ERROR(Msg0400, "expected an enum value identifier, found '%s'")
SWAG_ERROR(Msg0899, "expected an expression")
SWAG_ERROR(Msg0012, "expected an expression, found a type")
SWAG_ERROR(Msg0285, "expected an identifier, found a literal")
SWAG_ERROR(Msg0835, "expected an identifier, found symbol '%s'")
SWAG_ERROR(Msg0646, "expected an interface, but '%s' is %s")
SWAG_ERROR(Msg0772, "expected return expression of type '%s' after 'return'")
SWAG_ERROR(Msg0171, "expected the type of the array after dimensions, found '%s'")
SWAG_ERROR(Msg0798, "expression cannot be evaluated at compile time")
SWAG_ERROR(Msg0615, "expression cannot be evaluated at compile time, and switch is 'Swag.Complete'")
SWAG_ERROR(Msg0862, "expression is empty")
SWAG_ERROR(Msg0807, "expression of type '%s' cannot be spreaded")
SWAG_ERROR(Msg0629, "expression of type '%s' cannot be visited with 'visit'")
SWAG_ERROR(Msg0240, "expression should be of type 'code', but is '%s'")
SWAG_ERROR(Msg0257, "failed to load module '%s' while resolving foreign function '%s': %s")
SWAG_ERROR(Msg0052, "failed to start watcher service !")
SWAG_ERROR(Msg0055, "failed to update watcher service !")
SWAG_ERROR(Msg0546, "fatal error: cache directory '%s' does not exist")
SWAG_ERROR(Msg0547, "fatal error: cannot create cache directory '%s'")
SWAG_ERROR(Msg0818, "fatal error: cannot create directory '%s'")
SWAG_ERROR(Msg0824, "fatal error: cannot create file '%s'")
SWAG_ERROR(Msg0543, "fatal error: cannot create public directory '%s'")
SWAG_ERROR(Msg0347, "fatal error: cannot create script file '%s'")
SWAG_ERROR(Msg0545, "fatal error: cannot create target directory '%s'")
SWAG_ERROR(Msg0345, "fatal error: cannot delete directory '%s'")
SWAG_ERROR(Msg0344, "fatal error: cannot delete file '%s'")
SWAG_ERROR(Msg0165, "fatal error: cannot find 'SWAG_FOLDER' in the environment; you must run 'swag env' first at the Swag.exe location to register its path")
SWAG_ERROR(Msg0539, "fatal error: command line --tag '%s' unsupported type '%s'")
SWAG_ERROR(Msg0507, "fatal error: invalid module '%s', configuration file '%s' is missing")
SWAG_ERROR(Msg0319, "fatal error: invalid script file extension; should be '.swgs' instead of '%s'")
SWAG_ERROR(Msg0000, "fatal error: invalid swag command '%s'")
SWAG_ERROR(Msg0538, "fatal error: invalid value '%s' for command line '--tag:%s'; this is not a valid literal")
SWAG_ERROR(Msg0322, "fatal error: invalid value for '--tag:%s' (%s)")
SWAG_ERROR(Msg0542, "fatal error: invalid workspace '%s', subfolder 'modules/' or 'tests/' does not exist")
SWAG_ERROR(Msg0318, "fatal error: missing script file; use '--file:<filename>.swgs' to specify a script to run")
SWAG_ERROR(Msg0540, "fatal error: missing workspace folder '--workspace'")
SWAG_ERROR(Msg0397, "fatal error: module '%s' already exists in the '/modules' folder")
SWAG_ERROR(Msg0014, "fatal error: not enough memory !")
SWAG_ERROR(Msg0166, "fatal error: script file '%s' does not exist")
SWAG_ERROR(Msg0552, "fatal error: some problems have been found in compiler bootstrap !!!")
SWAG_ERROR(Msg0554, "fatal error: some problems have been found in compiler runtime !!!")
SWAG_ERROR(Msg0817, "fatal error: workspace folder '%s' already exists")
SWAG_ERROR(Msg0541, "fatal error: workspace folder '%s' does not exist")
SWAG_ERROR(Msg0120, "field name '%s' cannot be found in tuple")
SWAG_ERROR(Msg0242, "filename cannot be evaluated at compile time")
SWAG_ERROR(Msg0466, "floating point number exponent should have at least one digit")
SWAG_ERROR(Msg0199, "forbidden 'opDrop' special function for '%s' because struct is marked with 'Swag.ConstExpr'")
SWAG_ERROR(Msg0113, "found %d overloads for '%s' but no one could match")
SWAG_ERROR(Msg0325, "found '#elif' without a corresponding '#if'")
SWAG_ERROR(Msg0324, "found '#else' without a corresponding '#if'")
SWAG_ERROR(Msg0326, "found ')' without a corresponding opening '('")
SWAG_ERROR(Msg0328, "found ']' without a corresponding opening '['")
SWAG_ERROR(Msg0323, "found 'else' without a corresponding 'if'")
SWAG_ERROR(Msg0327, "found '}' without a corresponding opening '{'")
SWAG_ERROR(Msg0752, "function '%s' cannot have generic parameters because it is flagged with the 'Swag.NoGeneric' attribute")
SWAG_ERROR(Msg0753, "function '%s' cannot have the 'Swag.Complete' attribute, this is reserved for 'opAffect'")
SWAG_ERROR(Msg0754, "function '%s' cannot have the 'Swag.Implicit' attribute, this is reserved for 'opAffect' and 'opCast'")
SWAG_ERROR(Msg0652, "function '%s' has an incorrect signature for interface '%s'")
SWAG_ERROR(Msg0751, "function '%s' has the 'Swag.NoGeneric' attribute but seems to be generic")
SWAG_ERROR(Msg0098, "function '%s' should be called with '()' and not curlies (this is reserved for struct initialization)")
SWAG_ERROR(Msg0766, "function cannot have a return type because it is flagged with the 'Swag.NoReturn' attribute")
SWAG_ERROR(Msg0767, "function cannot have the 'Swag.Discardable' attribute because it returns 'void'")
SWAG_ERROR(Msg0764, "function cannot return a value of type '%s'")
SWAG_ERROR(Msg0413, "function names starting with '@' are reserved for intrinsics")
SWAG_ERROR(Msg0742, "function with the 'Swag.Foreign' attribute cannot have a body")
SWAG_ERROR(Msg0745, "function with the 'Swag.Test' attribute cannot have a return value")
SWAG_ERROR(Msg0746, "function with the 'Swag.Test' attribute cannot have parameters")
SWAG_ERROR(Msg0386, "global 'using' should be declared at the top of the file")
SWAG_ERROR(Msg0313, "global variable cannot be declared as 'public'")
SWAG_ERROR(Msg0085, "identifier '%s' cannot be dereferenced like a struct (type is '%s')")
SWAG_ERROR(Msg0110, "identifier '%s' cannot be found in %s '%s'")
SWAG_ERROR(Msg0093, "identifier '%s' cannot be found in tuple")
SWAG_ERROR(Msg0127, "identifier '%s' has call parameters, but is %s and not a function")
SWAG_ERROR(Msg0125, "identifier '%s' has call parameters, but is a variable of type '%s' and not a function")
SWAG_ERROR(Msg0893, "identifier '%s' has not been solved")
SWAG_ERROR(Msg0316, "identifier '%s' should be public")
SWAG_ERROR(Msg0272, "identifier '%s' starts with '__', and this is reserved by the language")
SWAG_ERROR(Msg0448, "identifier expected")
SWAG_ERROR(Msg0881, "identifier is preceeded with '.', but no parent scope can be found")
SWAG_ERROR(Msg0201, "if this is a tuple literal and not a type declaration, use '@{' instead of '{'")
SWAG_ERROR(Msg0198, "if this is an array literal and not a type declaration, use '@[' instead of '['")
SWAG_ERROR(Msg0660, "implementation block for '%s' is not private but the corresponding identifier is")
SWAG_ERROR(Msg0659, "implementation block for '%s' is private but the corresponding identifier is not")
SWAG_ERROR(Msg0661, "implementation block is not defined in the same scope as '%s' ('impl' parent scope is '%s', '%s' parent scope is '%s')")
SWAG_ERROR(Msg0441, "implementation block kind (%s) does not match the type of '%s' (%s)")
SWAG_ERROR(Msg0468, "index out of range (index is '%I64u', maximum index is '%I64u')")
SWAG_ERROR(Msg0670, "initialization expression cannot be evaluated at compile time")
SWAG_ERROR(Msg0307, "initialization expression is 'void'")
SWAG_ERROR(Msg0906, "initialization value cannot be evaluated at compile time because 'opAffect' is not 'Swag.ConstExpr'")
SWAG_ERROR(Msg0270, "initializer list is empty")
SWAG_ERROR(Msg0733, "inline function has variadic arguments, this is not yet supported")
SWAG_ERROR(Msg0683, "interface '%s' is empty")
SWAG_ERROR(Msg0861, "intrinsic parameter expression cannot be empty")
SWAG_ERROR(Msg0891, "invalid '%s', use '%s' instead to do a logical test")
SWAG_ERROR(Msg0845, "invalid 'assume' inside '%s' expression")
SWAG_ERROR(Msg0844, "invalid 'catch' inside '%s' expression")
SWAG_ERROR(Msg0514, "invalid 'location' format; should have the form 'location=\"mode@accesspath\"'")
SWAG_ERROR(Msg0515, "invalid 'location' mode; should be 'swag' or 'disk', not '%s'")
SWAG_ERROR(Msg0846, "invalid 'throw' inside '%s' expression")
SWAG_ERROR(Msg0843, "invalid 'try' inside '%s' expression")
SWAG_ERROR(Msg0694, "invalid 'using' type")
SWAG_ERROR(Msg0826, "invalid access to an array with multiple dimensions, syntax is [x, y], not [x][y]")
SWAG_ERROR(Msg0470, "invalid address expression")
SWAG_ERROR(Msg0454, "invalid affect operator '==', did you mean '=' ?")
SWAG_ERROR(Msg0598, "invalid attribute '%s'")
SWAG_ERROR(Msg0597, "invalid attribute usage")
SWAG_ERROR(Msg0031, "invalid bitcast type '%s' (should be native integer, char or float)")
SWAG_ERROR(Msg0081, "invalid character '%s'")
SWAG_ERROR(Msg0267, "invalid compare operator '=', did you mean '==' ?")
SWAG_ERROR(Msg0314, "invalid file format, should be ascii, utf-8 or utf-8-bom")
SWAG_ERROR(Msg0069, "invalid first parameter type for special function '%s' ('%s' expected, '%s' provided)")
SWAG_ERROR(Msg0074, "invalid generic parameter for special function '%s' ('bool' expected, '%s' provided)")
SWAG_ERROR(Msg0072, "invalid generic parameter for special function '%s' ('string' expected, '%s' provided)")
SWAG_ERROR(Msg0130, "invalid generic parameters, identifier '%s' is %s and not a function or a struct")
SWAG_ERROR(Msg0440, "invalid generic parameters, should be naked")
SWAG_ERROR(Msg0463, "invalid hexadecimal digit '%s'")
SWAG_ERROR(Msg0304, "invalid initialization expression for array (expected an array literal or '?')")
SWAG_ERROR(Msg0395, "invalid label identifier '%s'")
SWAG_ERROR(Msg0877, "invalid label name, identifier expected")
SWAG_ERROR(Msg0876, "invalid label name, you should add ';' or put a valid label identifier")
SWAG_ERROR(Msg0124, "invalid lambda call, '%s' is not a variable (it's %s)")
SWAG_ERROR(Msg0467, "invalid literal number prefix '%s'")
SWAG_ERROR(Msg0381, "invalid location '%s'")
SWAG_ERROR(Msg0778, "invalid name alias (should be a single identifier)")
SWAG_ERROR(Msg0777, "invalid name alias (should be an identifier)")
SWAG_ERROR(Msg0776, "invalid name alias")
SWAG_ERROR(Msg0403, "invalid named parameter '%s'")
SWAG_ERROR(Msg0061, "invalid number of arguments for special function '%s' ('%d' expected, '%d' provided)")
SWAG_ERROR(Msg0071, "invalid number of generic parameters for special function '%s'")
SWAG_ERROR(Msg0073, "invalid number of generic parameters for special function '%s'")
SWAG_ERROR(Msg0145, "invalid number syntax, a digit separator '_' cannot be followed by another digit separator")
SWAG_ERROR(Msg0152, "invalid number syntax, a digit separator '_' cannot end a literal number")
SWAG_ERROR(Msg0155, "invalid number syntax, a digit separator '_' cannot start a fractional part")
SWAG_ERROR(Msg0154, "invalid number syntax, a digit separator '_' cannot start a literal number")
SWAG_ERROR(Msg0156, "invalid number syntax, a digit separator '_' cannot start an exponent part")
SWAG_ERROR(Msg0151, "invalid number syntax, missing at least one digit")
SWAG_ERROR(Msg0168, "invalid operation '%s' on a tuple type")
SWAG_ERROR(Msg0573, "invalid operation on a tuple type")
SWAG_ERROR(Msg0264, "invalid operator modifier '%s'")
SWAG_ERROR(Msg0066, "invalid parameter '%d' for special function '%s' ('%s' expected, '%s' provided)")
SWAG_ERROR(Msg0077, "invalid parameter '2' for special function '%s' (cannot be of type '%s')")
SWAG_ERROR(Msg0408, "invalid parameter name '%s'")
SWAG_ERROR(Msg0373, "invalid pass name '%s'")
SWAG_ERROR(Msg0132, "invalid reference to private scope")
SWAG_ERROR(Msg0065, "invalid return type for special function '%s' ('%s' expected, '%s' provided)")
SWAG_ERROR(Msg0276, "invalid special variable name '%s', '@alias' should be followed by a number ('%s' provided)")
SWAG_ERROR(Msg0609, "invalid switch type '%s'")
SWAG_ERROR(Msg0608, "invalid switch type 'any', you need to cast to a concrete type")
SWAG_ERROR(Msg0841, "invalid token '%s' after 'discard'")
SWAG_ERROR(Msg0449, "invalid token '%s' in tuple type, ',' or '}' are expected here")
SWAG_ERROR(Msg0260, "invalid token '['")
SWAG_ERROR(Msg0402, "invalid token, ',' expected")
SWAG_ERROR(Msg0401, "invalid token, identifier expected")
SWAG_ERROR(Msg0731, "invalid type '%s' for attribute parameter")
SWAG_ERROR(Msg0697, "invalid type '%s' for enum flags (should be unsigned integer)")
SWAG_ERROR(Msg0698, "invalid type '%s' for enum index (should be integer)")
SWAG_ERROR(Msg0017, "invalid type declaration, symbol '%s' is not a type (it's %s)")
SWAG_ERROR(Msg0278, "invalid variable name '%s' (cannot start with '@')")
SWAG_ERROR(Msg0296, "invalid variable name '%s' because '@alias' can only be used inside a macro or a mixin function")
SWAG_ERROR(Msg0410, "invalid variable name '%s'")
SWAG_ERROR(Msg0383, "invalid version '%s'")
SWAG_ERROR(Msg0436, "it could be a bug in the compile time part of your program")
SWAG_ERROR(Msg0639, "label name '%s' already defined in the hierarchy")
SWAG_ERROR(Msg0331, "line break or ';' is expected before '%s' to close the %s")
SWAG_ERROR(Msg0464, "literal number is too big (cannot fit in 64 bits)")
SWAG_ERROR(Msg0558, "llvm backend cannot create target '%s'")
SWAG_ERROR(Msg0034, "llvm backend unsupported os '%s'")
SWAG_ERROR(Msg0828, "minus operation not allowed on type '%s'")
SWAG_ERROR(Msg0879, "missing '#global if' expression")
SWAG_ERROR(Msg0878, "missing '#if' expression")
SWAG_ERROR(Msg0269, "missing '#main' function (executable entry point)")
SWAG_ERROR(Msg0500, "missing '%d' test errors (%d raised)")
SWAG_ERROR(Msg0501, "missing '%d' test warnings (%d raised)")
SWAG_ERROR(Msg0329, "missing '%s' %s")
SWAG_ERROR(Msg0867, "missing 'case' expression before ':'")
SWAG_ERROR(Msg0868, "missing 'case' expression before 'break'")
SWAG_ERROR(Msg0863, "missing 'if' boolean expression before '{'")
SWAG_ERROR(Msg0864, "missing 'while' boolean expression before '{'")
SWAG_ERROR(Msg0872, "missing another 'visit' variable name after ',' and before ':'")
SWAG_ERROR(Msg0654, "missing first parameter 'self' for interface function '%s'")
SWAG_ERROR(Msg0020, "missing function call '()' to %s")
SWAG_ERROR(Msg0119, "missing function call parameters")
SWAG_ERROR(Msg0414, "missing function name instead of '%s'")
SWAG_ERROR(Msg0409, "missing function parameter type or assignment (':' or '=')")
SWAG_ERROR(Msg0883, "missing function parameters before '{'")
SWAG_ERROR(Msg0412, "missing generic name or type")
SWAG_ERROR(Msg0411, "missing generic parameters")
SWAG_ERROR(Msg0303, "missing initialization expression to deduce size of array")
SWAG_ERROR(Msg0394, "missing label identifier before '{'")
SWAG_ERROR(Msg0390, "missing namespace name before ';'")
SWAG_ERROR(Msg0389, "missing namespace name before '{'")
SWAG_ERROR(Msg0677, "missing parameters for interface member '%s' ('self' expected as first parameter)")
SWAG_ERROR(Msg0068, "missing parameters for special function '%s'")
SWAG_ERROR(Msg0339, "missing pointer declaration '*' after 'const'")
SWAG_ERROR(Msg0064, "missing return type for special function '%s' ('%s' expected)")
SWAG_ERROR(Msg0063, "missing return type for special function '%s'")
SWAG_ERROR(Msg0874, "missing the 'loop' expression to evaluate before '{'")
SWAG_ERROR(Msg0871, "missing the 'visit' expression to evaluate before '{'")
SWAG_ERROR(Msg0623, "missing variable type or assignment (':' or '=')")
SWAG_ERROR(Msg0556, "module '%s' cannot be found in that workspace")
SWAG_ERROR(Msg0549, "module '%s', cannot resolve %s '%s'")
SWAG_ERROR(Msg0169, "more than one module with name '%s' is present in the workspace (path is '%s')")
SWAG_ERROR(Msg0011, "named parameter '%s' already used")
SWAG_ERROR(Msg0393, "namespace cannot have the same name as the module ('%s')")
SWAG_ERROR(Msg0388, "namespace definition should appear either at file scope or immediately within another namespace definition")
SWAG_ERROR(Msg0391, "namespace name should be an identifier ('%s' provided)")
SWAG_ERROR(Msg0827, "negate an unsigned type ('%s') is not allowed")
SWAG_ERROR(Msg0880, "no corresponding '}' has been found")
SWAG_ERROR(Msg0299, "non mutable variable should be initialized")
SWAG_ERROR(Msg0748, "not all control paths of %s return a value")
SWAG_ERROR(Msg0035, "not enough generic parameters for %s")
SWAG_ERROR(Msg0196, "not enough initializers for '%s' ('%d' expected, '%d' provided)")
SWAG_ERROR(Msg0016, "not enough parameters for %s")
SWAG_ERROR(Msg0205, "not enough parameters in tuple initialization ('%d' expected, '%d' provided)")
SWAG_ERROR(Msg0087, "only calls to 'Swag.Mixin' functions can be done at global scope ('%s' is %s)")
SWAG_ERROR(Msg0870, "opVisit special name expected")
SWAG_ERROR(Msg0005, "operation '%s' not allowed on %s '%s'")
SWAG_ERROR(Msg0504, "operation '%s' not allowed, left type is '%s' and right type is '%s'")
SWAG_ERROR(Msg0157, "operator '%' not allowed on type '%s'")
SWAG_ERROR(Msg0164, "operator '&' not allowed on type '%s'")
SWAG_ERROR(Msg0148, "operator '*' not allowed on type '%s'")
SWAG_ERROR(Msg0143, "operator '+' not allowed on type '%s'")
SWAG_ERROR(Msg0142, "operator '+' not allowed with operand type '%s'")
SWAG_ERROR(Msg0147, "operator '-' not allowed on type '%s'")
SWAG_ERROR(Msg0146, "operator '-' not allowed with operand type '%s'")
SWAG_ERROR(Msg0149, "operator '/' not allowed on type '%s'")
SWAG_ERROR(Msg0170, "operator '<<' not allowed on type '%s'")
SWAG_ERROR(Msg0172, "operator '>>' not allowed on type '%s'")
SWAG_ERROR(Msg0167, "operator '^' not allowed on type '%s'")
SWAG_ERROR(Msg0163, "operator '|' not allowed on type '%s'")
SWAG_ERROR(Msg0265, "operator modifier '%s' already used once")
SWAG_ERROR(Msg0266, "operator modifier '%s' is invalid for operator '%s'")
SWAG_ERROR(Msg0006, "parameter '%d' should be named because some parameters before are named")
SWAG_ERROR(Msg0738, "parameter '%d' should have a default value because some parameters before have a default value")
SWAG_ERROR(Msg0040, "partial type alias '%s' for generic struct instantiation is not supported")
SWAG_ERROR(Msg0892, "placeholder identifier '%s' has not been solved")
SWAG_ERROR(Msg0144, "pointer arithmetic not allowed on 'typeinfo'")
SWAG_ERROR(Msg0579, "pointer arithmetic not allowed with operand type '%s'")
SWAG_ERROR(Msg0024, "pointer to 'Swag.TypeInfo' should be 'const'")
SWAG_ERROR(Msg0342, "pointer to reference is not (yet?) supported")
SWAG_ERROR(Msg0348, "private definition should appear at file or namespace scope")
SWAG_ERROR(Msg0300, "reference should be initialized")
SWAG_ERROR(Msg0774, "returning a value of type '%s', but %s returns nothing")
SWAG_ERROR(Msg0431, "runtime variable '%s' is initialized to zero and cannot be changed at compile time; initialize it with '?' if this is intended")
SWAG_ERROR(Msg0419, "semantic cycle detected during resolution of %s '%s'")
SWAG_ERROR(Msg0173, "shift operand should be 'u32' and not '%s'")
SWAG_ERROR(Msg0653, "should be")
SWAG_ERROR(Msg0812, "size cannot be computed because expression is generic")
SWAG_ERROR(Msg0009, "slice can only be compared to 'null'")
SWAG_ERROR(Msg0474, "slicing operator cannot be applied on an array with multiple dimensions (type is '%s')")
SWAG_ERROR(Msg0475, "slicing operator cannot be applied on type '%s'")
SWAG_ERROR(Msg0657, "some functions of interface '%s' are not implemented")
SWAG_ERROR(Msg0078, "special function '%s' (starting with 'op' followed by a letter in upper case) is unknown")
SWAG_ERROR(Msg0067, "special function '%s' should be defined in a 'impl' scope")
SWAG_ERROR(Msg0625, "special visit name is only valid for struct (type is '%s')")
SWAG_ERROR(Msg0536, "stack overflow (maximum stack size is '--stack-size:%s')")
SWAG_ERROR(Msg0696, "struct '%s' already defined")
SWAG_ERROR(Msg0765, "struct '%s' has the 'Swag.NoCopy' attribute, so 'opPostCopy' is irrelevant")
SWAG_ERROR(Msg0082, "struct '%s' should be initialized in place with '{}' and not parenthesis (this is reserved for function calls)")
SWAG_ERROR(Msg0295, "struct cannot be initialized twice")
SWAG_ERROR(Msg0666, "struct cannot be marked with 'Swag.Opaque' because it is not public")
SWAG_ERROR(Msg0667, "struct cannot be marked with 'Swag.Opaque' because the whole file is exported ('#global export')")
SWAG_ERROR(Msg0839, "struct initialization of '%s' should be done with '{}' and not parenthesis (this is reserved for function calls)")
SWAG_ERROR(Msg0674, "struct member name '%s' starts with 'item', and this is reserved by the language")
SWAG_ERROR(Msg0610, "switch body is empty")
SWAG_ERROR(Msg0612, "switch enum value '%s' already defined")
SWAG_ERROR(Msg0620, "switch is incomplete (missing '%s.%s')")
SWAG_ERROR(Msg0613, "switch value '%d' already defined")
SWAG_ERROR(Msg0614, "switch value '%f' already defined")
SWAG_ERROR(Msg0611, "switch value '%s' already defined")
SWAG_ERROR(Msg0607, "switch without an expression cannot be marked as 'Swag.Complete'")
SWAG_ERROR(Msg0885, "symbol '%s' already defined as %s in an accessible scope")
SWAG_ERROR(Msg0890, "symbol '%s' already defined as a name alias in an accessible scope")
SWAG_ERROR(Msg0886, "symbol '%s' already defined in an accessible scope")
SWAG_ERROR(Msg0346, "symbol '%s' already defined in parent scope")
SWAG_ERROR(Msg0888, "symbol '%s' already defined with the same signature in an accessible scope")
SWAG_ERROR(Msg0262, "symbol ':' is interpreted as a pointer dereference, but is followed by a symbol ('%s')")
SWAG_ERROR(Msg0062, "too few arguments for special function '%s' (at least '%d' expected, only '%d' provided)")
SWAG_ERROR(Msg0626, "too many 'visit' alias names (maximum is '2', but '%u' are provided)")
SWAG_ERROR(Msg0338, "too many array dimensions (maximum is '254')")
SWAG_ERROR(Msg0459, "too many digits in literal number")
SWAG_ERROR(Msg0044, "too many generic parameters for %s '%s'")
SWAG_ERROR(Msg0491, "too many initialization parameters for type '%s'")
SWAG_ERROR(Msg0197, "too many initializers for '%s' ('%d' expected, '%d' provided)")
SWAG_ERROR(Msg0026, "too many parameters for %s")
SWAG_ERROR(Msg0340, "too many pointer dimensions (maximim is '%u')")
SWAG_ERROR(Msg0252, "type '%s' and type '%s' defined in the command line for '%s' are incompatible")
SWAG_ERROR(Msg0002, "type '%s' cannot be used in a range expression")
SWAG_ERROR(Msg0911, "type '%s' cannot be used in an union because it contains 'opDrop' (or one of its members does)")
SWAG_ERROR(Msg0909, "type '%s' cannot be used in an union because it contains 'opPostCopy' (or one of its members does)")
SWAG_ERROR(Msg0910, "type '%s' cannot be used in an union because it contains 'opPostMove' (or one of its members does)")
SWAG_ERROR(Msg0671, "type '%s' is generic, but struct '%s' does not declare generic parameters")
SWAG_ERROR(Msg0478, "type '%s' is immutable ('const') and cannot be changed")
SWAG_ERROR(Msg0838, "type 'Self' cannot be used outside an 'impl', 'struct' or 'interface' block")
SWAG_ERROR(Msg0730, "type 'alias' is only valid in a 'Swag.Macro' or 'Swag.Mixin' function")
SWAG_ERROR(Msg0729, "type 'code' is only valid in a 'Swag.Macro' or 'Swag.Mixin' function")
SWAG_ERROR(Msg0294, "type to tuple conversion is not (yet?) supported for type '%s'")
SWAG_ERROR(Msg0309, "unable to deduce type of %s '%s'")
SWAG_ERROR(Msg0534, "uncatched error when calling '%s'; missing 'try', 'assume' or 'catch'")
SWAG_ERROR(Msg0099, "unexpected aliased identifiers because function '%s' is not a macro or a mixin")
SWAG_ERROR(Msg0274, "unexpected call parameters for variable '%s'")
SWAG_ERROR(Msg0080, "unexpected end of file found in comment")
SWAG_ERROR(Msg0905, "unexpected end of line found in string literal")
SWAG_ERROR(Msg0273, "unexpected generic parameters for variable '%s'")
SWAG_ERROR(Msg0352, "unexpected token '%s' after 'private' attribute")
SWAG_ERROR(Msg0353, "unexpected token '%s' after 'protected' attribute")
SWAG_ERROR(Msg0354, "unexpected token '%s' after 'public' attribute")
SWAG_ERROR(Msg0140, "unknown compiler instruction '%s'")
SWAG_ERROR(Msg0122, "unknown identifier '%s'")
SWAG_ERROR(Msg0631, "unknown label '%s'")
SWAG_ERROR(Msg0499, "unknown module dependency '%s'")
SWAG_ERROR(Msg0008, "unknown named parameter '%s'")
SWAG_ERROR(Msg0282, "unpacking '%d' variable(s), but the tuple on the right contains '%d' element(s)")
SWAG_ERROR(Msg0768, "unreachable code")
SWAG_ERROR(Msg0664, "unsupported alias as an implementation block name")
SWAG_ERROR(Msg0555, "unsupported tuple type in generic parameters")
SWAG_ERROR(Msg0109, "unused return value of function '%s'")
SWAG_ERROR(Msg0092, "unused return value of lambda '%s'")
SWAG_ERROR(Msg0096, "unused variable '%s'")
SWAG_ERROR(Msg0180, "value '%I64d' is negative and not in the range of 'u16'")
SWAG_ERROR(Msg0182, "value '%I64d' is negative and not in the range of 'u32'")
SWAG_ERROR(Msg0185, "value '%I64d' is negative and not in the range of 'u64'")
SWAG_ERROR(Msg0178, "value '%I64d' is negative and not in the range of 'u8'")
SWAG_ERROR(Msg0187, "value '%I64d' is not in the range of 's16'")
SWAG_ERROR(Msg0188, "value '%I64d' is not in the range of 's32'")
SWAG_ERROR(Msg0189, "value '%I64d' is not in the range of 's64'")
SWAG_ERROR(Msg0186, "value '%I64d' is not in the range of 's8'")
SWAG_ERROR(Msg0191, "value '%I64d' is truncated in 'f32'")
SWAG_ERROR(Msg0194, "value '%I64d' is truncated in 'f64'")
SWAG_ERROR(Msg0181, "value '%I64u' is not in the range of 'u16'")
SWAG_ERROR(Msg0183, "value '%I64u' is not in the range of 'u32'")
SWAG_ERROR(Msg0179, "value '%I64u' is not in the range of 'u8'")
SWAG_ERROR(Msg0192, "value '%I64u' is truncated in 'f32'")
SWAG_ERROR(Msg0195, "value '%I64u' is truncated in 'f64'")
SWAG_ERROR(Msg0193, "value '%lf' is truncated in 'f32'")
SWAG_ERROR(Msg0086, "variable '%s' has only been used to find function '%s'; use scope '%s' instead")
SWAG_ERROR(Msg0894, "variable '%s' is used before being declared")
SWAG_ERROR(Msg0645, "variable initialized twice, first with type arguments, and then with an assignment")
SWAG_ERROR(Msg0271, "variable name or '?' expected in tuple unpacking, found '%s'")
SWAG_ERROR(Msg0457, "variable should have a type or should be initialized")
SWAG_ERROR(Msg0734, "variadic argument should be the last one")
SWAG_ERROR(Msg0289, "version should be of the form 'version.revision.buildnum', with each number >= 0 or the '?' character")
SWAG_ERROR(Msg0056, "x64 backend unsupported os '%s'")
SWAG_ERROR(Msg0123, nullptr)
SWAG_ERROR(Msg0224, nullptr)
SWAG_ERROR(Msg0638, nullptr)
SWAG_ERROR(Msg0685, nullptr)
SWAG_ERROR(Msg0816, nullptr)
SWAG_ERROR(Msg0815, nullptr)
SWAG_ERROR(Msg0813, nullptr)
SWAG_ERROR(Msg0184, nullptr)
SWAG_ERROR(Msg0811, nullptr)
SWAG_ERROR(Msg0809, nullptr)
SWAG_ERROR(Msg0808, nullptr)
SWAG_ERROR(Msg0641, nullptr)
SWAG_ERROR(Msg0642, nullptr)
SWAG_ERROR(Msg0804, nullptr)
SWAG_ERROR(Msg0803, nullptr)
SWAG_ERROR(Msg0686, nullptr)
SWAG_ERROR(Msg0799, nullptr)
SWAG_ERROR(Msg0779, nullptr)
SWAG_ERROR(Msg0687, nullptr)
SWAG_ERROR(Msg0688, nullptr)
SWAG_ERROR(Msg0643, nullptr)
SWAG_ERROR(Msg0640, nullptr)
SWAG_ERROR(Msg0456, nullptr)
SWAG_ERROR(Msg0644, nullptr)
SWAG_ERROR(Msg0458, nullptr)
SWAG_ERROR(Msg0317, nullptr)
SWAG_ERROR(Msg0452, nullptr)
SWAG_ERROR(Msg0770, nullptr)
SWAG_ERROR(Msg0647, nullptr)
SWAG_ERROR(Msg0450, nullptr)
SWAG_ERROR(Msg0461, nullptr)
SWAG_ERROR(Msg0462, nullptr)
SWAG_ERROR(Msg0446, nullptr)
SWAG_ERROR(Msg0445, nullptr)
SWAG_ERROR(Msg0443, nullptr)
SWAG_ERROR(Msg0550, nullptr)
SWAG_ERROR(Msg0442, nullptr)
SWAG_ERROR(Msg0439, nullptr)
SWAG_ERROR(Msg0873, nullptr)
SWAG_ERROR(Msg0875, nullptr)
SWAG_ERROR(Msg0548, nullptr)
SWAG_ERROR(Msg0437, nullptr)
SWAG_ERROR(Msg0433, nullptr)
SWAG_ERROR(Msg0432, nullptr)
SWAG_ERROR(Msg0882, nullptr)
SWAG_ERROR(Msg0690, nullptr)
SWAG_ERROR(Msg0430, nullptr)
SWAG_ERROR(Msg0678, nullptr)
SWAG_ERROR(Msg0740, nullptr)
SWAG_ERROR(Msg0693, nullptr)
SWAG_ERROR(Msg0372, nullptr)
SWAG_ERROR(Msg0736, nullptr)
SWAG_ERROR(Msg0735, nullptr)
SWAG_ERROR(Msg0429, nullptr)
SWAG_ERROR(Msg0732, nullptr)
SWAG_ERROR(Msg0544, nullptr)
SWAG_ERROR(Msg0506, nullptr)
SWAG_ERROR(Msg0649, nullptr)
SWAG_ERROR(Msg0650, nullptr)
SWAG_ERROR(Msg0703, nullptr)
SWAG_ERROR(Msg0704, nullptr)
SWAG_ERROR(Msg0651, nullptr)
SWAG_ERROR(Msg0656, nullptr)
SWAG_ERROR(Msg0723, nullptr)
SWAG_ERROR(Msg0422, nullptr)
SWAG_ERROR(Msg0721, nullptr)
SWAG_ERROR(Msg0658, nullptr)
SWAG_ERROR(Msg0415, nullptr)
SWAG_ERROR(Msg0479, nullptr)
SWAG_ERROR(Msg0705, nullptr)
SWAG_ERROR(Msg0480, nullptr)
SWAG_ERROR(Msg0484, nullptr)
SWAG_ERROR(Msg0715, nullptr)
SWAG_ERROR(Msg0663, nullptr)
SWAG_ERROR(Msg0404, nullptr)
SWAG_ERROR(Msg0713, nullptr)
SWAG_ERROR(Msg0711, nullptr)
SWAG_ERROR(Msg0665, nullptr)
SWAG_ERROR(Msg0503, nullptr)
SWAG_ERROR(Msg0492, nullptr)
SWAG_ERROR(Msg0494, nullptr)
SWAG_ERROR(Msg0707, nullptr)
SWAG_ERROR(Msg0387, nullptr)
SWAG_ERROR(Msg0621, nullptr)
SWAG_ERROR(Msg0562, nullptr)
SWAG_ERROR(Msg0618, nullptr)
SWAG_ERROR(Msg0563, nullptr)
SWAG_ERROR(Msg0302, nullptr)
SWAG_ERROR(Msg0568, nullptr)
SWAG_ERROR(Msg0889, nullptr)
SWAG_ERROR(Msg0575, nullptr)
SWAG_ERROR(Msg0605, nullptr)
SWAG_ERROR(Msg0576, nullptr)
SWAG_ERROR(Msg0577, nullptr)
SWAG_ERROR(Msg0578, nullptr)
SWAG_ERROR(Msg0580, nullptr)
SWAG_ERROR(Msg0581, nullptr)
SWAG_ERROR(Msg0585, nullptr)
SWAG_ERROR(Msg0601, nullptr)
SWAG_ERROR(Msg0887, nullptr)
SWAG_ERROR(Msg0590, nullptr)
SWAG_ERROR(Msg0836, nullptr)
SWAG_ERROR(Msg0837, nullptr)
SWAG_ERROR(Msg0847, nullptr)
SWAG_ERROR(Msg0849, nullptr)
SWAG_ERROR(Msg0850, nullptr)
SWAG_ERROR(Msg0851, nullptr)
SWAG_ERROR(Msg0852, nullptr)
SWAG_ERROR(Msg0855, nullptr)
SWAG_ERROR(Msg0856, nullptr)
SWAG_ERROR(Msg0857, nullptr)
SWAG_ERROR(Msg0628, nullptr)
SWAG_ERROR(Msg0358, nullptr)
SWAG_ERROR(Msg0261, nullptr)
SWAG_ERROR(Msg0357, nullptr)
SWAG_ERROR(Msg0359, nullptr)
SWAG_ERROR(Msg0487, nullptr)
SWAG_ERROR(Msg0773, nullptr)
SWAG_ERROR(Msg0362, nullptr)
SWAG_ERROR(Msg0361, nullptr)
SWAG_ERROR(Msg0360, nullptr)
SWAG_ERROR(Msg0263, nullptr)
SWAG_ERROR(Msg0363, nullptr)
SWAG_ERROR(Msg0174, nullptr)
SWAG_ERROR(Msg0341, nullptr)
SWAG_ERROR(Msg0483, nullptr)
SWAG_ERROR(Msg0111, nullptr)
SWAG_ERROR(Msg0259, nullptr)
SWAG_ERROR(Msg0126, nullptr)
SWAG_ERROR(Msg0158, nullptr)
SWAG_ERROR(Msg0587, nullptr)
SWAG_ERROR(Msg0589, nullptr)
SWAG_ERROR(Msg0398, nullptr)
SWAG_ERROR(Msg0551, nullptr)
SWAG_ERROR(Msg0018, nullptr)
SWAG_ERROR(Msg0553, nullptr)
SWAG_ERROR(Msg0084, nullptr)
SWAG_ERROR(Msg0592, nullptr)
SWAG_ERROR(Msg0106, nullptr)
SWAG_ERROR(Msg0619, nullptr)
SWAG_ERROR(Msg0517, nullptr)
SWAG_ERROR(Msg0884, nullptr)
SWAG_ERROR(Msg0287, nullptr)
SWAG_ERROR(Msg0253, nullptr)
SWAG_ERROR(Msg0095, nullptr)
SWAG_ERROR(Msg0912, nullptr)

SWAG_ERROR(Hnt0006, "this cannot be visited")
SWAG_ERROR(Hnt0007, "this implies another 'visit' variable name")
SWAG_ERROR(Hnt0008, "this is a pointer dereference ':'")
SWAG_ERROR(Hnt0009, "this should be a 'visit' variable name or the expression to evaluate")
SWAG_ERROR(Hnt0010, "this should be a 'visit' variable name")
SWAG_ERROR(Hnt0021, "this should be a pointer")
SWAG_ERROR(Hnt0025, "this could be casted with 'cast(%s)'")
SWAG_ERROR(Hnt0001, "this '@sqrt' is called with a negative value")
SWAG_ERROR(Hnt0023, "this call could be preceeded by 'discard' if you do not want to use the return value")
SWAG_ERROR(Hnt0005, "this could be casted to 'uint'")
SWAG_ERROR(Hnt0017, "this function is marked with the 'Swag.Inline' attribute")
SWAG_ERROR(Hnt0015, "this function is marked with the 'Swag.Macro' attribute")
SWAG_ERROR(Hnt0016, "this function is marked with the 'Swag.Mixin' attribute")
SWAG_ERROR(Hnt0018, "this is a constant")
SWAG_ERROR(Hnt0024, "this is a pointer type declaration because of '*'")
SWAG_ERROR(Hnt0003, "this is a static reference to a struct member of '%s'")
SWAG_ERROR(Hnt0014, "this is invalid in global scope")
SWAG_ERROR(Hnt0012, "this return (%s) should have type '%s'")
SWAG_ERROR(Hnt0004, "this should be 'const %s'")
SWAG_ERROR(Hnt0020, "this should be 'impl %s'")
SWAG_ERROR(Hnt0019, "this should be 'impl enum %s'")
SWAG_ERROR(Hnt0013, "this should be on another line, or separated with ';'")
SWAG_ERROR(Hnt0011, "this type is '%s'")
SWAG_ERROR(Hnt0022, "this type is immutable ('const')")
SWAG_ERROR(Hnt0002, "this value can only be converted to type '%s' with a dynamic call to 'opAffect'")
SWAG_ERROR(Hnt0026, "this should be removed")
SWAG_ERROR(Hnt0027, "this should be the 'loop' expression to evaluate")
SWAG_ERROR(Hnt0028, "this should be the 'loop' variable name or the expression to evaluate")
SWAG_ERROR(Hnt0029, "this should be the 'visit' expression to evaluate")
SWAG_ERROR(Hnt0030, "this should be the expression to dereference")
SWAG_ERROR(Hnt0031, "this should be the range right expression")
SWAG_ERROR(Hnt0032, "this type is '%s' (could be casted with 'cast(%s)')")
SWAG_ERROR(Hnt0033, "this evaluates to 0")
SWAG_ERROR(Hnt0000, "this divisor expression is zero")
SWAG_ERROR(Hnt0034, "this returns nothing")
SWAG_ERROR(Hnt0035, "this is an alias and should be an identifier")
SWAG_ERROR(Hnt0036, nullptr)
SWAG_ERROR(Hnt0037, nullptr)

SWAG_ERROR(Note011, "%s is marked with 'Swag.NoReturn', so the return is used inside %s")
SWAG_ERROR(Note001, "'%s' is %s of type '%s' which does not contain a subscope")
SWAG_ERROR(Note010, "'%s' is %s")
SWAG_ERROR(Note042, "'%s' is a function without the 'Swag.ConstExpr' attribute (you could also use '#run' before the call)")
SWAG_ERROR(Note041, "'%s' is a variable and variables inside expressions cannot be evaluated at compile time")
SWAG_ERROR(Note006, "did you mean '%s' ?")
SWAG_ERROR(Note008, "here is %s")
SWAG_ERROR(Note040, "here is '%s'")
SWAG_ERROR(Note024, "here is a previous declaration")
SWAG_ERROR(Note016, "here is another")
SWAG_ERROR(Note025, "here is attribute '%s'")
SWAG_ERROR(Note000, "here is its declaration")
SWAG_ERROR(Note015, "here is one")
SWAG_ERROR(Note026, "here is the %s")
SWAG_ERROR(Note007, "here is the '%s'")
SWAG_ERROR(Note027, "here is the declaration of '%s'")
SWAG_ERROR(Note028, "here is the declaration")
SWAG_ERROR(Note029, "here is the definition of '%s'")
SWAG_ERROR(Note030, "here is the definition of the tuple")
SWAG_ERROR(Note031, "here is the deprecated definition")
SWAG_ERROR(Note032, "here is the faulty attribute")
SWAG_ERROR(Note033, "here is the function")
SWAG_ERROR(Note034, "here is the missing value")
SWAG_ERROR(Note035, "here is the other '#import'")
SWAG_ERROR(Note036, "here is the other definition")
SWAG_ERROR(Note037, "here is the previous definition")
SWAG_ERROR(Note038, "here is the related command line option: '%s'")
SWAG_ERROR(Note039, "here is the variable declaration")
SWAG_ERROR(Note020, "if you want to declare a lambda, you should use 'func('")
SWAG_ERROR(Note014, "if you want to dereference variable '%s' like in C, use 'dref %s'")
SWAG_ERROR(Note005, "is there a missing 'self' ?")
SWAG_ERROR(Note019, "it is applied on this %s")
SWAG_ERROR(Note012, "note: use '-w:<path>' or '--workspace:<path>' to specifiy a valid workspace folder, or execute swag from a valid workspace folder")
SWAG_ERROR(Note002, "occurred %s %s'%s'")
SWAG_ERROR(Note003, "occurred %s")
SWAG_ERROR(Note004, "occurred in generated code")
SWAG_ERROR(Note013, "symbol has been found thanks to a 'using'")
SWAG_ERROR(Note021, "to close the left expression")
SWAG_ERROR(Note023, "to close the namespace body")
SWAG_ERROR(Note022, "to start the namespace body")
SWAG_ERROR(Note018, "when solving affectation")
SWAG_ERROR(Note017, "when solving")
SWAG_ERROR(Note009, "you can run swag with --dbgcatch to attach the bytecode debugger when the error occurs")
SWAG_ERROR(Note043, "symbol '%s' was not found in '%s'")
SWAG_ERROR(Note044, "symbol '%s' exists in interface scope '%s'")
SWAG_ERROR(Note045, nullptr)
