SWAG_ERROR(Nte0000, "here is its declaration")
SWAG_ERROR(Nte0001, "`%s` is %s of type `%s` which does not contain a subscope")
SWAG_ERROR(Nte0002, nullptr)
SWAG_ERROR(Nte0003, nullptr)
SWAG_ERROR(Nte0004, "occurred in generated code")
SWAG_ERROR(Nte0005, nullptr)
SWAG_ERROR(Nte0006, "this `using` field can be converted")
SWAG_ERROR(Nte0007, "here is the `%s`")
SWAG_ERROR(Nte0008, "here is %s")
SWAG_ERROR(Nte0009, "you can run swag with --dbg-catch to attach the bytecode debugger when the error occurs")
SWAG_ERROR(Nte0010, "`%s` is %s")
SWAG_ERROR(Nte0011, "%s is marked with `Swag.NoReturn`, so the return is used inside %s")
SWAG_ERROR(Nte0012, "note: use `-w:<path>` or `--workspace:<path>` to specifiy a valid workspace folder, or execute swag from a valid workspace folder")
SWAG_ERROR(Nte0013, "the symbol has been found thanks to a `using`")
SWAG_ERROR(Nte0014, "here is the other value")
SWAG_ERROR(Nte0015, "here is one")
SWAG_ERROR(Nte0016, "here is another")
SWAG_ERROR(Nte0017, "`%s` has been found in `%s` because of a using field")
SWAG_ERROR(Nte0018, "the hidden call to `%s` returns type `%s` which does not contain a subscope")
SWAG_ERROR(Nte0019, "it is applied on this %s")
SWAG_ERROR(Nte0020, "here is the start")
SWAG_ERROR(Nte0021, "here is another one")
SWAG_ERROR(Nte0022, nullptr)
SWAG_ERROR(Nte0023, "here is the immutable value")
SWAG_ERROR(Nte0024, "here is a previous declaration")
SWAG_ERROR(Nte0025, "here is attribute `%s`")
SWAG_ERROR(Nte0026, "here is the %s")
SWAG_ERROR(Nte0027, "here is the declaration of `%s`")
SWAG_ERROR(Nte0028, "here is the declaration")
SWAG_ERROR(Nte0029, "here is the definition of `%s`")
SWAG_ERROR(Nte0030, "here is the definition of the tuple")
SWAG_ERROR(Nte0031, "here is the deprecated definition")
SWAG_ERROR(Nte0032, "here is the faulty attribute")
SWAG_ERROR(Nte0033, "here is the function")
SWAG_ERROR(Nte0034, "here is the missing value")
SWAG_ERROR(Nte0035, "here is the other `#import`")
SWAG_ERROR(Nte0036, "here is the other definition")
SWAG_ERROR(Nte0037, "here is the previous definition")
SWAG_ERROR(Nte0038, "here is the related command line option: `%s`")
SWAG_ERROR(Nte0039, "here is the variable declaration")
SWAG_ERROR(Nte0040, "here is `%s`")
SWAG_ERROR(Nte0041, "`%s` is a variable and variables inside expressions cannot be evaluated at compile time")
SWAG_ERROR(Nte0042, "`%s` is a function without the `Swag.ConstExpr` attribute")
SWAG_ERROR(Nte0043, "the symbol `%s` was not found in `%s`")
SWAG_ERROR(Nte0044, "the symbol `%s` exists in interface scope `%s`")
SWAG_ERROR(Nte0045, "an instance of generic function `%s` ")
SWAG_ERROR(Nte0046, "%s `%s` is waiting for %s `%s` to be solved")
SWAG_ERROR(Nte0047, "resulting type is `%s`")
SWAG_ERROR(Nte0048, "function `%s`")
SWAG_ERROR(Nte0049, "`%s`")
SWAG_ERROR(Nte0050, "%s of type `%s`")
SWAG_ERROR(Nte0051, "there is an hidden call to `%s` for type `%s`")
SWAG_ERROR(Nte0052, "expected the type `%s` because of %s")
SWAG_ERROR(Nte0053, nullptr)
SWAG_ERROR(Nte0054, nullptr)
SWAG_ERROR(Nte0055, "occurred when trying to match the type of the other part of the conditional expression")
SWAG_ERROR(Nte0056, "the other one is an implicit `using self` as a first parameter")
SWAG_ERROR(Nte0057, "here is the literal suffix `%s`")
SWAG_ERROR(Nte0058, nullptr)
SWAG_ERROR(Nte0059, nullptr)
SWAG_ERROR(Nte0060, nullptr)
SWAG_ERROR(Nte0061, nullptr)
SWAG_ERROR(Nte0062, "and this one could also be converted")
SWAG_ERROR(Nte0063, "here is the other return")
SWAG_ERROR(Nte0064, "here is the field where the recursion occurs")
SWAG_ERROR(Nte0065, nullptr)
SWAG_ERROR(Nte0066, "here is the parameter `%s` of %s")
SWAG_ERROR(Nte0067, "expected `%s` because of the function return type")
SWAG_ERROR(Nte0068, "here is the generic parameter `%s` of %s")
