#define Msg0000 "fatal error: invalid swag command '%s'"
#define Msg0001 "compare operation not allowed on type '%s'"
#define Msg0002 "compare operation not allowed on type '%s'"
#define Msg0003 "compare operation not allowed on type '%s'"
#define Msg0004 "compare operation not allowed on type '%s'"
#define Msg0005 "operation '%s' not allowed on %s '%s'"
#define Msg0006 "operation '%s' not allowed on %s '%s'"
#define Msg0007 "comparison operations are invalid on tuple types"
#define Msg0008 "comparison operations are invalid on tuple types"
#define Msg0009 "a slice can only be compared to 'null'"
#define Msg0010 "an interface can only be compared to 'null'"
#define Msg0011 "operation '%s' not allowed on %s '%s'"
#define Msg0012 "cannot reference a type expression"
#define Msg0013 "%s '%s' cannot be referenced in that context because it's not an rvalue"
#define Msg0014 "cannot evaluate relative size at compile time"
#define Msg0015 "relative size value must be 0, 1, 2, 4 or 8"
#define Msg0016 "relative size value must be 0, 1, 2, 4 or 8"
#define Msg0017 "symbol '%s' is not a type (it's %s)"
#define Msg0018 "this is the definition of '%s'"
#define Msg0019 "a reference must be declared as 'const'"
#define Msg0020 "a reference must be declared as 'const'"
#define Msg0021 "array dimension cannot be evaluated at compile time"
#define Msg0022 "array dimension is '%s' and should be integer"
#define Msg0023 "array dimension is 0"
#define Msg0024 "pointer to 'swag.TypeInfo' must be const"
#define Msg0025 "alias is public but '%s' is not"
#define Msg0026 "this is the definition of '%s'"
#define Msg0027 "alias can only be used with a type or an identifier"
#define Msg0028 "'swag.strict' attribute can only be used on a type alias"
#define Msg0029 "cannot alias multiple variables"
#define Msg0030 "alias cannot be used on %s"
#define Msg0031 "invalid bitcast type '%s' (should be native integer, char or float)"
#define Msg0032 "cannot bitcast from type '%s' (should be native integer, char or float)"
#define Msg0033 "cannot bitcast to a type with a bigger size ('%s' from '%s')"
#define Msg0034 "llvm backend unsupported os '%s'"
#define Msg0035 "llvm backend unsupported os '%s'"
#define Msg0036 "error: backend: cannot locate windows sdk folder"
#define Msg0037 "cannot instantiate generic %s '%s' with an untyped integer, you need to specify a type\n"
#define Msg0038 "cannot instantiate generic %s '%s' with an untyped float, you need to specify a type\n"
#define Msg0039 "cannot instantiate generic struct '%s', missing contextual types replacements"
#define Msg0040 "partial type alias for generic struct instantiation is not supported"
#define Msg0041 "cannot instantiate generic function '%s', missing generic parameters"
#define Msg0042 "cannot instantiate generic function '%s', missing contextual types replacements"
#define Msg0043 "cannot instantiate variable because type '%s' is generic"
#define Msg0044 "cannot instantiate variable because type '%s' is generic"
#define Msg0045 "cannot create '%s' process (::CreatePipe)"
#define Msg0046 "cannot create process '%s': %s"
#define Msg0047 "cannot create process '%s': %s"
#define Msg0048 "cannot set environment variable 'SWAG_FOLDER' to '%s'\n"
#define Msg0049 "cannot access environment variable 'PATH'\n"
#define Msg0050 "cannot access environment variable 'PATH'\n"
#define Msg0051 "cannot add '%s' to the 'PATH' environment variable\n"
#define Msg0052 "fail to start watcher service !"
#define Msg0053 "fail to start watcher service !"
#define Msg0054 "fail to start watcher service !"
#define Msg0055 "fail to update watcher service !"
#define Msg0056 "x64 backend unsupported os '%s'"
#define Msg0057 "x64 backend unsupported os '%s'"
#define Msg0058 "[compiler internal] %s"
#define Msg0059 "[compiler internal] function '%s' does not release all registers; this is fine, but should be reported !"
#define Msg0060 "[compiler internal] function '%s' releases too many registers !"
#define Msg0061 "invalid number of arguments for special function '%s' ('%d' expected, '%d' provided)"
#define Msg0062 "too few arguments for special function '%s' (at least '%d' expected, only '%d' provided)"
#define Msg0063 "missing return type for special function '%s'"
#define Msg0064 "missing return type for special function '%s' ('%s' expected)"
#define Msg0065 "invalid return type for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0066 "invalid parameter '%d' for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0067 "special function '%s' should be defined in a 'impl' scope"
#define Msg0068 "missing parameters for special function '%s'"
#define Msg0069 "invalid first parameter type for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0070 "invalid first parameter type for special function '%s' ('%s' expected, '%s' provided)"
#define Msg0071 "invalid number of generic parameters for special function '%s'"
#define Msg0072 "invalid generic parameter for special function '%s' ('string' expected, '%s' provided)"
#define Msg0073 "invalid number of generic parameters for special function '%s'"
#define Msg0074 "invalid generic parameter for special function '%s' ('bool' expected, '%s' provided)"
#define Msg0075 "'opVisit' must have the 'swag.macro' attribute"
#define Msg0076 "special function '%s' cannot be generic"
#define Msg0077 "invalid parameter '2' for special function '%s' (cannot be of type '%s')"
#define Msg0078 "function '%s' does not match a special function/operator overload"
#define Msg0079 "cannot find special function '%s' in '%s'"
#define Msg0080 "unexpected end of file found in comment"
#define Msg0081 "invalid character '%s'"
#define Msg0082 "struct '%s' must be initialized in place with '{}' and not parenthesis (this is reserved for function calls)"
#define Msg0083 "%s '%s' is deprecated"
#define Msg0084 "this is the deprecated definition"
#define Msg0085 "identifier '%s' cannot be dereferenced like a struct (type is '%s')"
#define Msg0086 "variable '%s' has only been used to find function '%s'; use scope '%s' instead"
#define Msg0087 "only calls to 'swag.mixin' functions can be done at global scope ('%s' is %s)"
#define Msg0088 "function '%s' is not declared with the 'swag.mixin' attribute, and this is mandatory for a function call at global scope"
#define Msg0089 "this is the function"
#define Msg0090 "struct '%s' must be initialized in place with '{}' and not parenthesis (this is reserved for function calls)"
#define Msg0091 "cannot reference 'swag.compiler' variable '%s' from runtime function '%s'"
#define Msg0092 "unused return value of lambda '%s'"
#define Msg0093 "this is the variable declaration"
#define Msg0094 "cannot discard a function call that returns nothing"
#define Msg0095 "this is the variable declaration"
#define Msg0096 "unused variable '%s'"
#define Msg0097 "%s '%s' has not been used as the first parameter to call '%s'"
#define Msg0098 "function '%s' must be called with '()' and not curlies (this is reserved for struct initialization)"
#define Msg0099 "invalid aliased identifiers because function '%s' is not a macro or a mixin"
#define Msg0100 "cannot reference 'opInit' special function (use '@init' instead)"
#define Msg0101 "cannot reference 'opDrop' special function (use '@drop' instead)"
#define Msg0102 "cannot reference 'opReloc' special function (use '@reloc' instead)"
#define Msg0103 "cannot reference 'opPostCopy' special function (use '@postcopy' instead)"
#define Msg0104 "cannot reference 'opPostMove' special function (use '@postmove' instead)"
#define Msg0105 "cannot call empty function '%s'"
#define Msg0106 "this is the function"
#define Msg0107 "cannot reference 'swag.compiler' function '%s' from runtime function '%s'"
#define Msg0108 "cannot reference 'swag.test' function '%s' from '%s'"
#define Msg0109 "unused return value of function '%s'"
#define Msg0110 "this is the function"
#define Msg0111 "cannot discard a function call that returns nothing"
#define Msg0112 "this is the function"
#define Msg0113 "none of the %d overloads could match"
#define Msg0114 "cannot take the address of a function with call parameters"
#define Msg0115 "ambiguous resolution of generic %s '%s'"
#define Msg0116 "ambiguous resolution of symbol '%s'"
#define Msg0117 "cannot use 'using' on two variables with the same type"
#define Msg0118 "this is the other definition"
#define Msg0119 "missing function call parameters"
#define Msg0120 "field name '%s' cannot be found in tuple"
#define Msg0121 "identifier '%s' cannot be found in %s '%s'"
#define Msg0122 "unknown identifier '%s'"
#define Msg0123 "invalid lambda call, cannot reference structure member '%s'"
#define Msg0124 "invalid lambda call, '%s' is not a variable"
#define Msg0125 "identifier '%s' has call parameters, but is a variable of type '%s' and not a function"
#define Msg0126 "this is '%s'"
#define Msg0127 "identifier '%s' has call parameters, but is %s and not a function"
#define Msg0128 "this is '%s'"
#define Msg0129 "variadic argument must be the last one"
#define Msg0130 "invalid generic parameters, identifier '%s' is %s and not a function or a structure"
#define Msg0131 "this is '%s'"
#define Msg0132 "invalid reference to private scope"
#define Msg0133 "cannot resolve identifier '%s'"
#define Msg0134 "cannot resolve identifier '%s'"
#define Msg0135 "backtick can only be used inside an inline/macro block"
#define Msg0136 "back ticked identifier can only be used inside a 'swag.macro' function or an '#inline' block"
#define Msg0137 "'%s' cannot be used inside a struct special function"
#define Msg0138 "'%s' can only be used inside a function marked with 'throw', and '%s' is not"
#define Msg0139 "'%s' can only be used before a function call, and '%s' is %s"
#define Msg0140 "pointer arithmetic not allowed on 'typeinfo'"
#define Msg0141 "pointer arithmetic not allowed with operand type '%s'"
#define Msg0142 "operator '+' not allowed with operand type '%s'"
#define Msg0143 "operator '+' not allowed on type '%s'"
#define Msg0144 "pointer arithmetic not allowed on 'typeinfo'"
#define Msg0145 "pointer arithmetic not allowed with operand type '%s'"
#define Msg0146 "operator '-' not allowed with operand type '%s'"
#define Msg0147 "operator '-' not allowed on type '%s'"
#define Msg0148 "operator '*' not allowed on type '%s'"
#define Msg0149 "operator '/' not allowed on type '%s'"
#define Msg0150 "division by zero"
#define Msg0151 "division by zero"
#define Msg0152 "division by zero"
#define Msg0153 "division by zero"
#define Msg0154 "division by zero"
#define Msg0155 "division by zero"
#define Msg0156 "division by zero"
#define Msg0157 "operator '%' not allowed on type '%s'"
#define Msg0158 "division by zero"
#define Msg0159 "division by zero"
#define Msg0160 "division by zero"
#define Msg0161 "division by zero"
#define Msg0162 "division by zero"
#define Msg0163 "operator '|' not allowed on type '%s'"
#define Msg0164 "operator '&' not allowed on type '%s'"
#define Msg0165 "expression cannot be evaluated at compile time"
#define Msg0166 "expression cannot be evaluated at compile time"
#define Msg0167 "operator '^' not allowed on type '%s'"
#define Msg0168 "invalid operation '%s' on a tuple type"
#define Msg0169 "invalid operation '%s' on a tuple type"
#define Msg0170 "operator '<<' not allowed on type '%s'"
#define Msg0171 "shift operand must be 'u32' and not '%s'"
#define Msg0172 "operator '>>' not allowed on type '%s'"
#define Msg0173 "shift operand must be 'u32' and not '%s'"
#define Msg0174 "an explicit 'cast(%s)' can be used to force the type"
#define Msg0175 "cannot cast implicitly from '%s' to '%s'"
#define Msg0176 "cannot cast, type '%s' does not implement interface '%s'"
#define Msg0177 "cannot cast from '%s' to '%s'"
#define Msg0178 "value '%I64d' is negative and not in the range of 'u8'"
#define Msg0179 "value '%I64u' is not in the range of 'u8'"
#define Msg0180 "value '%I64d' is negative and not in the range of 'u16'"
#define Msg0181 "value '%I64u' is not in the range of 'u16'"
#define Msg0182 "value '%I64d' is negative and not in the range of 'u32'"
#define Msg0183 "value '%I64u' is not in the range of 'u32'"
#define Msg0184 "value '%I64d' is negative and not in the range of 'u64'"
#define Msg0185 "value '%I64d' is negative and not in the range of 'u64'"
#define Msg0186 "value '%I64d' is not in the range of 's8'"
#define Msg0187 "value '%I64d' is not in the range of 's16'"
#define Msg0188 "value '%I64d' is not in the range of 's32'"
#define Msg0189 "value '%I64d' is not in the range of 's64'"
#define Msg0190 "value '%I64d' is not in the range of 's64'"
#define Msg0191 "value '%I64d' is truncated in 'f32'"
#define Msg0192 "value '%I64u' is truncated in 'f32'"
#define Msg0193 "value '%lf' is truncated in 'f32'"
#define Msg0194 "value '%I64d' is truncated in 'f64'"
#define Msg0195 "value '%I64u' is truncated in 'f64'"
#define Msg0196 "not enough initializers for '%s' ('%d' expected, '%d' provided)"
#define Msg0197 "too many initializers for '%s' ('%d' expected, '%d' provided)"
#define Msg0198 "relative types are not supported in expression lists"
#define Msg0199 "relative types are not supported in expression lists"
#define Msg0200 "cannot cast from '%s' to '%s' because '%s' has multiple fields of type '%s' with 'using'"
#define Msg0201 "this is one"
#define Msg0202 "this is another"
#define Msg0203 "cannot cast, not enough initializers ('%d' expected, '%d' provided)"
#define Msg0204 "cannot cast, too many initializers ('%d' expected, '%d' provided)"
#define Msg0205 "not enough parameters in tuple initialization ('%d' expected, '%d' provided)"
#define Msg0206 "cannot reference variable '%s' because it's in another stack frame"
#define Msg0207 "[safety] truncated bits when casting expression from '%s' to '%s'"
#define Msg0208 "[safety] cast from a negative value of type '%s' to unsigned type '%s'"
#define Msg0209 "[safety] integer overflow during '+' operation on type '%s'"
#define Msg0210 "[safety] integer overflow during '-' operation on type '%s'"
#define Msg0211 "[safety] integer overflow during '*' operation on type '%s'"
#define Msg0212 "[safety] integer overflow during '+=' operation on type '%s'"
#define Msg0213 "[safety] integer overflow during '-=' operation on type '%s'"
#define Msg0214 "[safety] integer overflow during '*=' operation on type '%s'"
#define Msg0215 "[safety] '<<' shift operand value on type '%s' is greater than '%d'"
#define Msg0216 "[safety] '>>' shift operand value on type '%s' is greater than '%d'"
#define Msg0217 "[safety] integer overflow during '<<' operation on type '%s'"
#define Msg0218 "[safety] integer overflow during '>>' operation on type '%s'"
#define Msg0219 "[safety] '@abs' integer overflow on type '%s'"
#define Msg0220 "[safety] integer overflow when taking the negative value of type '%s'"
#define Msg0221 "[safety] division by zero"
#define Msg0222 "[safety] index out of range"
#define Msg0223 "[safety] index out of range"
#define Msg0224 "[safety] relative pointer points to itself, this is not legit"
#define Msg0225 "[safety] relative pointer out of range"
#define Msg0226 "[safety] relative pointer out of range"
#define Msg0227 "[safety] index out of range"
#define Msg0228 "[safety] invalid dynamic cast"
#define Msg0229 "[safety] bad slicing, lower bound is greater than upper bound"
#define Msg0230 "[safety] bad slicing, upper bound is out of range"
#define Msg0231 "copy semantic is forbidden for type '%s' because of 'swag.nocopy' attribute"
#define Msg0232 "expression cannot be evaluated at compile time"
#define Msg0233 "'#selectif' expression is not 'bool' ('%s' provided)"
#define Msg0234 "'#ast' expression is not 'string' ('%s' provided)"
#define Msg0235 "expression cannot be evaluated at compile time"
#define Msg0236 "message expression is not a string"
#define Msg0237 "message expression cannot be evaluated at compile time"
#define Msg0238 "compiler assertion failed"
#define Msg0239 "'#macro' can only be used inside a 'swag.macro' function"
#define Msg0240 "expression should be of type 'code' ('%s' provided)"
#define Msg0241 "'#semerror' has not triggered an error"
#define Msg0242 "filename cannot be evaluated at compile time"
#define Msg0243 "'#load' parameter should be of type string ('%s' provided)"
#define Msg0244 "cannot find file '%s'"
#define Msg0245 "cannot open file '%s'"
#define Msg0246 "an identifier marked with '#scopefct' cannot be used in a scope"
#define Msg0247 "an identifier marked with '#scopefct' can only be used inside a function"
#define Msg0248 "'#hastag' name cannot be evaluated at compile time"
#define Msg0249 "'#hastag' parameter must be a string ('%s' provided)"
#define Msg0250 "'#tagval' name cannot be evaluated at compile time"
#define Msg0251 "'#tagval' parameter must be a string ('%s' provided)"
#define Msg0252 "type '%s' and type '%s' defined in the command line for '%s' are incompatible"
#define Msg0253 "this is the related command line option: '%s'"
#define Msg0254 "'#callerlocation' can only be set in a function parameter declaration"
#define Msg0255 "'#callerfunction' can only be set in a function parameter declaration"
#define Msg0256 "'#function' can only be called inside a function"
#define Msg0257 "failed to load module '%s' while resolving foreign function '%s': %s"
#define Msg0258 "cannot resolve foreign function call to '%s'"
#define Msg0259 "<foreign code>"
#define Msg0260 "invalid token '['"
#define Msg0261 "this is seen as a pointer dereference ':'"
#define Msg0262 "symbol ':' is interpreted as a pointer dereference, but is followed by a symbol ('%s')"
#define Msg0263 "this should be the expression to dereference"
#define Msg0264 "invalid modifier '%s'"
#define Msg0265 "'%s' modifier is not valid for operator '%s'"
#define Msg0266 "'%s' modifier is not valid for operator '%s'"
#define Msg0267 "invalid compare operator '=', did you mean '==' ?"
#define Msg0268 "initializer list is empty"
#define Msg0269 "identifier expected"
#define Msg0270 "initializer list is empty"
#define Msg0271 "variable name or '?' expected in tuple unpacking"
#define Msg0272 "identifier '%s' starts with '__', and this is reserved by the language"
#define Msg0273 "unexpected generic parameters for variable '%s'"
#define Msg0274 "unexpected call parameters for variable '%s'"
#define Msg0275 "'@alias' variable name must be followed by a number"
#define Msg0276 "invalid '@alias' variable name '%s', '%s' is not a valid number"
#define Msg0277 "an '@alias' number must be in the range [0, 31] ('%u' provided)"
#define Msg0278 "invalid variable name '%s', cannot start with '@'"
#define Msg0279 "cannot decompose a tuple in %s"
#define Msg0280 "'%s' modifier is not valid for operator '%s'"
#define Msg0281 "'%s' modifier is not valid for operator '%s'"
#define Msg0282 "unpacking '%d' variable(s), but the tuple on the right contains '%d' element(s)"
#define Msg0283 "invalid affect operator '==', did you mean '=' ?"
#define Msg0284 "'#import' location already defined as '%s'"
#define Msg0285 "this is the previous definition"
#define Msg0286 "'#import' version already defined as '%s'"
#define Msg0287 "this is the previous definition"
#define Msg0288 "'#import' invalid version format"
#define Msg0289 "version must be of the form 'version.revision.buildnum', with each number >= 0 or the '?' character"
#define Msg0290 "error: "
#define Msg0291 "cannot unpack type '%s' which is not a struct"
#define Msg0292 "cannot unpack '%s' because it does not contain any field"
#define Msg0293 "attempt to unpack '%u' variables, but '%s' contains only '%u' field(s)"
#define Msg0294 "type to tuple conversion is not (yet?) supported for type '%s'"
#define Msg0295 "structure cannot be initialized twice"
#define Msg0296 "invalid variable name '%s' because '@alias' can only be used inside a macro or a mixin function"
#define Msg0297 "attribute 'swag.autodiscard' can only be used on a lambda variable (provided type is '%s')"
#define Msg0298 "a constant must be initialized"
#define Msg0299 "a non mutable variable must be initialized"
#define Msg0300 "a reference must be initialized"
#define Msg0301 "affect not allowed from an array"
#define Msg0302 "initialization expression cannot be evaluated at compile time"
#define Msg0303 "missing initialization expression to deduce size of array"
#define Msg0304 "invalid initialization expression for an array"
#define Msg0305 "a constant must be explicitly initialized"
#define Msg0306 "'slice' must de declared as immutable with 'const'"
#define Msg0307 "type of expression is 'void'"
#define Msg0308 "cannot deduce type from 'null'"
#define Msg0309 "unable to deduce type of %s '%s'"
#define Msg0310 "an enum variable must be initialized"
#define Msg0311 "cannot create constant because type '%s' is generic"
#define Msg0312 "cannot create variable because type '%s' is generic"
#define Msg0313 "a global variable cannot be declared as 'public'"
#define Msg0314 "invalid file format, should be ascii, utf-8 or utf-8-bom"
#define Msg0315 "Ast::output, unknown compiler function"
#define Msg0316 "identifier '%s' should be public"
#define Msg0317 "Ast::output, unknown node"
#define Msg0318 "[syntax] "
#define Msg0319 "[syntax] "
#define Msg0320 "'nodrop' instruction must be placed before 'move'"
#define Msg0321 "'nodrop' instruction defined twice"
#define Msg0322 "'move' instruction defined twice"
#define Msg0323 "'else' without a corresponding 'if'"
#define Msg0324 "'#else' without a corresponding '#if'"
#define Msg0325 "'#elif' without a corresponding '#if'"
#define Msg0326 "')' without a corresponding opening '('"
#define Msg0327 "'}' without a corresponding opening '{'"
#define Msg0328 "']' without a corresponding opening '['"
#define Msg0329 "missing '%s' %s"
#define Msg0330 "'%s' is expected instead of '%s' %s"
#define Msg0331 "a line break or ';' is expected before '%s' to close the %s"
#define Msg0332 "cannot open file '%s' for writing"
#define Msg0333 "invalid alias name '%s'"
#define Msg0334 "invalid 'self' usage in that context"
#define Msg0335 "relative type must be followed by a number of an identifier"
#define Msg0336 "relative type must be followed by an untyped integer"
#define Msg0337 "relative type invalid size"
#define Msg0338 "too many array dimensions (max is 254)"
#define Msg0339 "missing pointer declaration '*' after 'const'"
#define Msg0340 "too many pointer dimensions (max is %u)"
#define Msg0341 "missing pointer '*' or reference '&' marker after 'const'"
#define Msg0342 "'&' is invalid for a pointer"
#define Msg0343 "invalid type declaration '%s'"
#define Msg0344 "fatal error: cannot delete file '%s' (%s)"
#define Msg0345 "fatal error: cannot delete folder '%s' (%s)"
#define Msg0346 "symbol '%s' already defined in parent scope"
#define Msg0347 "invalid attribute name '%s'"
#define Msg0348 "a private definition must appear at file or namespace scope"
#define Msg0349 "a %s definition must appear at file or namespace scope"
#define Msg0350 "'%s' attribute cannot be used in a file marked with '#global export', because the whole file is implicitly public"
#define Msg0351 "cannot declare a %s symbol in a private scope (%s '%s' is private)"
#define Msg0352 "unexpected token '%s' after 'private' attribute"
#define Msg0353 "unexpected token '%s' after 'protected' attribute"
#define Msg0354 "unexpected token '%s' after 'public' attribute"
#define Msg0355 "invalid attribute name '%s'"
#define Msg0356 "empty attribute"
#define Msg0357 "this should be a 'visit' variable name or the expression to evaluate"
#define Msg0358 "this implies another 'visit' variable name"
#define Msg0359 "this should be a 'visit' variable name"
#define Msg0360 "this should be the 'visit' expression to evaluate"
#define Msg0361 "this should be the 'loop' variable name or the expression to evaluate"
#define Msg0362 "this should be the 'loop' expression to evaluate"
#define Msg0363 "this should be the right expression of the 'loop' range"
#define Msg0364 "'#mixin' replacement block can only be used inside a breakable statement"
#define Msg0365 "'#mixin' invalid replacement '%s'"
#define Msg0366 "'#mixin' empty replacement block"
#define Msg0367 "'#semerror' is invalid outside a test module (in the './tests' folder of the workspace)"
#define Msg0368 "'#semerror' cannot be in a '#if' block"
#define Msg0369 "'#global' must be defined first, at the top of the file"
#define Msg0370 "'#global export' already defined"
#define Msg0371 "'#global foreignlib' must be followed by a string"
#define Msg0372 "'#global foreignlib' must be followed by a string"
#define Msg0373 "invalid pass name '%s'"
#define Msg0374 "'#global testerror' is invalid outside a test module (in the './tests' folder of the workspace)"
#define Msg0375 "'#global testwarning' is invalid outside a test module (in the './tests' folder of the workspace)"
#define Msg0376 "'#global' invalid token '%s'"
#define Msg0377 "'#import' can only be used in the module configuration file"
#define Msg0378 "'#import' can only be declared at the top level scope"
#define Msg0379 "'#import' must be followed by a string"
#define Msg0380 "'#import' location defined twice"
#define Msg0381 "invalid location '%s'"
#define Msg0382 "'#import' version defined twice"
#define Msg0383 "invalid version '%s'"
#define Msg0384 "'#placeholder' can only be declared in a top level scope"
#define Msg0385 "'#placeholder' must be followed by an identifier"
#define Msg0386 "global 'using' must be defined at the top of the file"
#define Msg0387 "global 'using' must be defined at the top of the file"
#define Msg0388 "a namespace definition must appear either at file scope or immediately within another namespace definition"
#define Msg0389 "missing namespace name before '{'"
#define Msg0390 "missing namespace name before ';'"
#define Msg0391 "namespace name must be an identifier ('%s' provided)"
#define Msg0392 "the 'swag' namespace is reserved by the compiler"
#define Msg0393 "a namespace cannot have the same name as the module ('%s')"
#define Msg0394 "missing label identifier before '{'"
#define Msg0395 "invalid label identifier '%s'"
#define Msg0396 "invalid enum name '%s'"
#define Msg0397 "the implementation block kind (%s) does not match the type of '%s' (%s)"
#define Msg0398 "this is the declaration of '%s'"
#define Msg0399 "'{' is expected instead of '%s'"
#define Msg0400 "enum value identifier expected"
#define Msg0401 "invalid token, identifier expected"
#define Msg0402 "invalid token, ',' expected"
#define Msg0403 "invalid named parameter '%s'"
#define Msg0404 "invalid variable name '%s'"
#define Msg0405 "const before a function parameter name can only be followed by 'self'"
#define Msg0406 "'self' can only be used in an 'impl' block"
#define Msg0407 "'self' can only be used in an 'impl' block"
#define Msg0408 "invalid parameter name '%s'"
#define Msg0409 "missing function parameter type or assignment"
#define Msg0410 "invalid variable name '%s'"
#define Msg0411 "missing generic parameters"
#define Msg0412 "missing generic name or type"
#define Msg0413 "function names starting with '@' are reserved for intrinsics"
#define Msg0414 "missing function name instead of '%s'"
#define Msg0415 "a function cannot be named 'drop' (reserved by the compiler)"
#define Msg0416 "special function '%s' must have a body"
#define Msg0417 "'@power' on invalid values '%.3f' and '%.3f'"
#define Msg0418 "'@power' on invalid values '%.3f' and '%.3f'"
#define Msg0419 "'@sqrt' on an invalid value '%.3f'"
#define Msg0420 "'@asin' on an invalid value '%.3f'"
#define Msg0421 "'@acos' on an invalid value '%.3f'"
#define Msg0422 "'@log' on an invalid value '%.3f'"
#define Msg0423 "'@log2' on an invalid value '%.3f'"
#define Msg0424 "'@log10' on an invalid value '%.3f'"
#define Msg0425 "'@sqrt' on an invalid value '%.3f'"
#define Msg0426 "'@asin' on an invalid value '%.3f'"
#define Msg0427 "'@acos' on an invalid value '%.3f'"
#define Msg0428 "'@lob' on an invalid value '%.3f'"
#define Msg0429 "'@log2' on an invalid value '%.3f'"
#define Msg0430 "'@log10' on an invalid value '%.3f'"
#define Msg0431 "variable '%s' is in the bss segment (content is zero) and cannot be changed at compile time. Initialize it with '?' if this is intended"
#define Msg0432 "unknown bytecode instruction '%s'"
#define Msg0433 "bytecode execution, "
#define Msg0434 "bytecode execution, "
#define Msg0435 "exception during compile time execution !"
#define Msg0436 "this is probably a bug in the compile time part of your program"
#define Msg0437 "you can run swag with --dbgcatch to attach the bytecode debugger when the error occurs"
#define Msg0438 "'for' is invalid for an enum implementation block"
#define Msg0439 "'for' is invalid for a typeset implementation block"
#define Msg0440 "invalid generic parameters, should be naked"
#define Msg0441 "the implementation block kind (%s) does not match the type of '%s' (%s)"
#define Msg0442 "this is the declaration of '%s'"
#define Msg0443 "no matching '}' found"
#define Msg0444 "invalid name '%s'"
#define Msg0445 "the implementation block kind (%s) does not match the type of '%s' (%s)"
#define Msg0446 "this is the declaration of '%s'"
#define Msg0447 "empty tuple definition"
#define Msg0448 "identifier expected"
#define Msg0449 "invalid token '%s' in tuple type, ',' or '}' are expected here"
#define Msg0450 "'alias' is invalid in a typeset definition"
#define Msg0451 "'using' on a member is invalid in an interface definition"
#define Msg0452 "'using' on a member is invalid in a typeset definition"
#define Msg0453 "'var' is not necessary to declare a field"
#define Msg0454 "invalid affect operator '==', did you mean '=' ?"
#define Msg0455 "invalid token '%s' in variable declaration, ':' or '=' are expected here"
#define Msg0456 "invalid affect operator '==', did you mean '=' ?"
#define Msg0457 "variable must have a type or must be initialized"
#define Msg0458 "literal number is too big"
#define Msg0459 "too many digits in literal number"
#define Msg0460 "invalid binary digit '%s'"
#define Msg0461 "literal number is too big"
#define Msg0462 "too many digits in literal number"
#define Msg0463 "invalid hexadecimal digit '%s'"
#define Msg0464 "literal number is too big"
#define Msg0465 "literal number is too big"
#define Msg0466 "floating point number exponent must have at least one digit"
#define Msg0467 "invalid literal number prefix '%s'"
#define Msg0468 "index out of range (index is '%I64u', maximum index is '%I64u')"
#define Msg0469 "cannot take address of expression"
#define Msg0470 "invalid address expression"
#define Msg0471 "cannot take address of a macro"
#define Msg0472 "cannot take address of a mixin"
#define Msg0473 "cannot take address of an inline function"
#define Msg0474 "slicing operator cannot be applied on an array with multiple dimensions"
#define Msg0475 "slicing operator cannot be applied on type '%s'"
#define Msg0476 "bad slicing, lower bound '%I64u' is greater than upper bound '%I64u'"
#define Msg0477 "bad slicing, upper bound '%I64u' is out of range"
#define Msg0478 "type '%s' is immutable and cannot be changed"
#define Msg0479 "array access type should be integer ('%s' provided)"
#define Msg0480 "cannot dereference a 'void' pointer"
#define Msg0481 "cannot dereference type '%s'"
#define Msg0482 "cannot dereference a tuple type"
#define Msg0483 "cannot dereference type '%s'"
#define Msg0484 "cannot dereference a tuple type"
#define Msg0485 "array access type should be integer ('%s' provided)"
#define Msg0486 "cannot dereference a 'void' pointer"
#define Msg0487 "this should be a pointer"
#define Msg0488 "%s '%s' cannot be dereferenced like a pointer"
#define Msg0489 "'@init' first parameter should be a pointer, but is '%s'"
#define Msg0490 "'@init' count parameter should be an integer, but is '%s'"
#define Msg0491 "too many initialization parameters for type '%s'"
#define Msg0492 "'%s' first parameter should be a pointer, but is '%s'"
#define Msg0493 "cannot call '@postcopy' on type '%s' because it is marked with the 'swag.nocopy' attribute"
#define Msg0494 "'%s' count parameter should be an integer, but is '%s'"
#define Msg0495 "'%s' first parameter should be a pointer, but is '%s'"
#define Msg0496 "'%s' second parameter should be a pointer, but is '%s'"
#define Msg0497 "'%s' second parameter should be a pointer to type '%s', but points to '%s'"
#define Msg0498 "'%s' count parameter should be an integer, but is '%s'"
#define Msg0499 "unknown module dependency '%s'"
#define Msg0500 "missing test errors: %d (%d raised)"
#define Msg0501 "missing test warnings: %d (%d raised)"
#define Msg0502 "cannot open file '%s': %s"
#define Msg0503 "internal compiler error during semantic (%s)"
#define Msg0504 "operation '%s' not allowed, left type is '%s' and right type is '%s'"
#define Msg0505 "%s overflow, maximum size is 0x%I64x bytes"
#define Msg0506 "operation '%s' not allowed on %s '%s'"
#define Msg0507 "fatal error: invalid module '%s', configuration file '%s' is missing"
#define Msg0508 "cannot find '%s' in module folder '%s'"
#define Msg0509 "cannot access file '%s'"
#define Msg0510 "cannot fetch file '%s' for module dependency '%s'"
#define Msg0511 "dependency module folder '%s' does not exist"
#define Msg0512 "dependency module folder '%s' does not exist"
#define Msg0513 "cannot resolve module dependency '%s' ('location' is empty)"
#define Msg0514 "invalid 'location' format; should have the form 'location=\"mode@accesspath\"'"
#define Msg0515 "invalid 'location' mode; should be 'swag' or 'disk', not '%s'"
#define Msg0516 "cannot resolve dependency to module '%s' because of two different major versions ('%d' and '%d')"
#define Msg0517 "this is the other '#import'"
#define Msg0518 "cannot resolve dependency to module '%s', version '%s' cannot be found at location '%s'"
#define Msg0519 "command line error: invalid --stack-size value (%s), valid range is [%s, %s]"
#define Msg0520 "command line error: invalid abi '%s' for x64 backend"
#define Msg0521 "command line error: invalid vendor '%s' for x64 backend"
#define Msg0522 "command line error: invalid os '%s' for x64 backend"
#define Msg0523 "command line error: invalid arch '%s' for x64 backend"
#define Msg0524 "cannot open file '%s' for writing: %s"
#define Msg0525 "cannot write to file '%s': %s"
#define Msg0526 "[safety] destination pointer of '@memcpy' is null"
#define Msg0527 "[safety] source pointer of '@memcpy' is null"
#define Msg0528 "[safety] destination pointer of '@memmove' is null"
#define Msg0529 "[safety] source pointer of '@memmove' is null"
#define Msg0530 "[safety] destination pointer of '@memset' is null"
#define Msg0531 "[safety] first pointer of '@memcmp' is null"
#define Msg0532 "[safety] second pointer of '@memcmp' is null"
#define Msg0533 "[safety] pointer of '@cstrlen' is null"
#define Msg0534 "uncatched error when calling '%s'"
#define Msg0535 "'%s' can only be used before a call that can raise errors"
#define Msg0536 "stack overflow (maximum stack size is '--stack-size:%s')"
#define Msg0537 "cannot convert typeinfo '%s' to runtime typeinfo"
#define Msg0538 "fatal error: cannot resolve type '%s' of command line tag '%s'"
#define Msg0539 "fatal error: type '%s' for tag '%s' is not a valid tag type"
#define Msg0540 "fatal error: missing workspace folder '--workspace'"
#define Msg0541 "fatal error: workspace folder '%s' does not exist"
#define Msg0542 "fatal error: invalid workspace '%s', subfolders 'modules/' and 'tests/' do not exist"
#define Msg0543 "cannot create public directory '%s'"
#define Msg0544 "cannot create public directory '%s'"
#define Msg0545 "fatal error: cannot create target directory '%s'"
#define Msg0546 "fatal error: cache directory '%s' does not exist"
#define Msg0547 "fatal error: cannot cache target directory '%s'"
#define Msg0548 "fatal error: cannot cache target directory '%s'"
#define Msg0549 "module '%s', cannot resolve %s '%s'"
#define Msg0550 "module '%s', cannot resolve %s"
#define Msg0551 "this is the declaration"
#define Msg0552 "some errors have been found in compiler bootstrap !!! exiting..."
#define Msg0553 "some errors have been found in compiler bootstrap !!! exiting..."
#define Msg0554 "some errors have been found in compiler runtime !!! exiting..."
#define Msg0555 "some errors have been found in compiler runtime !!! exiting..."
#define Msg0556 "module '%s' cannot be found in that workspace"
#define Msg0557 "dependency module '%s' cannot be found in that workspace"
#define Msg0558 "llvm backend cannot create target '%s'"
#define Msg0559 "'move' cannot be applied to a constant expression"
#define Msg0560 "relative pointer arithmetic out of range ('%d')"
#define Msg0561 "relative pointer arithmetic out of range ('%d')"
#define Msg0562 "relative pointer arithmetic out of range ('%d')"
#define Msg0563 "relative pointer arithmetic out of range ('%d')"
#define Msg0564 "affect operation not allowed, left expression is const"
#define Msg0565 "affect operation not allowed, left expression is not an l-value"
#define Msg0566 "affect operation not allowed"
#define Msg0567 "affect operation not allowed, left expression is not a variable"
#define Msg0568 "affect operation not allowed, left expression is immutable"
#define Msg0569 "cannot affect an expression of type 'void'"
#define Msg0570 "'%s' operation not allowed on type 'any'"
#define Msg0571 "affect not allowed on %s '%s'"
#define Msg0572 "affect not allowed, '%s' is %s"
#define Msg0573 "invalid operation on a tuple type"
#define Msg0574 "affect to tuple is not possible because right expression is not compatible"
#define Msg0575 "invalid operation on a tuple type"
#define Msg0576 "invalid operation on a tuple type"
#define Msg0577 "invalid operation on a tuple type"
#define Msg0578 "pointer arithmetic not allowed on 'typeinfo'"
#define Msg0579 "pointer arithmetic not allowed with operand type '%s'"
#define Msg0580 "invalid operation on a tuple type"
#define Msg0581 "invalid operation on a tuple type"
#define Msg0582 "'%s' is not a valid attribute, it's %s"
#define Msg0583 "attribute '%s' can only be applied to %s"
#define Msg0584 "it is applied on this %s"
#define Msg0585 "this is attribute '%s'"
#define Msg0586 "attribute '%s' cannot be used in that context"
#define Msg0587 "this is attribute '%s'"
#define Msg0588 "attribute '%s' cannot be applied to %s"
#define Msg0589 "this is the %s"
#define Msg0590 "this is attribute '%s'"
#define Msg0591 "attribute '%s' assigned twice to '%s' ('swag.attributeMulti' is not present in the declaration of '%s')"
#define Msg0592 "this is the faulty attribute"
#define Msg0593 "'swag.safety' invalid value '%s'"
#define Msg0594 "'swag.optim' invalid value '%s'"
#define Msg0595 "'swag.pack' value must be 0 or a power of two ('%d' provided)"
#define Msg0596 "'swag.align' value must be a power of two ('%d' provided)"
#define Msg0597 "invalid attribute usage"
#define Msg0598 "invalid attribute '%s'"
#define Msg0599 "this is the definition of '%s'"
#define Msg0600 "attribute '%s' does not have the 'File' usage, and cannot be used with '#global'"
#define Msg0601 "this is the definition of '%s'"
#define Msg0602 "attribute parameter cannot be evaluated at compile time"
#define Msg0603 "cannot delete file '%s': %s"
#define Msg0604 "cannot create directory '%s': %s"
#define Msg0605 "not all control paths of %s return a value"
#define Msg0606 "%s must return a value"
#define Msg0607 "a switch without an expression cannot be marked as 'swag.complete'"
#define Msg0608 "invalid switch type 'any', you need to cast to a concrete type"
#define Msg0609 "invalid switch type '%s'"
#define Msg0610 "switch body is empty"
#define Msg0611 "switch value '%s' already defined"
#define Msg0612 "switch value '%s' already defined"
#define Msg0613 "switch value '%d' already defined"
#define Msg0614 "switch value '%f' already defined"
#define Msg0615 "expression cannot be evaluated at compile time, and switch is 'swag.complete'"
#define Msg0616 "'default' is invalid in a switch marked with 'swag.complete'"
#define Msg0617 "'swag.complete' attribute cannot be used on a switch with type '%s'"
#define Msg0618 "switch is incomplete (missing '%s.%s')"
#define Msg0619 "this is the missing value"
#define Msg0620 "switch is incomplete (missing '%s.%s')"
#define Msg0621 "this is the missing value"
#define Msg0622 "switch is incomplete (missing '%s.%s')"
#define Msg0623 "this is the missing value"
#define Msg0624 "cannot visit a tuple"
#define Msg0625 "special named visit is only valid for struct ('%s' provided)"
#define Msg0626 "too many 'visit' alias names (maximum is 2, but %u are provided)"
#define Msg0627 "cannot visit a type variadic by pointer"
#define Msg0628 "this cannot be visited"
#define Msg0629 "invalid type '%s' for 'visit'"
#define Msg0630 "'@index' can only be used inside a breakable loop"
#define Msg0631 "unknown label '%s'"
#define Msg0632 "'break' can only be used inside a breakable block"
#define Msg0633 "'fallthrough' can only be used inside a 'switch' block"
#define Msg0634 "'fallthrough' can only be used inside a 'case' block"
#define Msg0635 "'fallthrough' cannot be used in the last 'case' of the swtich"
#define Msg0636 "unknown label '%s'"
#define Msg0637 "'continue' can only be used inside a breakable loop"
#define Msg0638 "'continue' can only be used inside a breakable loop"
#define Msg0639 "label name '%s' already defined in the hierarchy"
#define Msg0640 "this is the other definition"
#define Msg0641 "expression cannot be evaluated at compile time"
#define Msg0642 "expression cannot be evaluated at compile time"
#define Msg0643 "expression cannot be evaluated at compile time"
#define Msg0644 "expression cannot be evaluated at compile time"
#define Msg0645 "variable initialized twice, first with type arguments, and then with this assignment"
#define Msg0646 "'%s' is %s and should be an interface"
#define Msg0647 "this is the definition of '%s'"
#define Msg0648 "'%s' is %s and should be a struct"
#define Msg0649 "this is the definition of '%s'"
#define Msg0650 "function '%s' is not part of interface '%s'"
#define Msg0651 "this is the definition of interface '%s'"
#define Msg0652 "function '%s' has an incorrect signature for interface '%s'"
#define Msg0653 "should be"
#define Msg0654 "missing first parameter 'self' for interface function '%s'"
#define Msg0655 "bad type for first parameter of interface function implementation ('self' expected, '%s' provided)"
#define Msg0656 "bad type for first parameter of interface function implementation ('self' expected, '%s' provided)"
#define Msg0657 "some functions of interface '%s' are not implemented"
#define Msg0658 "this is the definition of '%s'"
#define Msg0659 "the implementation block for '%s' is private but the corresponding identifier is not"
#define Msg0660 "the implementation block for '%s' is not private but the corresponding identifier is"
#define Msg0661 "implementation block is not defined in the same scope as '%s' ('impl' parent scope is '%s', '%s' parent scope is '%s')"
#define Msg0662 "'%s' is %s and should be a struct or an enum"
#define Msg0663 "this is the definition of '%s'"
#define Msg0664 "unsupported alias as an implementation block name"
#define Msg0665 "symbol already defined"
#define Msg0666 "struct cannot be marked with 'swag.opaque' because it is not public"
#define Msg0667 "struct cannot be marked with 'swag.opaque' because the whole file is exported ('#global export')"
#define Msg0668 "'using' is invalid on a constant"
#define Msg0669 "'using' on a field is only valid for a struct type ('%s' provided)"
#define Msg0670 "initialization expression cannot be evaluated at compile time"
#define Msg0671 "type '%s' is generic, but struct '%s' does not declare generic parameters"
#define Msg0672 "cannot resolve struct '%s' because type '%s' is generic"
#define Msg0673 "cannot find structure member '%s' to compute variable relocation"
#define Msg0674 "structure member name '%s' starts with 'item', and this is reserved by the language"
#define Msg0675 "embedded struct '%s' cannot be public"
#define Msg0676 "an interface can only contain members of type 'lambda' ('%s' provided)"
#define Msg0677 "missing parameters for interface member '%s' ('self' expected as first parameter)"
#define Msg0678 "bad type for first parameter of interface member ('self' expected, '%s' provided)"
#define Msg0679 "bad type for first parameter of interface member ('self' expected, '%s' provided)"
#define Msg0680 "cannot initialize an interface member"
#define Msg0681 "cannot resolve interface because type '%s' is generic"
#define Msg0682 "cannot relocate an interface member"
#define Msg0683 "interface '%s' is empty"
#define Msg0684 "embedded interface '%s' cannot be public"
#define Msg0685 "embedded typeset '%s' cannot be public"
#define Msg0686 "cannot resolve typeset because type '%s' is generic"
#define Msg0687 "cannot relocate a typeset member"
#define Msg0688 "typeset '%s' is empty"
#define Msg0689 "'using' on a variable cannot be used in '%s' scope"
#define Msg0690 "'using' cannot be used on a typeset variable"
#define Msg0691 "'using' cannot be used on an enum variable"
#define Msg0692 "'using' cannot be used on a variable of type '%s'"
#define Msg0693 "'using' cannot be used on a variable of type '%s'"
#define Msg0694 "invalid 'using' type"
#define Msg0695 "'using' cannot be used on type %s"
#define Msg0696 "symbol already defined"
#define Msg0697 "invalid type '%s' for enum flags (should be unsigned integer)"
#define Msg0698 "invalid type '%s' for enum index (should be integer)"
#define Msg0699 "dimension of enum array type '%s' must be specified"
#define Msg0700 "enum array type '%s' must be const"
#define Msg0701 "enum slice type '%s' must be const"
#define Msg0702 "invalid enum type '%s'"
#define Msg0703 "expression cannot be evaluated at compile time"
#define Msg0704 "expression cannot be evaluated at compile time"
#define Msg0705 "expression cannot be evaluated at compile time"
#define Msg0706 "enum value '%s' of type '%s' must be initialized"
#define Msg0707 "enum value '%s' of type '%s' must be initialized"
#define Msg0708 "enum value '%s' is out of range of 'u8'"
#define Msg0709 "cannot deduce flag value of '%s' because previous value is not power of two"
#define Msg0710 "enum value '%s' is out of range of 'u16'"
#define Msg0711 "cannot deduce flag value of '%s' because previous value is not power of two"
#define Msg0712 "enum value '%s' is out of range of 'u32'"
#define Msg0713 "cannot deduce flag value of '%s' because previous value is not power of two"
#define Msg0714 "enum value '%s' is out of range of 'u64'"
#define Msg0715 "cannot deduce flag value of '%s' because previous value is not power of two"
#define Msg0716 "enum value '%s' is out of range of 's8'"
#define Msg0717 "enum value '%s' is out of range of 's16'"
#define Msg0718 "enum value '%s' is out of range of 's32'"
#define Msg0719 "enum value '%s' is out of range of 's64'"
#define Msg0720 "command line error: invalid argument '%s'"
#define Msg0721 "command line error: invalid argument '%s'"
#define Msg0722 "command line error: argument '%s' must be followed by '%s'"
#define Msg0723 "command line error: argument '%s' must be followed by '%s'"
#define Msg0724 "command line error: argument '%s' must be followed by 'true' or 'false' ('%s')"
#define Msg0725 "command line error: argument '%s' must be followed by a string"
#define Msg0726 "command line error: argument '%s' must be followed by a string"
#define Msg0727 "command line error: argument '%s' must be followed by an integer value"
#define Msg0728 "command line error: argument '%s' must be followed by an integer value ('%s')"
#define Msg0729 "type 'code' is only valid in a 'swag.macro' or 'swag.mixin' function"
#define Msg0730 "type 'alias' is only valid in a 'swag.macro' or 'swag.mixin' function"
#define Msg0731 "invalid type '%s' for attribute parameter"
#define Msg0732 "invalid type '%s' for attribute parameter"
#define Msg0733 "inline function has variadic arguments, this is not yet supported"
#define Msg0734 "variadic argument should be the last one"
#define Msg0735 "inline function has variadic arguments, this is not yet supported"
#define Msg0736 "variadic argument should be the last one"
#define Msg0737 "compiler instruction '%s' is invalid as a default parameter value"
#define Msg0738 "parameter '%d', missing default value"
#define Msg0739 "#main directive already defined"
#define Msg0740 "this is the other definition"
#define Msg0741 "'@alias' names are not all contiguous in function '%s' (missing '@alias%u')"
#define Msg0742 "a function with the 'swag.foreign' attribute cannot have a body"
#define Msg0743 "a compiler special function cannot have the 'swag.inline' attribute"
#define Msg0744 "#test functions can only be used in a test module (in the './tests' folder of the workspace)"
#define Msg0745 "a function with the 'swag.test' attribute cannot have a return value"
#define Msg0746 "a function with the 'swag.test' attribute cannot have parameters"
#define Msg0747 "%s cannot be public"
#define Msg0748 "not all control paths of %s return a value"
#define Msg0749 "%s missing return value"
#define Msg0750 "'#compiler' function must have 'swag.CompilerMsgMask' as a parameter"
#define Msg0751 "'#compiler' function must have 'swag.CompilerMsgMask' as a parameter"
#define Msg0752 "returning an array of relative types is not supported"
#define Msg0753 "function '%s' cannot have the 'swag.complete' attribute, this is reserved for 'opAffect'"
#define Msg0754 "function '%s' cannot have the 'swag.implicit' attribute, this is reserved for 'opAffect' and 'opCast'"
#define Msg0755 "function '%s' cannot have the 'swag.noreturn' attribute without 'swag.macro' or 'swag.mixin'"
#define Msg0756 "function '%s' cannot have the 'swag.implicit' attribute because it's generic"
#define Msg0757 "function '%s' is marked with 'swag.macro' and 'swag.inline' attributes at the same time"
#define Msg0758 "function '%s' is marked with 'swag.macro' and 'swag.mixin' attributes at the same time"
#define Msg0759 "function '%s' is marked with 'swag.mixin' and 'swag.inline' attributes at the same time"
#define Msg0760 "function '%s' is marked with 'swag.mixin' and 'swag.macro' attributes at the same time"
#define Msg0761 "function '%s' cannot be marked with 'swag.macro' attribute"
#define Msg0762 "function '%s' cannot be marked with 'swag.mixin' attribute"
#define Msg0763 "function '%s' cannot be marked with 'swag.inline' attribute"
#define Msg0764 "a function cannot return a value of type '%s'"
#define Msg0765 "struct '%s' has the 'swag.nocopy' attribute, so 'opPostCopy' is irrelevant"
#define Msg0766 "function cannot have a return type because it is flagged with the 'swag.noreturn' attribute"
#define Msg0767 "function cannot have the 'swag.autodiscard' attribute because it returns 'void'"
#define Msg0768 "unreachable code"
#define Msg0769 "'retval' can only be used in a function body"
#define Msg0770 "'retval' can only be used in a function body"
#define Msg0771 "'retval' cannot be used in a function that returns nothing"
#define Msg0772 "missing a return value ('%s')"
#define Msg0773 "the function should return nothing"
#define Msg0774 "returning a value of type '%s', but the function does not declare a return type"
#define Msg0775 "cannot expand '%s' because this is recursive"
#define Msg0776 "invalid name alias"
#define Msg0777 "invalid name alias, should be an identifier"
#define Msg0778 "invalid name alias, should be a single identifier"
#define Msg0779 "alias name '%s' is unused and should be removed"
#define Msg0780 "alias name '%s' is unused and should be removed"
#define Msg0781 "cannot expand '%s' in global scope because it contains sub declarations, this is not (yet?) supported"
#define Msg0782 "'@mkforeign' must have a lambda type as a first parameter"
#define Msg0783 "'@mkforeign' must have a 'const *void' as a second parameter"
#define Msg0784 "'@mkcallback' must have a lambda value as a first parameter"
#define Msg0785 "callback type not supported, too many parameters (maximum is '%d')"
#define Msg0786 "callback return type '%s' not supported"
#define Msg0787 "'%s' must have a pointer as a first parameter"
#define Msg0788 "'%s' cannot have 'null' as first parameter"
#define Msg0789 "'@mkany' must have a pointer as a first parameter"
#define Msg0790 "'@mkany' cannot have 'null' as first parameter"
#define Msg0791 "'pointer to value and type are not related (first parameter is a pointer to type '%s' but second parameter is type '%s')"
#define Msg0792 "'@mkany' must have a 'typeinfo' or a type value as a second parameter ('%s' provided)"
#define Msg0793 "'@mkinterface' must have a one dimension pointer or a struct as a first parameter"
#define Msg0794 "'@mkinterface' must have a typeinfo as a second parameter"
#define Msg0795 "'@mkinterface' must have an interface as a third parameter"
#define Msg0796 "'@dataof' cannot be used on a tuple type"
#define Msg0797 "'@dataof' cannot be applied to expression of type '%s'"
#define Msg0798 "expression cannot be evaluated at compile time"
#define Msg0799 "expression cannot be evaluated at compile time"
#define Msg0800 "'@countof' cannot be used on a tuple type"
#define Msg0801 "expression should be of type integer, but is '%s'"
#define Msg0802 "constant value should be unsigned, but is '%d'"
#define Msg0803 "constant value should be unsigned, but is '%d'"
#define Msg0804 "constant value should be unsigned, but is '%d'"
#define Msg0805 "constant value should be unsigned, but is '%I64d'"
#define Msg0806 "'@spread' can only be called as a function parameter"
#define Msg0807 "expression of type '%s' cannot be spreaded"
#define Msg0808 "expression cannot be evaluated at compile time"
#define Msg0809 "expression cannot be evaluated at compile time"
#define Msg0810 "cannot evaluate type in that context because it's generic"
#define Msg0811 "expression cannot be evaluated at compile time"
#define Msg0812 "size cannot be computed because expression is generic"
#define Msg0813 "expression cannot be evaluated at compile time"
#define Msg0814 "alignement cannot be computed because expression is generic"
#define Msg0815 "expression cannot be evaluated at compile time"
#define Msg0816 "fatal error: missing workspace folder '--workspace'"
#define Msg0817 "fatal error: workspace folder '%s' already exists"
#define Msg0818 "fatal error: cannot create directory '%s'"
#define Msg0819 "fatal error: cannot create directory '%s'"
#define Msg0820 "fatal error: cannot create directory '%s'"
#define Msg0821 "fatal error: cannot create directory '%s'"
#define Msg0822 "fatal error: cannot create directory '%s'"
#define Msg0823 "fatal error: cannot create directory '%s'"
#define Msg0824 "fatal error: cannot create file '%s'"
#define Msg0825 "fatal error: cannot create directory '%s'"
#define Msg0826 "fatal error: cannot create file '%s'"
#define Msg0827 "negate an unsigned type ('%s') is not allowed"
#define Msg0828 "minus operation not allowed on type '%s'"
#define Msg0829 "cannot negate number '%d' because '%u' is not in the range of 's8'"
#define Msg0830 "cannot negate number '%d' because '%u' is not in the range of 's16'"
#define Msg0831 "cannot negate number '%d' because '%u' is not in the range of 's32'"
#define Msg0832 "cannot negate number '%I64d' because '%I64u' is not in the range of 's64'"
#define Msg0833 "bit inversion operation not allowed on type '%s'"
#define Msg0834 "%s size overflow"
#define Msg0835 "expected an identifier, found symbol '%s'"
#define Msg0836 "expected an identifier, found symbol '%s'"
#define Msg0837 "expected an identifier, found symbol '%s'"
#define Msg0838 "type 'Self' cannot be used outside an 'impl', 'struct' or 'interface' block"
#define Msg0839 "a struct initialization must be done with '{}' and not parenthesis (this is reserved for function calls)"
#define Msg0840 "array size must be defined before the type name"
#define Msg0841 "invalid token '%s' after 'discard'"
#define Msg0842 "'%s' can only be used inside a function"
#define Msg0843 "invalid 'try' inside '%s' expression"
#define Msg0844 "invalid 'catch' inside '%s' expression"
#define Msg0845 "invalid 'assume' inside '%s' expression"
#define Msg0846 "invalid 'throw' inside '%s' expression"
#define Msg0847 "'%s' must be immediatly followed by an identifier"
#define Msg0848 "'catch' can only be used inside a function"
#define Msg0849 "invalid 'try' inside '%s' expression"
#define Msg0850 "invalid 'catch' inside '%s' expression"
#define Msg0851 "invalid 'assume' inside '%s' expression"
#define Msg0852 "invalid 'throw' inside '%s' expression"
#define Msg0853 "'%s' must be immediatly followed by an identifier"
#define Msg0854 "'throw' can only be used inside a function"
#define Msg0855 "invalid 'try' inside '%s' expression"
#define Msg0856 "invalid 'catch' inside '%s' expression"
#define Msg0857 "invalid 'assume' inside '%s' expression"
#define Msg0858 "invalid 'throw' inside '%s' expression"
#define Msg0859 "[safety] dereferencing a null pointer"
#define Msg0860 "[safety] dereferencing a null pointer"
#define Msg0861 "intrinsic parameter expression cannot be empty"
#define Msg0862 "expression is empty"
#define Msg0863 "missing 'if' boolean expression before '{'"
#define Msg0864 "missing 'while' boolean expression before '{'"
#define Msg0865 "'case' or 'default' expected"
#define Msg0866 "'default' already defined"
#define Msg0867 "missing 'case' expression before ':'"
#define Msg0868 "missing 'case' expression before 'break'"
#define Msg0869 "'case' statement is empty"
#define Msg0870 "opVisit special name expected"
#define Msg0871 "missing the 'visit' expression to evaluate before '{'"
#define Msg0872 "missing another 'visit' variable name after ',' and before ':'"
#define Msg0873 "missing the 'visit' expression to evaluate before '{'"
#define Msg0874 "missing the 'loop' expression to evaluate before '{'"
#define Msg0875 "missing the 'loop' expression to evaluate before '{'"
#define Msg0876 "invalid label name, you should add ';' or put a valid label identifier"
#define Msg0877 "invalid label name, identifier expected"
#define Msg0878 "missing '#if' expression"
#define Msg0879 "missing '#global if' expression"
#define Msg0880 "no corresponding '}' has been found"
#define Msg0881 "no corresponding '}' has been found"
#define Msg0882 "no corresponding '}' has been found"
#define Msg0883 "missing function parameters before '{'"