
#unittest pass lexer;
#unittest error;
È

#unittest error;
1_.00_00_1
#unittest error;
1._00_00_1
#unittest error;
1.00_00_1_
#unittest error;
0È

#unittest error;
0.1's8
#unittest error;
0.1's16
#unittest error;
0.1's32
#unittest error;
0.1's64
#unittest error;
0.1'u8
#unittest error;
0.1'u16
#unittest error;
0.1'u32
#unittest error;
0.1'u64

0.1
145.1'f32
145.1'f64
1'f32
1'f64
100_1.00_00_1
0.1
