SCBE_MICRO_OP(Ignore, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Label, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Debug, MOF_ZERO, MOF_ZERO)

SCBE_MICRO_OP(SymbolRelocationRef, MOF_NAME, MOF_ZERO)
SCBE_MICRO_OP(SymbolRelocationAddress, MOF_REG_A, MOF_VALUE_A | MOF_VALUE_B)
SCBE_MICRO_OP(SymbolRelocationValue, MOF_REG_A, MOF_VALUE_A | MOF_VALUE_B)
SCBE_MICRO_OP(SymbolGlobalString, MOF_REG_A, MOF_NAME)
SCBE_MICRO_OP(SymbolRelocationPtr, MOF_REG_A, MOF_NAME)

SCBE_MICRO_OP(Push, MOF_REG_A, MOF_ZERO)
SCBE_MICRO_OP(Pop, MOF_REG_A, MOF_ZERO)
SCBE_MICRO_OP(Enter, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Leave, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Nop, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Ret, MOF_ZERO, MOF_ZERO)

SCBE_MICRO_OP(LoadParam, MOF_REG_A | MOF_OPBITS_A, MOF_VALUE_A)
SCBE_MICRO_OP(LoadAddressParam, MOF_REG_A, MOF_VALUE_A | MOF_BOOL)
SCBE_MICRO_OP(LoadSignedExtendParam, MOF_REG_A | MOF_OPBITS_A, MOF_VALUE_B | MOF_OPBITS_B)
SCBE_MICRO_OP(LoadZeroExtendParam, MOF_REG_A | MOF_OPBITS_A, MOF_VALUE_B | MOF_OPBITS_B)
SCBE_MICRO_OP(StoreParam, MOF_ZERO, MOF_ZERO)

SCBE_MICRO_OP(CallLocal, MOF_NAME, MOF_ZERO)
SCBE_MICRO_OP(CallExtern, MOF_NAME, MOF_ZERO)
SCBE_MICRO_OP(CallIndirect, MOF_REG_A, MOF_ZERO)

SCBE_MICRO_OP(JumpTable, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Jump0, MOF_JUMP_TYPE | MOF_OPBITS_A, MOF_ZERO)
SCBE_MICRO_OP(Jump1, MOF_REG_A, MOF_ZERO)
SCBE_MICRO_OP(Jump2, MOF_JUMP_TYPE | MOF_VALUE_A, MOF_ZERO)
SCBE_MICRO_OP(PatchJump, MOF_ZERO, MOF_ZERO)

SCBE_MICRO_OP(Load0, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_OPBITS_A)
SCBE_MICRO_OP(Load1, MOF_REG_A | MOF_OPBITS_A, MOF_REG_A | MOF_OPBITS_A)
SCBE_MICRO_OP(Load2, MOF_ZERO, MOF_ZERO)
SCBE_MICRO_OP(Load3, MOF_REG_A, MOF_VALUE_A)
SCBE_MICRO_OP(Load4, MOF_REG_A | MOF_OPBITS_A, MOF_VALUE_A)
SCBE_MICRO_OP(Load5, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_VALUE_A)

SCBE_MICRO_OP(LoadSignedExtend0, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_VALUE_A | MOF_OPBITS_B)
SCBE_MICRO_OP(LoadSignedExtend1, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_OPBITS_B)
SCBE_MICRO_OP(LoadZeroExtend0, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_VALUE_A | MOF_OPBITS_B)
SCBE_MICRO_OP(LoadZeroExtend1, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_OPBITS_B)

SCBE_MICRO_OP(LoadAddress0, MOF_REG_A, MOF_REG_B | MOF_VALUE_A)
SCBE_MICRO_OP(LoadAddress1, MOF_REG_A, MOF_REG_B | MOF_REG_C | MOF_VALUE_A | MOF_OPBITS_A)

SCBE_MICRO_OP(Store0, MOF_REG_A | MOF_VALUE_A, MOF_REG_B | MOF_OPBITS_A)
SCBE_MICRO_OP(Store1, MOF_REG_A | MOF_VALUE_A, MOF_VALUE_B | MOF_OPBITS_A)

SCBE_MICRO_OP(Cmp0, MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_OPBITS_A)
SCBE_MICRO_OP(Cmp1, MOF_REG_A | MOF_OPBITS_A, MOF_VALUE_A | MOF_OPBITS_A)
SCBE_MICRO_OP(Cmp2, MOF_REG_A | MOF_VALUE_A, MOF_REG_B | MOF_OPBITS_A)
SCBE_MICRO_OP(Cmp3, MOF_REG_A | MOF_VALUE_A, MOF_VALUE_B | MOF_OPBITS_A)

SCBE_MICRO_OP(Set, MOF_CPU_COND | MOF_REG_A, MOF_ZERO)

SCBE_MICRO_OP(Clear0, MOF_REG_A | MOF_OPBITS_A, MOF_ZERO)
SCBE_MICRO_OP(Clear1, MOF_REG_A | MOF_VALUE_A | MOF_VALUE_B, MOF_ZERO)
SCBE_MICRO_OP(Copy, MOF_REG_A | MOF_REG_B | MOF_VALUE_A, MOF_ZERO)

SCBE_MICRO_OP(OpUnary0, MOF_CPU_OP | MOF_REG_A | MOF_VALUE_A, MOF_ZERO)
SCBE_MICRO_OP(OpUnary1, MOF_CPU_OP | MOF_REG_A | MOF_OPBITS_A, MOF_ZERO)

SCBE_MICRO_OP(OpBinary0, MOF_CPU_OP | MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_OPBITS_A)
SCBE_MICRO_OP(OpBinary1, MOF_CPU_OP | MOF_REG_A | MOF_VALUE_A, MOF_REG_B | MOF_OPBITS_A)
SCBE_MICRO_OP(OpBinary2, MOF_CPU_OP | MOF_REG_A | MOF_OPBITS_A, MOF_VALUE_A | MOF_OPBITS_A)
SCBE_MICRO_OP(OpBinary3, MOF_CPU_OP | MOF_REG_A | MOF_VALUE_A, MOF_VALUE_B | MOF_OPBITS_A)
SCBE_MICRO_OP(OpBinary4, MOF_CPU_OP | MOF_REG_A | MOF_OPBITS_A, MOF_REG_B | MOF_VALUE_A)
SCBE_MICRO_OP(MulAdd, MOF_REG_A | MOF_OPBITS_A, MOF_REG_A | MOF_REG_B | MOF_REG_C | MOF_OPBITS_A)

